### ISSUE TITLE
Official GDPR compliance Module translation

### ISSUE THREAD

**Issue by positrongr** [PrestaShop/PrestaShop#10136]
Hello,

We are using prestashop 1.7.4.1 and Official GDPR compliance Module  v1.1.0
While trying to translate the module and save the translated fields we get a blank page.
After re-login at BO we see all the translations saved but not appearing in front office.
In case of further field translations or modyfing the exist ones , after save, we get a blank page again.

Can you help us for this?
Thank you in advance

**Comment by khouloudbelguith** [comment]
Hi @positrongr,

The translation of the module RGPD does not apply in the front office, it is fixed in the last version 1.7.4.2.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9326
Thanks to check and feedback.
About the blank page after saving fields, I did not manage to reproduce the issue with PS 1.7.4.1 & Official GDPR compliance Module v1.1.0, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Best regards, Khouloud

**Comment by positrongr** [comment]
Hi khouloudbelguith,

Thanks for the reply. The PHP error log we get is:
Notice on line 101 in file /home/lingeristas/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php
[8] SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php70) failed: Permission denied (13)
and the debug mode report
![debug](https://user-images.githubusercontent.com/42682407/44653808-64a02300-a9f8-11e8-9a79-8af1f49b0c25.png)
Thank you in advance
Kind regards

**Comment by khouloudbelguith** [comment]
Hi @positrongr,

You have a permission issue on your server [Permission denied].
Thanks to check your issue with your host & feedback.

Best regards, Khouloud

**Comment by positrongr** [comment]
Hi Khouloud,

We have fix the server permission issue and debug mode works properly without errors.
We are still getting blank page after saving fields for translation of GDPR module. Besides while trying
to upgrade our Prestashop from 1.7.4.1 to 1.7.4.2. with 1-click upgrade module , it does not allows us to upgrade getting:
Check your configuration
Required parameters: Please fix the following error(s)
Optional parameters: OK
without showing any error.

Thank you in advance

**Comment by khouloudbelguith** [comment]
Hi @positrongr,

It seems that a description is missing, and that's why it could not be listed in the "following errors". 
Here's the PR about that issue in https://github.com/PrestaShop/PrestaShop/pull/9407.
If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @positrongr,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Best regards, Khouloud
