### ISSUE TITLE
Shop not found on line 418 in Shop.php

### ISSUE THREAD

**Issue by Prestashopnewbie** [PrestaShop/PrestaShop#10220]
Already 2 weeks I discovered a problem, but the shop was working fine in the front except on exporting data to others. So I was searching for solutions... 

But I didn`t find one.... 

Now this morning, just it is a fenomenal problem, I cant reach the shop anymore from the back or from the front... Just a blank error page... 

I didn`t changed a thing!

In the log files I only see this lines: 

Exception log:
`*ERROR* 	v1.7.4.2	2018/08/31 - 09:01:22: Shop not found at line 363 in file classes/shop/Shop.php`

Prod log:
`[2018-08-31 08:36:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Maximum function nesting level of '256' reached, aborting!" at RecursiveDirectoryIterator.php line 113 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Maximum function nesting level of '256' reached, aborting! at RecursiveDirectoryIterator.php:113)"} []
[2018-08-31 08:36:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Maximum function nesting level of '256' reached, aborting!" at RecursiveDirectoryIterator.php line 113 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Maximum function nesting level of '256' reached, aborting! at RecursiveDirectoryIterator.php:113)"} []
`

How to solve this? 

Prestashop version: 1.7.4.2
php version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
Hi, 

Now I changed the PHP version to a lower version (5.6)  & cleared the cache.
The shop is working again. 

But for your information:

Info_outline Server Data
Server Data Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Server software version: Apache/2
PHP version: 5.6.37
Memory Limit:-1
Maximum run time: 10000
Maximum file size for uploads: 50m
Info_outline Database Information
MySQL version: 10.2.16-MariaDB
MySQL server: localhost
Tables prefix: psc5_
MySQL Engine: InnoDB
MySQL-Driver: DbPDO
Info_outline Store Information
PrestaShop version: 1.7.4.2
Shop-URL: http://natureldeluxe.be/
Current used theme: Ap_olay
Info_outline Email Configuration
Mail method: You use the PHP mail () function.
Info_outline your details
Your Web browser: Mozilla/5.0 (Windows NT 6.1; Win64 x64) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Info_outline Check your configuration
Required Parameters: OK
Optional Parameters: OK

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

Thanks for your feedback.
Since it is fixed, can I close the issue?

Best regards, Khouloud

**Comment by MathiasReker** [comment]
Change memory limit from -1 to 512

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

The required memory_limit is 64MB.
You can follow this link: https://github.com/PierreRambaud/phppsinfo 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Best regards, Khouloud

**Comment by Prestashopnewbie** [comment]
Ok, I did follow all the intructions above, but unfortionally the shop is still not found. 
The shop works again & everything is back the same as my first post. 
Only the php version is now as recommend 7.1 instead of 7.2... 

So exports like google shopping & mailchimp are still not working

**Comment by khouloudbelguith** [comment]
Hi @Prestashopnewbie,

The MailChimp module is not provided by PrestaShop, you need to contact the module developer: https://addons.prestashop.com/en/contact-us?id_product=26957.
The same thing with the google shopping module, it is provided by Business Tech, you can contact them via this link: https://addons.prestashop.com/en/contact-us?id_product=1768
Since it is fixed, I close the issue, feel free to open a new one when needed.

Best regards, Khouloud
