### ISSUE TITLE
Search isn't working in catalog > product page 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10345]
**Describe the bug**
Search isn't working in catalog > product page 

**To Reproduce**

1. Go to Catalog > Products
2. Click on Filter by categories and select a category
3. Refresh the page => #10257
4. Click on the **Reorder** button
5. Search with all field (name, category, status, price, ..) => doesn't work => The page is refreshed but you still see all products

**Screenshots**
https://drive.google.com/file/d/192CE4LInDEJrN_9FqWWiy6izxl7kR1H0/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by matks** [comment]
This issue looks like a summary of issues https://github.com/PrestaShop/PrestaShop/issues/10168 and https://github.com/PrestaShop/PrestaShop/issues/10257 that are fixed by https://github.com/PrestaShop/PrestaShop/pull/10365

**Comment by matks** [comment]
Hello @khouloudbelguith I am sorry with the latest version of `develop` I fail to reproduce the issue.

Here is what I do:
1) go to Catalog Products page, filter by "Papeterie"
![capture d ecran 2018-09-11 a 10 45 54](https://user-images.githubusercontent.com/3830050/45348881-22f2a900-b5b0-11e8-9449-884a144f22cb.png)
2) I see the 3 "Papeterie" products: looks good
![capture d ecran 2018-09-11 a 10 46 07](https://user-images.githubusercontent.com/3830050/45348897-2f770180-b5b0-11e8-9ec1-ec3fe0f987a8.png)
3) I search for string "10" in "reference" field, I get the matching product
![capture d ecran 2018-09-11 a 10 46 17](https://user-images.githubusercontent.com/3830050/45348927-3ef64a80-b5b0-11e8-94bd-3d39aa9e2647.png)
4) I search for string "Renard" in "name" field, I get the matching product
![capture d ecran 2018-09-11 a 10 46 28](https://user-images.githubusercontent.com/3830050/45348950-4f0e2a00-b5b0-11e8-9fd6-fe65d1f7a45f.png)
5) I search for ID minimum higher or equal to 17, I get products with IDs 17 and 18 and product ID 16 is excluded: looks right
![capture d ecran 2018-09-11 a 10 49 25](https://user-images.githubusercontent.com/3830050/45349008-736a0680-b5b0-11e8-8312-59165bac901e.png)

**Comment by khouloudbelguith** [comment]
Hi @matks,

Thanks for your feedback.
Yes, now I cannot reproduce the issue with the develop branch.

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with PS 1.7.5.0-beta1build.
In fact, you need to click on the Reorder button before the Search.
Thanks!

**Comment by clemkake** [comment]
Hello Team, 

were you guys able to fix this issue?

it's been more than a year and people are still facing the same problem:

I was able to reproduce the error and I think those who were able to didnt really look at the product 

category, the problem seem to be coming from there. 

Let's say you have 10 product in a category A and 5 of them have their default category set to B, 

when you try reordering the product in this case, the bug comes out. 

CAN ANYONE PLEASE TRY SOMETHING?

**Comment by khouloudbelguith** [comment]
Hi @clemkake,

Please follow: #14616.
Thanks!
