### ISSUE TITLE
You may be not allowed to download this module

### ISSUE THREAD

**Issue by Prestapro** [PrestaShop/PrestaShop#10387]
**Describe the bug**
Error!
Exception thrown by module autoupgrade on install. Error sent by Addons. You may be not allowed to download this module.

**To Reproduce**
1. Go to Back Office -> Module selection -> Selection
2. Click on install 1 click upgrade
3. See error

**Screenshots**
Any modules do not upload 1 click upgrade or theme customization:
http://prntscr.com/ktbyyt

**Additionnal information**
PrestaShop version: 1.7.3.4
PHP version: 7.1.12

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Could you please try to download the 1-click upgrade from this deposit & install it: https://github.com/PrestaShop/autoupgrade/releases/tag/v4.2.0
Thanks to check and feedback.

Best regards, Khouloud

**Comment by Prestapro** [comment]
Hello,

If you install the 1-click upgrade module separately, this works. But this is not the best way to solve the problem. Perhaps PrestaShop should make the background update possible, for critical bugs, at least as an option, it could remove a lot of questions and make using PrestaShop easier.

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Installing the 1-click upgrade from the BO ( I did not manage to reproduce the issue with PS1.7.4.2/ PS1.7.3.4 => OK )
https://drive.google.com/file/d/1lP9Ekvcq1ZqNFQhSxBpJRK68TexI-TVN/view
But the theme customization cannot be installed. (1.7.4.2 => NOK, 1.7.3.4 => NOK)
![image](https://user-images.githubusercontent.com/16067358/45478034-4bf77300-b743-11e8-81fc-39c3e1549920.png)
@colinegin what do you think about this issue?

Best regards, Khouloud

**Comment by dheerajwebkul** [comment]
I am also facing this issue on V1.7.4.2, not able to install the 1-click upgrade module issue
See screenshot, even after login
![install_error](https://user-images.githubusercontent.com/19220745/48301210-27840100-e510-11e8-8df5-d1842db48037.png)

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by marionf** [comment]
I can install 1click upgrade & theme custo with success on 1.7.3.4 & 1.7.4.4

It must be related to the unavailability of the API, maybe we can add a check of the API answer in BO if we have a 200 or 400/500 like proposed by @matks

**Comment by thierry-laval** [comment]
I am also facing this issue on V1.7.5.1, not able to install the 1-click upgrade module issue

**Comment by davenir** [comment]
Same issue here on V1.7.5.0
I've tried clearing the cache to no avail.

**Comment by smarmie** [comment]
Somehow it seem I cannot +1 the OP, so same issue for me.

**Comment by lutek** [comment]
on module update
```
[2019-07-12 14:31:40] php.INFO: User Deprecated: The "logger" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"logger\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /var/www/site/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []
[2019-07-12 14:31:40] app.ERROR: Wyjątek wyrzucany przez moduł ps_facetedsearch podczas upgrade. Error sent by Addons. You may be not allowed to download this module. [] []
```
module: ps_facetedsearch (v3.0.5 -> v3.1.0)
prestashop: 1.7.5.2

**Comment by johanlantz** [comment]
This happens to me as well on a clean install of 1.7.6.0 trying to install the productcomments module.

**Comment by colinegin** [comment]
Hello @johanlantz,

Thanks for your feedback. Could you give us more details about your issue ? What is the error message you get when trying to install this module ?

**Comment by dreamtheme** [comment]
I'm getting the same error on 1.7.6.0 clean install, If I'm not log in in addons, i get "you may need to be logged in", when i log in i get "You may be not allowed to download this module."

**Comment by chrisrabkin** [comment]
Getting this same error 
Error!
Exception thrown by module ps_reminder on install. Error sent by Addons. You may be not allowed to download this module in 1.7.6.0 - fresh install and logged into addons.

**Comment by kpodemski** [comment]
Same error reported on 1.7.6.0 while installing `productcomments` v4.0, this has to be some global issue after all

**Comment by JavierEB** [comment]
this error is also happening to me with version 1.7.6 ..... it may be a punctual problem of "Addons" because yesterday it worked perfectly and the modules were updated well .. I do not believe

**Comment by gahinton** [comment]
I am having the same issue with 1.7.6.0 when trying to add the RSS product feed module. I get the message "Error!
Exception thrown by module ps_feeder on install. Error sent by Addons. You may need to be logged."

I have downloaded and installed modules over the weekend without issue.

**Comment by JavierEB** [comment]
Error!
Exception issued by the statscatalog module in upgrade. Warning: include_once (/ httpdocs / classes /../ tools / pear / PEAR.php): failed to open stream: No such file or directory

e also tested with version 1.7.5.2 with which I think it is a general problem with the connection of "Addons Prestashop"

> 
> 
> I am having the same issue with 1.7.6.0 when trying to add the RSS product feed module. I get the message "Error!
> Exception thrown by module ps_feeder on install. Error sent by Addons. You may need to be logged."
> 
> I have downloaded and installed modules over the weekend without issue.

**Comment by colinegin** [comment]
There was an issue with some of our modules, we fixed it. Do you still have issues on your side ?

**Comment by lutek** [comment]
My problem was resolved. prestashop: 1.7.5.2
I noticed that the version of updated module was changed 
module: ps_facetedsearch (v3.0.5 -> v3.0.6)

**Comment by JavierEB** [comment]
if it seems that they have already solved the problem. I use the 1.7.6.0 and now everything ok. I can update all modulors without error. Thank you

**Comment by colinegin** [comment]
Thanks for your feedbacks ! As it seems the issue is fixed I will close it.
Do not hesitate to re-open it with a comment if your issue remains.

Have a nice day !

**Comment by BigAndini** [comment]
Hello, I'm still not able to upgrade the prestablog module with this error. We're using prestashop 1.7.6.0. Is there a real solution for this problem?

**Comment by khouloudbelguith** [comment]
Hi @inbaz,

Your issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/11450?

Thanks!
