### ISSUE TITLE
Javascript error when trying to edit embedded video (TinyMCE)

### ISSUE THREAD

**Issue by benwallis** [PrestaShop/PrestaShop#10737]
**Describe the bug**
After embedding a video in a product description, clicking on the object in the textarea causes a Javascript error to be reported in console, so the embed can not be edited.

`Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.`

**To Reproduce**
1. Go to 'Admin > Shop Parameters > General' and make sure that "Allow iframes on HTML fields" is set to "Yes"
2. Make sure that browser developer tools are enabled (console).
3. Go to 'Admin > Catalog' and add/edit a product
4. Edit the "Description". Click "Insert/Edit video" button in the rich text controls toolbar. Change to the "Embed" tab. Paste in an iframe embed HTML from a YouTube video (under a video on YouTube click "Share" then "Embed" to see the iframe HTML). Click "OK".
5. Click on the embedded grey object rectangle within the textarea.
6. See Javascript error in browser development tools error console.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.12

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

I did not manage to reproduce the issue with PS: 1.7.4.2.
I attached a video record.
https://drive.google.com/file/d/15czDbGJU-gzXiTu3XHjCd79cG2iR8WKD/view
Thanks to check & feedback.

Best regards, Khouloud

**Comment by benwallis** [comment]
Ah, it seems to only happen in Chrome browser.

I believe the issue is fixed by TinyMCE v4.5.6

**Comment by khouloudbelguith** [comment]
HI @benwallis,

Have you the same issue with this ticket: #9651?

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by simulbeni** [comment]
Hi,

This issue is still there. Once you add a image and click again on that image it gives error.

Thanks

![image](https://user-images.githubusercontent.com/437314/70759267-d924df80-1d6b-11ea-9853-998d45256738.png)

**Comment by khouloudbelguith** [comment]
Hi @benwallis,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!

**Comment by benwallis** [comment]
I'm not @beniwal ...

Anyway, as I mentioned above it's a known issue in TinyMCE and Chrome.

Prestashop needs to use an updated version of TinyMCE - this specific issue was fixed in TinyMCE 4.5.6 https://www.tiny.cloud/docs-4x/changelog/#version456-march302017

Latest version of TinyMCE is 5.1

See here: https://github.com/tinymce/tinymce/issues/3611#issuecomment-298427206
TinyMCE commit fixing the issue: https://github.com/tinymce/tinymce/commit/518a3bff9a5b5922e647db7b0b2d000d4d4c752f

Prestashop is currently using modified TinyMCE 4.0.16 released January 31 2014...
https://github.com/PrestaShop/PrestaShop/blob/develop/js/tiny_mce/tinymce.min.js

**Comment by khouloudbelguith** [comment]
@benwallis, @beniwal,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16583 to fix the issue.
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/11011
