### ISSUE TITLE
Voucher display in cart doesn't check group's price display method

### ISSUE THREAD

**Issue by jgtrescazes** [PrestaShop/PrestaShop#10841]
In a B2B websitewith all groups configured to show price tax excluded, price display is OK everywhere except in cart voucher, when discount is an amount.
In this case voucher amount is displayed tax included.
In code the problem is in src/Adapter/Cart/CartPresenter.php file in method getTemplateVarVouchers
The code that compute the displayed value doesn't check any price display settings.

```
// Voucher reduction depending of the cart tax rule
// if $cartHasTax & voucher is tax excluded, set amount voucher to tax included
if ($cartHasTax && $cartVoucher['reduction_tax'] == '0') {
     $cartVoucher['reduction_amount'] = $cartVoucher['reduction_amount'] * (1 + $cartHasTax / 100);
}
```
In my case I fixed this issue by changing this : 
```
-            if ($cartHasTax && $cartVoucher['reduction_tax'] == '0') {
+            if ($cartHasTax && $cartVoucher['reduction_tax'] == '0' && PS_TAX_INC === \Group::getCurrent()->price_display_method) {
```
**How to reproduce:**
I'm using 1.7.4.2 but code is the same in 1.7.4.3
- In FRONT: Create a user 
- In BO: Create a group with price display tax ecluded and add it to the user
- In BO: Create a voucher with an amount tax excluded
- In front: add products and voucher on the cart
- Expected behavior: In cart page, shown voucher amount is tax excluded
- Observed behavior: In cart page, shown voucher amount is tax included

**Comment by khouloudbelguith** [comment]
Hi @jgtrescazes,

Have you the same issue with this ticket: #9856?
We have a lot of issues related to the prices.
Thanks to take a look at this link: Prices - Lot 2 #9700
Thanks to check & feedback.

**Comment by jgtrescazes** [comment]
Hi @khouloudbelguith 
I just had a look at all those tickets and none of them is exactly the same as this one.
This is not a calculation problem but a display problem.
In my case prices are right as we dont use taxes anymwhere but the shown discount amount is wrong : it is displayed tax included but it should not as customer group is set to show tax excluded.
So if customer make the calculation from amounts that are displayed, result doesn't match the final amount that is displayed (the real amount tax exculded)

**Comment by khouloudbelguith** [comment]
Hi @jgtrescazes,

Yes, I said before, it is the same issue: #9856.
You can find in this description: https://github.com/PrestaShop/PrestaShop/issues/9856#issue-353105910 => [The problem occurs for countries outside the EU: In the cart and in the product details page, I get displayed the price tax Excl. with the reduction **tax incl**. ]
![image](https://user-images.githubusercontent.com/16067358/46460865-88a41080-c7bd-11e8-8a7f-65466616c439.png)
![image](https://user-images.githubusercontent.com/16067358/46460887-95286900-c7bd-11e8-811c-0c19093753de.png)
We are aware of this issue, it is added to our bug roadmap.
Please follow this ticket: #9856
Your ticket is a duplicate of #9856
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9856

**Comment by jgtrescazes** [comment]
@khouloudbelguith 
I dont think it is the same problem.
On your sceenshot (and in #9856) it concerns product specific price as I understand. 
In my case it concerns voucher (cart rule) amount only there are no country or tax calculation issue.
In the capture bellow problem is only on cart summary block in right sidebar.
My voucher amount is 200 € tax excluded and it's shown tax included (240) but all other calculated amounts in the page are OK:
50x49.9+2x39.80 = 2534.80 € Tax excl.
2534.80 - **200** = 2334.80 € Tax excl.

![wrong-voucher-amount](https://user-images.githubusercontent.com/5382876/46463080-601f1500-c7c3-11e8-8c1b-366ec1b7ab84.png)

I fixed it by my side for now , the problem is just that carPresenter class apply taxes before display without regarding price method settings, so I dont think that fixing 9856, will solve my problem but I will follow it and test again once it is resolved.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @jgtrescazes, thanks for your feedback.
I edit the #9856 to add the "discounts/ voucher" issue.
Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by Wykett** [comment]
Hi @khouloudbelguith, I know this item is pretty long time ago but since it's still an issue for me, with Prestasho v1.7.5.2, do you have any news?
I tried what @jgtrescazes did, but not working for me, even if I did that in src/Adapter/Presenter/Cart/CartPresenter.php
and not in 
src/Adapter/Cart/CartPresenter.php as this one is empty

Thank you, stucked with this problem since 1 week, nothing I see is working

**Comment by khouloudbelguith** [comment]
@jgtrescazes, this issue is fixed in the PS1.7.6.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/13684 to fix the issue.

Thanks!
