### ISSUE TITLE
1.7.4.3 Error with shopping cart 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#11065]
Prestashop 1.7.4.3.
PHP 7.2

1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in Cart.php line 61
at Cart->getPackageShippingCost(279, true, object(Country), null, 9)in Carrier.php line 748
at CarrierCore::getCarriersForOrder(9, array('3'), object(Cart), array())in Carrier.php line 1540
at CarrierCore::getAvailableCarrierList(object(Product), 0, '37135', 1, object(Cart))in Cart.php line 2321
at CartCore->getPackageList(false)in Cart.php line 2532
at CartCore->getDeliveryOptionList(null)in Cart.php line 3081
at CartCore->getDeliveryOption(null, false, false)in Cart.php line 3150
at CartCore->getTotalShippingCost(null, true)in Fees.php line 82
at Fees->processCalculation(object(Cart), object(CartRowCollection), '2', null)in Calculator.php line 271
at Calculator->calculateFees('2')in Calculator.php line 124
at Calculator->processCalculation('2')in Cart.php line 1901
at CartCore->getOrderTotal(false)in CartPresenter.php line 286
at CartPresenter->present(object(Cart), true)in CartController.php line 102
at CartControllerCore->initContent()in Controller.php line 255
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

![2018-10-18_16h27_31](https://user-images.githubusercontent.com/11147327/47161933-49181100-d2f3-11e8-92f1-536e5246907c.png)

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Could you please add steps to reproduce the issue in a new comment.
Thanks!

**Comment by Peter4661** [comment]
Customer complaint he did not recieve order confirmation.

We tried to reproduce it by placing order ourselves.  

In last payment step, selecting payment method "bank transfer", 500 error when confirming order.

With debug, on putting product in shopping cart, did get result as shown above.

Order has been processed in backoffice. No order confirmation revieved.

**Comment by Peter4661** [comment]
Issue solved after installing  php-intl extension!

**Comment by Peter4661** [comment]
Backoffice alos now sends order messages correct!

**Comment by khouloudbelguith** [comment]
Hi @Peter4661,

Thanks for your feedback.
Since it is fixed.
I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by matteolavaggi** [comment]
PHP 7.2


ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in Cart.php line 61
at Cart->getPackageShippingCost(62, true, object(Country), null, 9)in Carrier.php line 758


Still this bug on PS 1.7.6.0

**Comment by khouloudbelguith** [comment]
@matteolavaggi, `php-intl` extension is installed on your server?

Thanks!

**Comment by matteolavaggi** [comment]
Yes, i've found the problem, is related to the count() function modification on php7.2 that now retunr an e warning. 

THe problem is related to this module , developer has not yet fixed it (crazy) 


Free Delivery Pro


BTW because prestashop is full of third parts module , why there isn't a check against php compatibility of them? OR better there is no way to implement a better handling of the error send back from count() function in dev mode? thanks

For now i've fix the dev capability changing the function to @count , and ask developer to do therir job.

 elseif (@count($product_list)) {

**Comment by khouloudbelguith** [comment]
@matteolavaggi, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by matks** [comment]
> BTW because prestashop is full of third parts module , why there isn't a check against php compatibility of them? OR better there is no way to implement a better handling of the error send back from count() function in dev mode? thanks

Unfortunately there are no reliable ways to be able to say "this module is php7.2 compatible". There are lot of tools that can find php7.2 errors in a php code, but no tool can confirm there is absolutely zero issues in it. This is the responsibility of the module developer to handle different php versions, or to warn users what versions are not compatible.

BTW this module is really late 😄 [php 7.1 will be End Of Life in 2020](https://www.php.net/supported-versions.php) so he better hurry to be php7.2 compliant and php7.3 compliant
