### ISSUE TITLE
Translation not display if we add new line in string Module class l() function

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#11573]
**Describe the bug**
If we add a new line to the l() function like
$this->l(
'This is a test translation'
);
a function can have arguments with a single line with the PSR-2 standard.

Then,
It will not display in Module back-office translation page, see screenshot.

**Why we need a new line?**
Because if we want to fix 120 line PSR-2 issues sometimes it helps.

**Screenshots**
![download 13](https://user-images.githubusercontent.com/19220745/49281850-a935d180-f4b3-11e8-960e-026ece58d910.png)

**Fix line Code**
This is because of this regex which excluding \n newline string,
https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminTranslationsController.php#L1268

**Additionnal information**
PrestaShop version: V1.6.x.x, V1.7.x.x and also in V1.7.5.0 beta
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

This issue should be fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/11345.
It is fixed in the next stable version 1.7.5.0.
Thanks to check & feedback.
For more details about the translation system in Prestashop, you can follow this [link](http://build.prestashop.com/news/new-translation-system-prestashop-17)
Thanks!

**Comment by dheerajwebkul** [comment]
@khouloudbelguith thanks,
But are you sure this fix for the third party module translations? because PrestaShop module translation and third-party module translation have a different way to translate.

**Comment by khouloudbelguith** [comment]
@dheerajwebkul, public [PrestaShop 1.7.x nightly builds ](https://console.cloud.google.com/storage/browser/prestashop-core-nightly)are available! This way, it should be easier for anyone who wants to contribute to the project to work with a recent build. Also, it means that merged pull requests will be in a build the next day for testing.
So, you can check if this issue occurs with the last prestashop-core-nightly.
THanks!

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Any news about your issue?
The last version PS1.7.5.0 is released, did you check your issue with PS1.7.5.0?
Thanks!

**Comment by dheerajwebkul** [comment]
Hello @khouloudbelguith  

A very Happy New Year...

Yes, I checked this on PrestaShop V1.7.5.0. this issue is still in this version.
You can check this normally as I explained.

Thanks,

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Happy New Year, wish you all the best.
I did not manage to reproduce the issue with PS1.7.5.0, I tried with this module 
[translationbug.zip](https://github.com/PrestaShop/PrestaShop/files/2732368/translationbug.zip)
It is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/10735
Thanks to check & feedback.

**Comment by dheerajwebkul** [comment]
Hello @khouloudbelguith 

Your translatiobug module does not have condition to produce this issue.
Please upload this

[translationbug.zip](https://github.com/PrestaShop/PrestaShop/files/2732422/translationbug.zip)


module. where I have added $this->displayName translatable text with a new line and 'bla bla bla' with a new line. Now you can not see these text in the International->translation page while translating this module.

Thanks,

**Comment by dheerajwebkul** [comment]
@khouloudbelguith 

PR: #10735 is totally different with this issue.

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for this clarifications.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
When we have `$this->l(' ')` translatable text **with a new line** we will can not see these text in the International->translation page.
We will see how to fix it.
Thanks!

**Comment by eternoendless** [comment]
Hi @dheerajwebkul 

This can be considered fixed as of 1.7.6.0 thanks to #13504, but keep in mind that you will have to update your module to opt-in to the new translator (read the Pull Request description)

**Comment by dheerajwebkul** [comment]
@eternoendless thanks, very glad to see new translation system for the third-party module. 
I just tested with this module

[translationbug.zip](https://github.com/PrestaShop/PrestaShop/files/3239710/translationbug.zip)

I can successfully translate with new translation system, but still the translated string not display in FO or BO. Is anything I am missing or it's still to be fixed.

Please check my screenshots in order,
![1-BO-Configuration-Page-Translated](https://user-images.githubusercontent.com/19220745/58681492-3b972f00-838a-11e9-9f6f-ea527dde3fe5.png)
![2-FO-displayhome-tpl-page-translated](https://user-images.githubusercontent.com/19220745/58681494-3b972f00-838a-11e9-8924-8717016fe626.png)
![3-BO-Configuration-Page-Not-translating](https://user-images.githubusercontent.com/19220745/58681495-3c2fc580-838a-11e9-9d3c-935fb9d83dec.png)
![4-FO-displayhome-hook-content-not-translating](https://user-images.githubusercontent.com/19220745/58681496-3c2fc580-838a-11e9-9b90-fda413c19c86.png)
![5-In-Db-All-saved-success](https://user-images.githubusercontent.com/19220745/58681497-3c2fc580-838a-11e9-8e21-8bc07598d01e.png)

Thanks,

**Comment by khouloudbelguith** [comment]
Hi @dheerajwebkul,

Thanks for your feedback.
Yes, I have the same issue with PS1.7.6.0beta1 & the module provided.
In the BO => Translations page => all the expression are well displayed => new translations are successfully saved => but in the module configuration page BO => this translation is not displayed, also in the FO.
https://drive.google.com/file/d/1kgL0S8SxqRpOeCxgK_2zPud6l91V2bKE/view
PS: I tried with PS1.7.5.2 => when I try to translate the module => there is no expression displayed.

ping @eternoendless what do you think?

Thanks!

**Comment by unlocomqx** [comment]
I tested on `1.7.6.0` and the multiline translation code is not yet handled properly
Example
```
$this->confirmUninstall = $this->l(
    'All data associated with the module will be lost! Are you sure you want to proceed ?'
);
```
or
```
$this->confirmUninstall = $this->l(
    'All data associated with the module will be lost! Are you sure you want to proceed ?',
   'source_file'
);
```

https://github.com/PrestaShop/PrestaShop/pull/12903 provides a fix for this case without changing the module code
