### ISSUE TITLE
SEO - meta description Uncaught Error: Syntax error, unrecognized main.bundle.js:275 

### ISSUE THREAD

**Issue by futurehousestore** [PrestaShop/PrestaShop#11911]
**Describe the bug**
There's a problem with accessing modules configuration in modules tab in BO product page. When you click to configure any of the installed modules (in my case e.g. AN Product Extra Tabs Premium) the product is being saved without accessing product module configuration. 

**To Reproduce**
1. Fill in meta description in product SEO tab in Presta 1.7.4.4
2. Upgrade to 1.7.5.0
3. Access any of the products with fulfilled SEO fields (meta description)
4. Go to tab "modules" and click on "configure"

**Screenshots**
<img width="929" alt="screenshot 2018-12-23 at 03 03 56" src="https://user-images.githubusercontent.com/28427270/50380448-74a2d900-065f-11e9-89c0-881f11b2ccb3.png">
<img width="1463" alt="screenshot 2018-12-23 at 03 07 23" src="https://user-images.githubusercontent.com/28427270/50380473-2215ec80-0660-11e9-8f6a-0464beb0b615.png">
<img width="1423" alt="screenshot 2018-12-23 at 03 11 25" src="https://user-images.githubusercontent.com/28427270/50380486-92247280-0660-11e9-9fd2-cf0f0b413726.png">

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0.33

**Fix**
Delete meta description in SEO tab, save, refresh.

**Comment by khouloudbelguith** [comment]
Hi @futurehousestore,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 after upgrade from 1.7.4.4 to 1.7.5.0.
 
If before the upgrade, we have a product SEO complete, after the upgrade we have two issues in this product.

1. The SEO preview on this product page is not working
![image](https://user-images.githubusercontent.com/16067358/50396823-9a69d400-076c-11e9-8c49-4608fd426a5a.png)
 2. In the Tab module, if we click on configure => nothing happens
![image](https://user-images.githubusercontent.com/16067358/50396843-c5542800-076c-11e9-844f-f335fcbe1147.png)

These issues happen only when we have a product SEO complete.
![image](https://user-images.githubusercontent.com/16067358/50396884-03e9e280-076d-11e9-81cd-139afd1fe3e5.png)

We will see how to fix it.
Here's the log file after the upgrade.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/2707040/log.txt)

Ping @Quetzacoalt91 what do you think?
Thanks!

**Comment by mrabsinthe** [comment]
Also tested on vanilla 1.7.5. - if you paste text into "Meta description", it is not updated in preview even if you save and refresh. It only works when you start typing into the description field.

**Comment by Quetzacoalt91** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/11923

**Comment by Mreco83** [comment]
This fix does not work.
![clipboard01](https://user-images.githubusercontent.com/36883457/50483077-4f5cf480-09ea-11e9-9b57-3355ed2e0b92.jpg)

**Comment by marionf** [comment]
The fix works fine for me 

![capture d ecran_825](https://user-images.githubusercontent.com/13449658/50484769-9222ca80-09f2-11e9-8331-44ded3e51f7e.png)

![capture d ecran_826](https://user-images.githubusercontent.com/13449658/50484772-964ee800-09f2-11e9-92b3-d23058ba605f.png)

**Comment by Peterits** [comment]
Hi,
I have done some tests on version 1.7.5.1, there is a small bug on SEO product, if the field meta description is empty, the preview SEO shows code!

![image-seo](https://user-images.githubusercontent.com/44966543/51441163-fe7daa80-1cce-11e9-892c-ae0013e15a75.jpg)

**Comment by matks** [comment]
Hi @Peterits, do you think the bug you found is related to this issue ?

If not, could you please open another issue 😉 it makes issues easier to track (and fix 😛 )

**Comment by Peterits** [comment]
Yes you are right ! 😉

**Comment by Ybeske** [comment]
I discovered something (maybe) strange. Maybe it can be helpful to find a stable solution.

I installed a module (in my case Additional Product Attributes / Custom Product Fields) to be configured in the product "Module" tab. As described above, (sometimes) nothing happens (or opens) and I get immediately the typical green "Setup updated" message.

This problem only appears from the moment I write some "punctuation mark" like comma (,), point (.), exclamation mark (!), question mark (?).. in the meta description. Deleting all these characters makes the Module configuration work again.

**Comment by Ybeske** [comment]
To fix the problem (for all modules with the configuration in the product Module tab) in 1.7.5.0, you will have to do a find/replace in the adminXXX/themes/new-theme/public/main.bundle.js:

find
u(t.watchedDescription.val()).text()
replace by
t.watchedDescription.val().innerText

I could see the coming version 1.7.5.1 has this bug fixed already!

**Comment by khouloudbelguith** [comment]
@Ybeske, this ticket is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/11923, It is fixed in the next release 1.7.5.1.
Thanks!

**Comment by rafaviana** [comment]
Hi. I'm getting the same issue here, what do I need to do to solve it? I'm using 1.7.5.0
Thanks!

EDIT:
I followed @Ybeske instructions and it works. Is it ok to change PS files?

**Comment by matks** [comment]
@rafaviana It is OK to change PS files if you need the fix now. However keep in mind that this will create problems when you upgrade to 1.7.5.1 .

In order to avoid problems when you upgrade, keep the old file (with the bug in it) somewhere. Just before performing the upgrade, put back the old file 😉 . The idea is that in order for the upgrade to work correctly, you need the files unmodified.

**Comment by Ybeske** [comment]
<img width="1552" alt="schermafbeelding 2019-01-28 om 13 45 26" src="https://user-images.githubusercontent.com/43880279/51837563-0909f680-2304-11e9-8f97-972484e65197.png">
> @Ybeske, this ticket is fixed with this PR: #11923, It is fixed in the next release 1.7.5.1.
> Thanks!

Having 1.7.5.0, even with a fresh install to avoid the possible other conflicts with many modules.
From the moment I install a module (in my case: Product Fields manager) that creates a Module product tab, I also have issues with the specific price discount amount and dropdown menus ("% or €"  and "incl/excl. tax" settings)... It seems the issue is linked to this one...

Please see attachment.

Until now I only fixed manually the find replace of the spoken code above:

find
u(t.watchedDescription.val()).text()
replace by
t.watchedDescription.val().innerText

Any fix available?
Thanks in advance.

**Comment by khouloudbelguith** [comment]
Hi @Ybeske,

This is a different issue, can you open a new one with more information about your configuration.
Thanks!

**Comment by krupers** [comment]
Still having this issue with 1.7.6.5 version :(

**Comment by web-cooking-factory** [comment]
Hi everyone !

I had this error in 1.7.7.8 but found out why.

It could be useful for those who still having this error.

If you've imported the product descriptions with html tags, you get the error if the description is not encapsulated.

Simple example:
`lorem<br />ipsum` => error
`<p>lorem<br />ipsum</p>` => no error

So correct the descriptions in SQL with something like : 
`UPDATE ps_product_lang SET description = CONCAT('<p>',description,'</p>')`

Hope it helps, have a good day !

**Comment by MarcinWad** [comment]
Still not fixed in 8.1.2. To fix use this Query on database:

`UPDATE ps_product_lang SET description_short = CONCAT('<div>',description_short,'</div>') where description_short NOT LIKE '%<%'; `

It will only add DIV tags around description_short where there is no HTML tag.
