### ISSUE TITLE
Wrong quantities showing in BO for products with combinations

### ISSUE THREAD

**Issue by oskarna** [PrestaShop/PrestaShop#12814]
I noticed out that Prestashop is calculating wrong quantities in a certain case for products with quantities. After several tests I have found out how is it happening.

This issue is quite problematic for shops, that decided to control their quantities by prestashop's BO, instead of inventory managemenet software etc. I know this type of software COULD help, but this is Prestashop bug that should be fixed anyway.

How to achieve it?

# Simple description # 

1. Create combinations for product.
2. Customer makes order.
3. Delete combinations from product.
4. Create again combinations for product.
5. Order cancelled.
6. Overall quantity showed in BO products list is calculated wrong.

# Detailed description #

**1.)** We have product XYZ with size combinations: 
S, M, L, XL.
in database inside table pr_stock_available they have id_product_attribute: 
120, 121, 122, 123

**2.)** Customer is making order for 5 pieces of M size.

**3.)** Now we are deleting size M from product XYZ only. We are deleting it because we need to make it not appear, because for e.g. this size for product XYZ it is temporary not avaible for some reason.

**4.)** We are adding size M back to our product XYZ  (we decided to put it in offer again). 
If we take a look in database now - id_product_attribute for new "size M" have different ID than before. So we have again sizes: 
S, M, L, XL, 
but in database their IDs are: 
120, 4117, 122, 123.

**5.)** Our customer from pt. 2 is returning product (5 pieces). We are changing order status for cancelled - quantity is returned back to combination with ID 121. 

Now we can make another look in database.
Combination with ID 121 is recreated back and now for our product XYZ we have 5 combinations:
120, 121, 122, 123, 4117
Our old "size M" combination have id 121 with quantity that is equal 5.

Now in BO we can edit combinations of our product like this:
size S = quantity 0
size M = quantity 0
size L = quantity 0
size XL = quantity 0

In moment that we hit "save" button, prestashop is calculating overall quantity (that is show in BO products list):
0+0+0+0+5= 5 pieces
but in backoffice we can clearly see in combinations tab that they are set for 0. 

We can set product for "simple product" and set quantity to "0". Unfortunately after we generate combinations - after we hit "save" button - quantity is calculated wrong way again.

# Half-solutions? #

Half-solutions that we have tried are listed below. But in cases A and B it is hard to precisely determine when we have to fix our product. It may be a while before we find it out.

A.) You can manually change quantity of invisible combination in database.
This soultion is not acceptable for shop that have dozens of orders per day.

B.) We could create custom "cancelled" status for orders, that is not returning quantites back. Sadly it is not good solution for shop with huge amount of orders. 

C.) We could (in front) hide combinations that have quantity 0 and never delete them in BO. It will not work for shops that are using option for products on request:
Availability preferences -> Behavior when out of stock -> Allow orders 

# info #

PrestaShop version: tested at 1.7.5, 1.7.4.4, 1.7.4.2, 1.7.3.1
PHP version: 7.0.32, 7.2.11

**Comment by khouloudbelguith** [comment]
Hi @oskarna,

Thanks for your report.
Yes, I have the same behavior after following your steps.
After canceling the order, in the Product list page, we have a different quantity
![image](https://user-images.githubusercontent.com/16067358/53943568-a7386b80-40bd-11e9-823f-cff4e7adee55.png)
![image](https://user-images.githubusercontent.com/16067358/53943614-bc14ff00-40bd-11e9-9aa5-a7f5b9111867.png)
Which is normal behavior.
I think the solution is the worst solution you are making because combinations are incrementally created.
So when you create a new combination, a new id will be created.

About this solution:

> We could (in front) hide combinations that have quantity 0 and never delete them in BO

I think, it is the best solution to ovoid your problem.

> It will not work for shops

Yes, you are right, we are aware of this issue, it is added to our debug roadmap.
It is reported in this ticket: #9667 
Thanks to check & feedback.

**Comment by ghost** [comment]
I came here with a similar problem and I see that something is wrong with the quantity of products (stocks) in Prestashop when quantities are decreased manualy instead of automatic (via orders).

I have weird problem with store that was updated successfuly from 1.7.3.3 to 1.7.4.2 and 1.7.5.1.
Upgrades was always flawless (database is consistent) but some day customer says that disabled products (sold one) get back to live with available quantities... WTF...

Also i found that product quantity in BO product list show 2 (1 quantity per two sizes) but Stocks are emptied...  HOW? It's very unpleasant issue ;/
![geox](https://user-images.githubusercontent.com/8243273/53956336-a57da080-40db-11e9-9d81-bec25303aa04.jpg)
Looks like somewhere quantities are added +1. Is there a way to get rid of it?

**Comment by ghost** [comment]
@oskarna try to not decrease quantities manualy but make an order from the front (like regular customer). One of my friend use Prestashop as PoS system. When something is sold in local store then his employee use his customer account to make an order.

**Comment by oskarna** [comment]
@PrestaShark 
As I described in my post - this value is in database, but it is not visible in backoffice.

Check table "pr_stock_available". Sort products by ID and You will see combination with quantity larger than zero. You can edit it and problem will be solved.

**Comment by khouloudbelguith** [comment]
@oskarna, can I close the issue? it is a duplicate of #9667?
Is it? it is the only solution that exists.
THanks!

**Comment by oskarna** [comment]
It is different situation, @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@oskarna,

I have the same behavior described by @oskarna.
After canceling the order, in the Product list page, we have a different quantity
![image](https://user-images.githubusercontent.com/16067358/54019203-e54f9100-418a-11e9-8a02-1486a5fb3ccf.png)
![image](https://user-images.githubusercontent.com/16067358/54019234-fbf5e800-418a-11e9-86d1-e952f8ff6160.png)

In fact when we delete the combination with `id_product_attribute = 201` 
In the table `ps_stock_available`  the column where `id_product_attribute = 201` is deleted.
But when we cancel the order, this column is recreated in the table `ps_stock_available`

Before the suppression of the combination
![image](https://user-images.githubusercontent.com/16067358/54019042-7a9e5580-418a-11e9-925a-074a7b0abb33.png)
After the suppression of the combination
![image](https://user-images.githubusercontent.com/16067358/54019090-96096080-418a-11e9-967f-ad00722e4060.png)

After canceling the order
![image](https://user-images.githubusercontent.com/16067358/54019106-a4f01300-418a-11e9-8fd1-a5cba7dd06f7.png)

@marionf, what do you think?
Thanks!

**Comment by neich78** [comment]
Have a similar problem. Products with 4 combinations and different stock in each one. Stock does not match quantity shown in Catalog summary. 
Please check product ID=3. Stock in combinations 103, but stock in summary = 335. 

![Captura de pantalla 2020-04-29 a las 11 26 54](https://user-images.githubusercontent.com/11721870/80581018-cd7d4100-8a0c-11ea-9fa6-0c2e537efe16.png)
![Captura de pantalla 2020-04-29 a las 11 30 07](https://user-images.githubusercontent.com/11721870/80581025-ceae6e00-8a0c-11ea-9641-ad28fe9a8e78.png)

Prestashop 1.7.6.4

**Comment by jonpontet** [comment]
This is "still" outstanding right ?

Be great to get this "minor" bug that has large ramifications for so many ...fixed ! 

I see a lot of chatter but very little movement :(

**Comment by masiorama** [comment]
Experiencing the same issue on 1.7.7.4.

**Comment by masiorama** [comment]
In my case the issue is related to the cancellation of 2 product combinations with still 2 and 3 stocks, which led to a total of 5 available even if the "published" combinations were 0 (non available). I fixed the numbers on database and it was sorted for my specific case, but I guess that some sort of check on the stock quantity should be taken in consideration when a combination erase has been triggered.

**Comment by ocio87** [comment]
Hello,

I present the same problem. Removing a combination does not remove the stock, nor does it remove the id_product_attribute.

https://drive.google.com/file/d/11RBnPRE92TnHw7Akqxyc-lk5jX6nKFZ0/view?usp=sharing

Php 7.4
Prestashop 1.7.8.2

**Comment by Mauro207** [comment]
I have the same problem on version 1.7.8.5. The quantities shown in the product list are incorrect.
![Screen1](https://user-images.githubusercontent.com/46824784/165471565-e196459b-b914-4d8c-8765-6ecf9194ef09.jpeg)

Where the total quantities between the combinations equals 1, I am shown 2 in the BO
![Screen2](https://user-images.githubusercontent.com/46824784/165471664-26d5bb8a-b998-4135-98b9-b761c68d7923.jpeg)

Repeated error in other products. Can I somehow fix it or am I waiting for a new update?

**Comment by webstartconsulting** [comment]
We are the same problem at version 1.7.8.7 Not fixed yet? Any update?

**Comment by sketchypl** [comment]
any update? bump topic, i've the same problem

**Comment by MatShir** [comment]
For this issue, why not to hide unavailable combination ? 🤔 
The feature is available on the Product Setting "Display unavailable attributes on the product sheet".

**Comment by kpodemski** [comment]
@MatShir also, probably to be validated on the new product list in 8.1

**Comment by MatShir** [comment]
Still present on the new product page. We have a workaround (we can hide the attribute out of stocks) for the FO until someone make a contribution on this issue

**Comment by KodeToad** [comment]
This issue is still present in PS 8.1.1.

My analysis suggests that the rows in ps_stock_available are not being removed for combinations when the parent product is not removed also.
My experience is that after creating new combinations and removing old combinations for a product without removing the product, the old rows in this table remain with the quantities they had when they were removed with BO. These are then incorrectly added to the total quantity on the summary list pages.
It could be that this table was relying on cascade delete which is not functioning in this case.
The delete function in classes/Combination.php returns false if the parent::delete function is false without removing the relevant lines.

I can find affected lines with this sql:
`select * from ps_stock_available psa WHERE psa.id_product_attribute <> 0 and NOT EXISTS (select pa.id_product_attribute from ps_product_attribute pa where psa.id_product = pa.id_product and pa.id_product_attribute = psa.id_product_attribute);`

I'd like to know if just removing the offending lines in ps_stock_available will be enough or are there other rows which need to be tidied up as well? It looks as if ps_stock_available records where id_product_attribute = 0 need to be updated too.

**Comment by dmarczewski** [comment]
Has anyone found a solution to this problem yet?

**Comment by seederp2p** [comment]
2024, prestashop 8.2... and this is still present...

**Comment by indysp80** [comment]
Anyone has a workaround ?

**Comment by PhenixInfo** [comment]
1 - Check ghost :

```
SELECT
    p.id_product,
    p.reference                           AS product_ref,
    sa_global.id_shop,
    sa_global.quantity                    AS stock_affiche,
    
    -- Somme des quantités des déclinaisons réelles
    SUM(CASE 
            WHEN pa.id_product_attribute IS NOT NULL 
            THEN sa_attr.quantity 
            ELSE 0 
        END)                              AS stock_calcule,
    
    -- Somme des quantités des déclinaisons fantômes
    SUM(CASE 
            WHEN pa.id_product_attribute IS NULL 
            THEN sa_attr.quantity 
            ELSE 0 
        END)                              AS stock_fantome,
    
    -- Écart entre ce qui est affiché et ce qui devrait être
    sa_global.quantity 
      - SUM(CASE 
                WHEN pa.id_product_attribute IS NOT NULL 
                THEN sa_attr.quantity 
                ELSE 0 
            END)                          AS diff_affiche_calcule

FROM ps_stock_available AS sa_attr
JOIN ps_product AS p
      ON p.id_product = sa_attr.id_product

-- Test si la déclinaison existe vraiment
LEFT JOIN ps_product_attribute AS pa
       ON pa.id_product_attribute = sa_attr.id_product_attribute
      AND pa.id_product = sa_attr.id_product

-- Ligne globale (id_product_attribute = 0)
JOIN ps_stock_available AS sa_global
      ON sa_global.id_product          = sa_attr.id_product
     AND sa_global.id_shop             = sa_attr.id_shop
     AND sa_global.id_shop_group       = sa_attr.id_shop_group
     AND sa_global.id_product_attribute = 0

WHERE sa_attr.id_product_attribute <> 0
  AND sa_attr.id_product <> 0

GROUP BY 
    p.id_product,
    p.reference,
    sa_global.id_shop,
    sa_global.quantity

HAVING 
    stock_fantome > 0         -- au moins une déclinaison fantôme
    OR diff_affiche_calcule <> 0;  -- ou écart entre affiché et calculé
```

2 - Fix stock (recalibration) :

```
UPDATE ps_stock_available AS sa_global
JOIN (
    SELECT 
        sa_attr.id_product,
        sa_attr.id_shop,
        sa_attr.id_shop_group,
        SUM(sa_attr.quantity)          AS stock_calcule,
        SUM(sa_attr.physical_quantity) AS stock_physique_calcule,
        SUM(sa_attr.reserved_quantity) AS stock_reserve_calcule
    FROM ps_stock_available AS sa_attr
    JOIN ps_product_attribute AS pa
          ON pa.id_product_attribute = sa_attr.id_product_attribute
         AND pa.id_product          = sa_attr.id_product
    WHERE sa_attr.id_product_attribute <> 0
      AND sa_attr.id_product <> 0
    GROUP BY sa_attr.id_product, sa_attr.id_shop, sa_attr.id_shop_group
) AS agg
  ON agg.id_product     = sa_global.id_product
 AND agg.id_shop        = sa_global.id_shop
 And agg.id_shop_group  = sa_global.id_shop_group
SET 
    sa_global.quantity          = agg.stock_calcule,
    sa_global.physical_quantity = agg.stock_physique_calcule,
    sa_global.reserved_quantity = agg.stock_reserve_calcule
WHERE sa_global.id_product_attribute = 0
  AND sa_global.id_product <> 0
  AND (
        sa_global.quantity          <> agg.stock_calcule
     OR sa_global.physical_quantity <> agg.stock_physique_calcule
     OR sa_global.reserved_quantity <> agg.stock_reserve_calcule
  );
```

**Comment by boo-code** [comment]
I could not reproduce the described mechanism on `9.1.x`, and the cleanup that was missing appears to be in place now. Posting what I ran so it can be re-tested rather than taken on trust.

`Combination::delete()` calls `StockAvailable::removeProductFromStockAvailable()` for the related shops, and the modern deletion path reaches the same method - `CombinationRepository::delete()` goes through `deleteObjectModelFromShops()`, which calls `$objectModel->delete()`. So both the product page and the legacy path clean up.

Measured, creating a combination with stock and deleting it:

```
stock rows for that combination after create: 1
stock rows after delete:                      0
orphan stock_available rows overall:          0
```

Adding the part of your scenario that my first attempt was missing - an order line referencing the combination, in a not-yet-shipped state - changes nothing, including after the stock refresh the back office runs:

```
rows right after delete:      0
rows after stock refresh:     0
orphans overall:              0
```

And the product level row stays consistent with the sum of its combinations across the whole sequence:

```
before add:   product_row=2400  sum_of_combinations=2400
after add:    product_row=2410  sum_of_combinations=2410
after delete: product_row=2400  sum_of_combinations=2400
```

One thing that would not be fixed by the cause being gone, and which may be what people still hitting this are seeing: a shop that accumulated orphan rows under 1.7 or 8.x still carries them after upgrading, and the total stays wrong until those rows are removed. That is data left behind rather than a live defect. Shops can check with:

```sql
SELECT sa.* FROM ps_stock_available sa
LEFT JOIN ps_product_attribute pa ON pa.id_product_attribute = sa.id_product_attribute
WHERE sa.id_product_attribute > 0 AND pa.id_product_attribute IS NULL;
```

If that returns rows on a 9.x shop that never ran an older version, then something still creates them and I would like the steps - I will take it. If it only returns rows on upgraded shops, the remaining question is whether the upgrade should clean them, which belongs in `PrestaShop/autoupgrade`.
