### ISSUE TITLE
Error Faceted Search Module

### ISSUE THREAD

**Issue by frankymartinES** [PrestaShop/PrestaShop#14281]
Hi, I have found other issue with new version of Faceted search module. When I active the faceted search module the default combination of products is not showed in product list.
I am working in a multistore PS 1.7.4.4

**To Reproduce**
1. Set a combination of a product with a discount price.
2. Set that combination as default (see screenshot 1).
3. Go to product list and see the product, the default combination is not showed (price is the clue to know the error, see screenshot 2).
4. Click in the product and see that not open the deault combination (see screenshot 3).

If I deactive the faceted search module everything is working fine.

PHP version: 7.0.33
PS version: 1.7.4.4
Multistore Shop

**Comment by khouloudbelguith** [comment]
Hi @frankymartinES,

We just released a new version of the module ps_facetedsearch.
It is v3.0.5, https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.0.5
Could you please try with this version and feedback. 

Thanks!

**Comment by frankymartinES** [comment]
Could I to update from backoffice? or Do I need to upload the zip? and After upload Do I need to change any file?

**Comment by khouloudbelguith** [comment]
@frankymartinES, could you please try with this zip folder.
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3305622/ps_facetedsearch.zip)

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith I have updated from backoffice and the error is still here :-(

**Comment by khouloudbelguith** [comment]
@frankymartinES, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 & ps_facetedsearch v3.0.5.
I attached a video record
https://drive.google.com/file/d/1QplgmBOCtFq4Mx-2lzt4yrmGsFyNJLGJ/view
Thanks to check & feedback.

**Comment by frankymartinES** [comment]
@khouloudbelguith I see the error hapen in all products added before the first update of the module. Maybe the error is in relation with data base or cache?

**Comment by khouloudbelguith** [comment]
@frankymartinES, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
You can also Click on "Rebuild entire price index", "Build attributes and features indexes" & "Clear cache" button in the ps_facetedsearch configuration module.
Thanks to check and feedback.

**Comment by frankymartinES** [comment]
@khouloudbelguith I have renamed the folders prod and dev into var/cache and "Rebuild entire price index", "Build attributes and features indexes" & "Clear cache" in one of the shops of my multistore but nothing change. Any idea?

**Comment by khouloudbelguith** [comment]
@frankymartinES, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by frankymartinES** [comment]
Hi, I have updated to last version v3.0.6 but the error continue. And I found another, en 2 shops of my multistore the module is not showed in the right column after activate. I have check that the module is set in that hook. Could i give you acces to my backoffice?

**Comment by frankymartinES** [comment]
@khouloudbelguith forgot about the second error!! It is solved. But the main problem is that the default combination is not showed in few products.

**Comment by khouloudbelguith** [comment]
@frankymartinES, in the BO => Shop Parameters => Product Settings => the option "Display unavailable product attributes on the product page" is enabled or disabled?

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith it is enabled because if I disable it the client can´t change the combination in product page. But I test it and after disable that option the error continue.

**Comment by khouloudbelguith** [comment]
@frankymartinES, I tried with PS1.7.5.2 again & the ps_facetedsearch module v3.0.6 => but it is OK.
The default combination is well displayed.
![image](https://user-images.githubusercontent.com/16067358/60656575-93bcc780-9e47-11e9-84e4-01d4e40f2056.png)
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith, in new products the module es working great, but in prodcuts before the first update the error exist. I am going to try to send you the error log details.

**Comment by frankymartinES** [comment]
@khouloudbelguith I can´t find any file;
PHP error log:
Apache: /var/log/apache/php_error.log
Nginx: /var/log/php-fpm/default/error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles

**Comment by khouloudbelguith** [comment]
@frankymartinES, If you don't have it, you should ask your hosting provider.
Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith, I have found the log reports. I have attached the file.
[error_log.zip](https://github.com/PrestaShop/PrestaShop/files/3362440/error_log.zip)

**Comment by khouloudbelguith** [comment]
@frankymartinES, you a lot of errors related to your cache
>[Fri Jul 05 12:58:56.245923 2019] [proxy_fcgi:error] [pid 24423] [client 66.249.76.120:41046] AH01071: Got error 'ts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 195\nPHP message: PHP Notice:  Undefined index: base_dir in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 199\nPHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 199\nPHP message: PHP Notice:  Undefined index: base_dir in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 203\nPHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 203\nPHP message: PHP Notice:  Undefined index: base_dir in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 207\nPHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/sps-sport.com/httpdocs/var/cache/prod/smarty/compile/layouts_layout_full_width_tpl/53/3f/be/533fbe986c31be55065d3e4e3c50e4af66ee45a1_2.file.footer.tpl.php on line 207\n'

This error is related to the ps_facetedsearch module but it is in the cache files.

Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```

Thanks!

**Comment by frankymartinES** [comment]
Hi, I rename the cache directory in var but nothing change :-(

**Comment by khouloudbelguith** [comment]
Hi @frankymartinES,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith Sorry but ti must be in relation with the module, no with my server configuration or customization because the error star after update the faceted module and if I disactive the module the error dissapear. So, It is problem with the faceted module for sure!!!

**Comment by khouloudbelguith** [comment]
@frankymartinES, I tried with a diferent versions of the module ps_facetedsearch but I did not manage to reproduce the issue.
The default combination is well displayed in the FO.

Thanks!

**Comment by frankymartinES** [comment]
Hi, I am going to show you 3 pages in the same domain, 2 without faceted module and 1 with the faceted module. In the 2 firsts no error and in the thirs one ERROR (look for MIZUNO WAVE LIGHTNING Z5 red and black):
https://sps-sport.com/busqueda?controller=search&s=lightning+z5
https://sps-sport.com/7_mizuno
https://sps-sport.com/351-balonmano?q=Marca-Mizuno

**Comment by khouloudbelguith** [comment]
Hi @frankymartinES,

I tried with the 3 shops => the red & black combinations are well displayed.
I attached a screen record
https://drive.google.com/file/d/1U2-muYimQB779zGtHXb4JyG4kkPu9spR/view
Thanks!

**Comment by frankymartinES** [comment]
I think I did not explain me very vell, sorry!! But the combination are not well displayed, in the producto Mizuno Wave lightning Z5 (red and black) the default combination is the size 42, but with the faceted module active the first combination showed is the 40.5. You can see it in your video, only in your firs test the default combination is showed with the discount because that page has not sidebar with facetes module. I hope you can understand me now, sorry again. Help me please

**Comment by khouloudbelguith** [comment]
@frankymartinES, In my case, I did not manage to reproduce the issue.
https://drive.google.com/file/d/1VVs4bLqqzO_cr-A6eiKO1rjwUrKyvCaA/view
But, in your shop: https://sps-sport.com/351-balonmano?q=Marca-Mizuno
The product MIZUNO WAVE LIGHTNING Z5 has a combination by default this one: https://sps-sport.com/zapatillas-unisex/4180-32121-mizuno-wave-lightning-z5.html
And not this one: https://sps-sport.com/zapatillas-unisex/4180-32121-mizuno-wave-lightning-z5.html

Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith you must see the product MIZUNO WAVE LIGHTNING Z5 (red/black ref: V1GA190062), because there are more products with that name but diferent colors. In product page you are changing the product, not color combination, it is a new module I have installed yesterday.

You have to focus in the product MIZUNO WAVE LIGHTNING Z5 (red/black ref: V1GA190062)
No error: https://sps-voleibol.com/busqueda?controller=search&s=lightning+z5
![captura1](https://user-images.githubusercontent.com/50448058/60886140-7b86e700-a251-11e9-8363-18e318a646cd.jpg)

Error: https://sps-voleibol.com/13-zapatillas-unisex?q=Marca-Mizuno
![captura2](https://user-images.githubusercontent.com/50448058/60886159-817cc800-a251-11e9-82c4-d58befbf4d5f.jpg)

**Comment by khouloudbelguith** [comment]
@frankymartinES, In your second shop, could you please provide me a screenshot from your Product page "MIZUNO WAVE LIGHTNING Z5" => Combination Tab.

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith , if I click in the first option I send you before (https://sps-voleibol.com/busqueda?controller=search&s=lightning+z5) the product page opened is the good one;
https://sps-voleibol.com/zapatillas-unisex/4182-32151-mizuno-wave-lightning-z5.html#/309-tallas-42
![captura3](https://user-images.githubusercontent.com/50448058/60899607-0c1df100-a26b-11e9-96ec-f31f13579f12.jpg)

But if I click in the second situation (https://sps-voleibol.com/13-zapatillas-unisex?q=Marca-Mizuno) the producd page opened has the error.
https://sps-voleibol.com/zapatillas-unisex/4182-32149-mizuno-wave-lightning-z5.html#/306-tallas-405
![captura4](https://user-images.githubusercontent.com/50448058/60899760-54d5aa00-a26b-11e9-9dd2-76a08d8d7303.jpg)

**Comment by frankymartinES** [comment]
@khouloudbelguith Could I try to reindex all the products in the "Search" section (
advanced parameters)?

**Comment by khouloudbelguith** [comment]
@frankymartinES, Do you need to Re-build the entire index in the Search page?
![image](https://user-images.githubusercontent.com/16067358/60901412-cf9bc680-a265-11e9-9d19-fad9aa89f9cf.png)

Thanks!

**Comment by frankymartinES** [comment]
Could be a solution? Now all my products are indexed but maby that action can be usefull. What do you think?

**Comment by khouloudbelguith** [comment]
@frankymartinES, you need to rebuild the entire index, clear cache & check the issue again.

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith I have rebuilted the entire index and clen cache but the error continue. You can see that the error must be in the faceted module because when I desactive the module the error disapear.
https://sps-uhlsport.com/13-zapatillas-unisex?page=2
![captura5](https://user-images.githubusercontent.com/50448058/60906528-9ff5ba00-a277-11e9-969a-5c405a60fb38.jpg)

**Comment by khouloudbelguith** [comment]
@frankymartinES, thanks for your feedback.
In my case it is OK => there is no issue.
Ping @PierreRambaud what do you think of this issue?
>Set a combination of a product with a discount price.
Set that combination as default
Go to the product list and see the product, the default combination is not showed (price is the clue to know the error)
Click on the product and see that not open the default combination.
If I disable the faceted search module everything is working fine.


Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith , sorry but in your video I can see the issue prefectly. Check it again please!!
In the first part of your video you can see that after click in the black product and open the product page, you change to red color and the combiantion opened is the 40.5 size and the default combination is the 42 size.
And also in the third part you can see in the product list that the red color shoe Mizuno Wave Lightning Z5 is showed without the discount because is not showing the default combination.

**Comment by khouloudbelguith** [comment]
@frankymartinES, I just created a product following your steps & it is OK.
https://drive.google.com/file/d/1zy2xDr6MK-wIWg3s8OH5VK69vGdn1JmV/view
In your Back office => Shop Parameters => Product Settings => "Quantity discounts based on" is setted to "Combinations?
![image](https://user-images.githubusercontent.com/16067358/60962520-5dc78980-a306-11e9-9750-69ab9c86124b.png)

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith I have setted to Cambinations the "Quantity discounts based on" option but the error still here. I think that is not the problem because before update the "faceted search module" the error did not exist. 
You did the test in PS 1.7.6, I have PS 1.7.4.4 and tha error appear after update the module, maby you are working in a new installation. 
I think the problem could be the database or cache after update the module.

**Comment by khouloudbelguith** [comment]
Hi @frankymartinES,

I tried with PS1.7.4.4 & the ps_fecetedsearch before & after the upgrade.
I attached a screen record
https://drive.google.com/file/d/1O5wMqBQaX0sY2t6jXWbCEnyyUCT0SEoq/view

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith so I have not solution for that problem. How I could to go back to old version of the faceted module?

**Comment by khouloudbelguith** [comment]
@frankymartinES, you can check in this link the releases of the ps_facetedsearch module https://github.com/PrestaShop/ps_facetedsearch/releases
Also, you need to run `composer install` inside it.

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith Could you explain how to do it please? Sorry for all your time waste in this issue. Thanks again

**Comment by khouloudbelguith** [comment]
@frankymartinES, you are welcome!
For example, you need to download the release v2.2.1.
1. You need to follow this link: https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.2.1
2. Click on the Source code (zip) link: https://github.com/PrestaShop/ps_facetedsearch/archive/v2.2.1.zip. =>  zip file will be downloaded.
3. Unzip this file.
4. Run the command  `composer install`  inside the folder
5. Compress the folder
6. Upload it from the Module catalog page

Thanks!

**Comment by frankymartinES** [comment]
@khouloudbelguith  Sorry, but I did not do it before, so Could you explain me how to do step 2?

**Comment by frankymartinES** [comment]
Sorry, I mean step 4

**Comment by khouloudbelguith** [comment]
@frankymartinES, Composer is a tool for dependency management in PHP. It allows you to declare the libraries your project depends on and it will manage (install/update) them for you.
Using console command, you need to run composer install
![image](https://user-images.githubusercontent.com/16067358/60986522-8ddb5080-a337-11e9-9a01-380daeb2a021.png)

Thanks!

**Comment by frankymartinES** [comment]
Hi @khouloudbelguith finally I have bak to old version of the module and everithing is working fine again. It means that the problem come from the update of the module. Thanks for your help and time!!!
