### ISSUE TITLE
Error in suppliers page after deleting a currency - Regression

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#15486]
I would like to refer to this issue (https://github.com/PrestaShop/PrestaShop/issues/14908). This issue appears to be resolved in my other shops, but not on morganic.mu. My guess is that the alterations that I made on the database to rectify the issue prior to 1.7.6.1 update may have corrupted the database (see issue 14908 which explains the solutions I tried). 

I am hoping that we can rectify the issue or at least avoid worst case scenario: fresh reinstall of prestashop.

Exception discovered when viewing suppliers: ![64470979-9d6eee00-d15c-11e9-8bb0-23b225d096d2](https://user-images.githubusercontent.com/26452178/64610143-a3283600-d3df-11e9-92e3-2d5b41547c41.png)

Exception discovered when creating a new currency:

[exception.pdf](https://github.com/PrestaShop/PrestaShop/files/3595397/exception.pdf)

![64470999-d9a24e80-d15c-11e9-963c-14d67529b1bd](https://user-images.githubusercontent.com/26452178/64610144-a3c0cc80-d3df-11e9-95c9-ffcd7e13a9ba.png)

Image of the database:

![64471155-72859980-d15e-11e9-9373-78599caa2b39](https://user-images.githubusercontent.com/26452178/64610615-ab34a580-d3e0-11e9-9e98-a51bd9286c07.png)
![64471156-787b7a80-d15e-11e9-8958-4f14a481ca48](https://user-images.githubusercontent.com/26452178/64610616-abcd3c00-d3e0-11e9-9137-e8d8c55f7ae9.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

About the second issue => it is OK.
I manage to reproduce the first issue about the suppliers with PS1.7.6.1.
To reproduce the issue:
1. Import new products from the BO => Advanced Parameters => Import page using the CSV file by default.
2. Go to the supplier page => Click on the view button => OK => fixed in the PS1.7.6.1.
3. Go to the BO => International => Change the currency by default  & delete your previous currency.
4. Go to the supplier page => Click on the view button => NOK => Regression
It is OK with PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/64615184-fa270e80-d3d1-11e9-9d9a-4a79294d6256.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/15376

**Comment by nrcjea001** [comment]
I am still facing issue in 1.7.6.2. I looked at #17056 but it doesn't look like its related.

To reproduce:

Import new products from the BO => Advanced Parameters => Import page using the CSV file by default.
Go to the supplier page => Click on the view button => OK
Go to the BO => International => Change the currency by default & delete your previous currency.
Go to the supplier page => Click on the view button => NOK
I

![Untitled](https://user-images.githubusercontent.com/26452178/72199587-6df82700-3457-11ea-8576-2c03e1258010.png)

**Comment by khouloudbelguith** [comment]
@nrcjea001, it is OK with PS1.7.6.2
I attached a screen record
https://drive.google.com/file/d/1FURBX8o7zH43xdyO3jdvm-JqvHH44KDl/view

Thanks!
