### ISSUE TITLE
By assigning a default supplier the product disappears from the index.

### ISSUE THREAD

**Issue by JuanjoSCu** [PrestaShop/PrestaShop#15640]
If a product is indexed and we assign a default supplier it disappears from the index, if we reconstruct the index and in the same product we make a preview it also disappears.

**To Reproduce**
Go to Shop Parameters -> Search -> Indexed -> see the number  (indexed product 5000/5000)
Go to Catalog -> Products -> enter an active product without assigned default supplier 
Go to Options -> Suppliers
Assign provider and set default provider 
Save
Go to Shop Parameters -> Search -> Indexed -> see the number  (indexed product 4999/5000)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.2

**Comment by khouloudbelguith** [comment]
Hi @JuanjoSCu,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
https://drive.google.com/file/d/1Cgp20IWXFDXev2lcuWyR49te-uXQInBE/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by idnovate** [comment]
Problem is that the product words are indexed, but the flag `indexed` from tables `ps_product` and `ps_product_shop` is overriden.

This is the sequence:
```
UPDATE ps_product a
				 INNER JOIN ps_product_shop product_shop
        ON (product_shop.id_product = a.id_product AND product_shop.id_shop = 1)
				SET a.indexed = '1', product_shop.indexed = '1' WHERE a.id_product IN (18)
```
```
#0 \classes\db\Db.php(571): DbCore->query('UPDATE ps_produ...')
#1 \classes\ObjectModel.php(1808): DbCore->execute('UPDATE ps_produ...')
#2 \classes\Search.php(811): ObjectModelCore::updateMultishopTable('Product', Array, 'a.id_product IN...')
#3 \classes\Search.php(787): SearchCore::setProductsAsIndexed(Array)
#4 \controllers\admin\AdminProductsController.php(1954): SearchCore::indexation(false, 18)
#5 \classes\controller\AdminController.php(1150): AdminProductsControllerCore->processUpdate()
#6 \classes\controller\AdminController.php(988): AdminControllerCore->processSave()
#7 \controllers\admin\AdminProductsController.php(1269): AdminControllerCore->postProcess()
#8 \src\PrestaShopBundle\Controller\Admin\ProductController.php(513): AdminProductsControllerCore->postCoreProcess()
#9 [internal function]: PrestaShopBundle\Controller\Admin\ProductController->formAction('18', Object(Symfony\Component\HttpFoundation\Request))
#10 \var\cache\dev\classes.php(4581): call_user_func_array(Array, Array)
#11 \var\cache\dev\classes.php(4536): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#12 \vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#13 \administrator\index.php(86): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#14 {main}
```

Value is correctly set to `1`, but then is executed this one:
```
UPDATE `ps_product` SET `id_product` = '18',`id_shop_default` = '1',`id_manufacturer` = '2',`id_supplier` = '1',`reference` = 'demo_10',`supplier_reference` = '',`location` = '',`width` = '0',`height` = '0',`depth` = '0',`weight` = '0',`quantity_discount` = '0',`ean13` = '',`isbn` = '',`upc` = '',`cache_is_pack` = '0',`cache_has_attachments` = '0',`is_virtual` = '0',`state` = '1',`additional_delivery_times` = '1',`id_category_default` = '7',`id_tax_rules_group` = '1',`on_sale` = '0',`online_only` = '0',`ecotax` = '0',`minimal_quantity` = '1',`low_stock_threshold` = NULL,`low_stock_alert` = '0',`price` = '0.826446',`wholesale_price` = '0',`unity` = '',`unit_price_ratio` = '0',`additional_shipping_cost` = '0',`customizable` = '0',`text_fields` = '0',`uploadable_files` = '0',`active` = '1',`redirect_type` = '301-category',`id_type_redirected` = '0',`available_for_order` = '1',`available_date` = '0000-00-00',`show_condition` = '0',`condition` = 'new',`show_price` = '1',`indexed` = '0',`visibility` = 'both',`cache_default_attribute` = '36',`advanced_stock_management` = '0',`date_add` = '2019-07-12 10:28:51',`date_upd` = '2019-09-24 09:54:02',`pack_stock_type` = '3' WHERE `id_product` = 18
```
```
#0 \classes\db\Db.php(745): DbCore->query('UPDATE `ps_prod...')
#1 \classes\db\Db.php(527): DbCore->q('UPDATE `ps_prod...', true)
#2 \classes\ObjectModel.php(738): DbCore->update('product', Array, '`id_product` = ...', 0, false)
#3 \classes\Product.php(630): ObjectModelCore->update(false)
#4 \controllers\admin\AdminProductsController.php(2563): ProductCore->update()
#5 \src\PrestaShopBundle\Controller\Admin\ProductController.php(525): AdminProductsControllerCore->processSuppliers(18)
#6 [internal function]: PrestaShopBundle\Controller\Admin\ProductController->formAction('18', Object(Symfony\Component\HttpFoundation\Request))
#7 \var\cache\dev\classes.php(4581): call_user_func_array(Array, Array)
#8 \var\cache\dev\classes.php(4536): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 \vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#10 \administrator\index.php(86): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#11 {main}
```

And this one:

```
UPDATE `ps_product_shop` SET `id_product` = '18',`id_category_default` = '7',`id_tax_rules_group` = '1',`on_sale` = '0',`online_only` = '0',`ecotax` = '0',`minimal_quantity` = '1',`low_stock_threshold` = NULL,`low_stock_alert` = '0',`price` = '0.826446',`wholesale_price` = '0',`unity` = '',`unit_price_ratio` = '0',`additional_shipping_cost` = '0',`customizable` = '0',`text_fields` = '0',`uploadable_files` = '0',`active` = '1',`redirect_type` = '301-category',`id_type_redirected` = '0',`available_for_order` = '1',`available_date` = '0000-00-00',`show_condition` = '0',`condition` = 'new',`show_price` = '1',`indexed` = '0',`visibility` = 'both',`cache_default_attribute` = '36',`advanced_stock_management` = '0',`date_add` = '2019-07-12 10:28:51',`date_upd` = '2019-09-24 09:54:02',`pack_stock_type` = '3',`id_shop` = '1' WHERE id_product = 18 AND id_shop = 1
```
```
#0 D:\wamp64\www\ps176\classes\db\Db.php(745): DbCore->query('UPDATE `ps_prod...')
#1 D:\wamp64\www\ps176\classes\db\Db.php(527): DbCore->q('UPDATE `ps_prod...', true)
#2 D:\wamp64\www\ps176\classes\ObjectModel.php(765): DbCore->update('product_shop', Array, 'id_product = 18...', 0, false)
#3 D:\wamp64\www\ps176\classes\Product.php(630): ObjectModelCore->update(false)
#4 D:\wamp64\www\ps176\controllers\admin\AdminProductsController.php(2563): ProductCore->update()
#5 D:\wamp64\www\ps176\src\PrestaShopBundle\Controller\Admin\ProductController.php(525): AdminProductsControllerCore->processSuppliers(18)
#6 [internal function]: PrestaShopBundle\Controller\Admin\ProductController->formAction('18', Object(Symfony\Component\HttpFoundation\Request))
#7 D:\wamp64\www\ps176\var\cache\dev\classes.php(4581): call_user_func_array(Array, Array)
#8 D:\wamp64\www\ps176\var\cache\dev\classes.php(4536): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 D:\wamp64\www\ps176\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#10 D:\wamp64\www\ps176\administrator\index.php(86): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false)
#11 {main}
```

**Comment by JuanjoSCu** [comment]
Rebuild the search index does not work from cron in this version.
If a product is not found, it is not sold if it is not sold, it is CRITICAL, not a minor bug.

https://github.com/PrestaShop/PrestaShop/issues/15725

**Comment by florine2623** [comment]
This issue is fixed on PS 9.0.0 :

https://github.com/user-attachments/assets/9093f064-e8fb-4376-9068-9362520aaaab

**Comment by floriangerard-rightmove** [comment]
> This issue is fixed on PS 9.0.0 :
> 
>  Screen.Recording.2024-11-27.at.11.32.54.mov
**EDIT**
Hi, can we have a hint of the file concerned by that fix, we currently have several clients between 1.7.8 and 8.2.x that have this issue.
We can't update all those Prestashop like that to 9.0.0.

The issue is still related: "when the product is save in a specific store the index is deleted in others".
We can't rely on the cron to rebuild the indexes since the clients modify regularly their products.

Any possible quickfix for that by modifying a query or something ?

Thanks,

--------

Since I needed a quickfix I digged a bit into it :

In the indexation function, if you fall in the else condition line 751 in class Search.php, I didn't understand why when you save in a shop it deletes lines in the table search_word linked to other shops since you can see this :

```
$db->execute('DELETE si FROM `' . _DB_PREFIX_ . 'search_index` si
				INNER JOIN `' . _DB_PREFIX_ . 'product` p ON (p.id_product = si.id_product)
				' . Shop::addSqlAssociation('product', 'p') . '
				WHERE product_shop.`visibility` IN ("both", "search")
				AND product_shop.`active` = 1
				AND ' . ($id_product ? 'p.`id_product` = ' . (int) $id_product : 'product_shop.`indexed` = 0'));
```

This query should only delete the datas related to the current context (Shop::addSqlAssociation) of the shop 
I missed that part and I didn't find how it is possible that datas from other shops are deleted so I went straight and just reindexed datas for all shops for that product instead with those modifications.

It's a temporary fix for me, I modified the indexation query in Search.php line 612

```
$sql = 'SELECT DISTINCT p.id_product, pl.id_lang, pl.id_shop, l.iso_code';

        if (is_array($weight_array)) {
            foreach ($weight_array as $key => $weight) {
                if ((int) $weight) {
                    switch ($key) {
                        case 'pname':
                            $sql .= ', pl.name pname';

                            break;
                        case 'reference':
                            $sql .= ', p.reference';

                            break;
                        case 'supplier_reference':
                            $sql .= ', p.supplier_reference';

                            break;
                        case 'ean13':
                            $sql .= ', p.ean13';

                            break;
                        case 'isbn':
                            $sql .= ', p.isbn';

                            break;
                        case 'upc':
                            $sql .= ', p.upc';

                            break;
                        case 'mpn':
                            $sql .= ', p.mpn';

                            break;
                        case 'description_short':
                            $sql .= ', pl.description_short';

                            break;
                        case 'description':
                            $sql .= ', pl.description';

                            break;
                        case 'cname':
                            $sql .= ', cl.name cname';

                            break;
                        case 'mname':
                            $sql .= ', m.name mname';

                            break;
                    }
                }
            }
        }

        $sql .= ' FROM ' . _DB_PREFIX_ . 'product p
        LEFT JOIN ' . _DB_PREFIX_ . 'product_lang pl
            ON p.id_product = pl.id_product
        LEFT JOIN ' . _DB_PREFIX_ . 'product_shop product_shop
            ON product_shop.id_product = p.id_product
        LEFT JOIN ' . _DB_PREFIX_ . 'category_lang cl
            ON (cl.id_category = product_shop.id_category_default AND pl.id_lang = cl.id_lang)
        LEFT JOIN ' . _DB_PREFIX_ . 'manufacturer m
            ON m.id_manufacturer = p.id_manufacturer
        LEFT JOIN ' . _DB_PREFIX_ . 'lang l
            ON l.id_lang = pl.id_lang
        WHERE product_shop.indexed = 0
        AND product_shop.visibility IN ("both", "search")
        ' . ($id_product ? 'AND p.id_product = ' . (int) $id_product : '') . '
        ' . ($ids ? 'AND p.id_product IN (' . implode(',', array_map('intval', $ids)) . ')' : '') . '
        AND product_shop.`active` = 1
        AND pl.`id_shop` IN (SELECT id_shop FROM ' . _DB_PREFIX_ . 'shop)';

        return Db::getInstance()->executeS($sql, true, false);
```

This can have border effects (like if you want some products not to be indexed in several shops), it's just a quickfix for those in need.

In the wait for a proper answer,
Thanks
