### ISSUE TITLE
Filtering by date in /Logs does not work

### ISSUE THREAD

**Issue by PrestaworksNiklas** [PrestaShop/PrestaShop#16540]
**Describe the bug**
Filtering by just a day in the filter option return "No records found".

**To Reproduce**
1. In the Back Office, go to Advanced Parameters / Logs
2. To filter by just one day, select a date in the "from" field and the same date in the "to" field.
3. Expected result: The logs for the selected day shows up
4. Result: No records found (though there are records to display)
5. To show the logs of the day you want, you have to select the actual day in "from" and the day after in "to".

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.3.5

**Comment by khouloudbelguith** [comment]
Hi @PrestaworksNiklas,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.

This issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/14926
It is fixed with PS1.7.6.1.

Thanks to downgrade your PHP version, check & feedback.

**Comment by PrestaworksNiklas** [comment]
Hi @khouloudbelguith,

I have downgraded my PHP version, added the fix you refer to but it still does not work when filtering on the same date.

**Comment by khouloudbelguith** [comment]
@PrestaworksNiklas, I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1kuaf1IAyDfu40VySQepEJc0bO1FLhrOY/view
Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Are you using a fresh install PS1.7.6.1 or an upgrade from a previous version?
Thanks to check and feedback.

**Comment by PrestaworksNiklas** [comment]
@khouloudbelguith, I use a new fresh install. I could not see that you filtered on the same date. e.g., from 25/11/2019 to 25/11/2019, in order to just see the logs from 25/11

**Comment by khouloudbelguith** [comment]
@PrestaworksNiklas, it is Ok.
https://drive.google.com/file/d/1gXPp42u6AE5Yq0oFRfOlEG8Ss2IBkWFo/view

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaworksNiklas,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by matks** [comment]
@khouloudbelguith I confirm the bug on develop

**Comment by khouloudbelguith** [comment]
@PrestaworksNiklas, @matks,

Same issue with PS1.7.5.2 & PS1.7.6.2 & develop.
https://drive.google.com/file/d/1VK7DTHraec4V5AmmaHM0MiWAqxS4ztWb/view
I’ll add this to the debug roadmap.
Thanks!

**Comment by Progi1984** [comment]
Fixed in #16883
