### ISSUE TITLE
Rounding difference between invoices and credit notes

### ISSUE THREAD

**Issue by MultiTech-MS** [PrestaShop/PrestaShop#16879]
I encounter a rounding problem when I generate a credit note with Prestashop (1.7.4.4).
The problem seems to come from the total tax on delivery in the credit note.

![facture](https://user-images.githubusercontent.com/51752454/71245003-08ab8d00-2314-11ea-8e46-c74f7fe31a7f.JPG)
![avoirs](https://user-images.githubusercontent.com/51752454/71245007-08ab8d00-2314-11ea-9c5f-982bc42e805a.JPG)

PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @MultiTech-MS,

I did not manage to reproduce the issue with PS1.7.6.2.
Invoice
[IN000007.pdf](https://github.com/PrestaShop/PrestaShop/files/3987979/IN000007.pdf)
![image](https://user-images.githubusercontent.com/16067358/71250851-056ace00-2321-11ea-8967-ee319f0c2d5f.png)
Credit notes
[000010.pdf](https://github.com/PrestaShop/PrestaShop/files/3987983/000010.pdf)
![image](https://user-images.githubusercontent.com/16067358/71250891-19163480-2321-11ea-8f97-3ba8f48ff05c.png)
In your BO => Shop Parameters => General page
You can check "Round mode", "Round type"
![image](https://user-images.githubusercontent.com/16067358/71251103-a063a800-2321-11ea-921e-0ea6a2434617.png)

PS: We have a different rounding problem, it is an issue that should be specified & fixed by our developers.
We are aware of this issue.
You can check this issue: #9779

Thanks!

**Comment by MultiTech-MS** [comment]
Hello, thank you for your return, I looked in the options and that did not solve the problem. I will see to investigate further, pending another response. I will also closely monitor post #9779.

**Comment by khouloudbelguith** [comment]
@MultiTech-MS, thanks!
Waiting for your feedback.

**Comment by khouloudbelguith** [comment]
Hi @MultiTech-MS,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
