### ISSUE TITLE
upgrade from ps 1.7.6.1 to 1.7.6.2 cause 500 Server Error on front-end

### ISSUE THREAD

**Issue by Kis-shoes** [PrestaShop/PrestaShop#17056]
Hi everyone,

I just upgraded to PS 1.7.6.2 from PS 1.7.6.1. For the upgrade I used 1-click Upgrade the latest version - v4.0.0. The process went successfully and everything seemed good from the backend. But the frontend showed 500 Server Error. Then I turned on the debug-modus and the frontend started showing again, but then product page came up with error. At this point I discovered that some modules at the backend were also not working, Theme editor module and paypal module.

Using the Debug-modus here are some of the error, product page error message and module error message
![Module error message](https://user-images.githubusercontent.com/40031239/71930142-5bea6000-319b-11ea-9402-6803db8dfbe2.JPG)
![Product page error message](https://user-images.githubusercontent.com/40031239/71930158-66a4f500-319b-11ea-923b-d7af7b30dfe6.JPG)

I look forward to your help, thank you.

Regards

**Comment by khouloudbelguith** [comment]
Hi @Kis-shoes,

>For the upgrade I used 1-click Upgrade the latest version - v4.0.0.

No, the last version of the 1-click upgrade is 4.10.1.

>Theme editor module and paypal module.

As they are not modules provided by Prestashop, we can't do anything with this. 
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.

>![image](https://user-images.githubusercontent.com/16067358/71963039-12316200-31fb-11ea-9ab9-54372e93c62d.png)

Same with this module, You should contact the module's author.

>![image](https://user-images.githubusercontent.com/16067358/71963099-31c88a80-31fb-11ea-9183-42702d9f3a4b.png)

The [ganalytics](https://github.com/PrestaShop/ganalytics) module, It has been remade for PrestaShop 1.7: [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics).
You can download it from here: https://addons.prestashop.com/en/analytics-statistics/4168-ganalytics.html

Thanks to check & feedback.

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith 

Thank you for the kind information. 
I renamed the ganalytics and that resolved the issue with product page, but still other issues to resolve. I will roll back the update, install the 1-click upgrade i download from Prestashop module Addon and make a fresh update and see what happen.

I will give a feedback afterwards, thank you.

regards

**Comment by khouloudbelguith** [comment]
@Kis-shoes, thanks!
Waiting for your feedback.

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith,

I did again a fresh upgrade with 1-click v4.10.1. The process was successful, but again the front-shop had 500 Server Error. After switching to Debug-modus the front-shop showed again. Like previously I had issues with product page and some modules, but was resolved  after I renamed ganalytics and ps_relatedpost modules. But then when I proceeded to the cart I found other issues, as you can see in the attached image below
![Checkout error](https://user-images.githubusercontent.com/40031239/71992360-8e489b80-3235-11ea-9485-242912d60525.JPG)

Looking forward to your feedback, thank you.

Regards

**Comment by khouloudbelguith** [comment]
@Kis-shoes, this issue occurs due to the supercheckout module.
As it is not a module provided by Prestashop, we can't do anything with this.
You should contact the module's author via your addons.prestashop.com account, they are the only ones to help you with it.

Thanks!

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith,
"this issue occurs due to the supercheckout module." I had this module for very long time, what is it with the update that is causing the issue. I have their latest update for Ps 1.7.6.2.

Here is also another issue I discovered
![Orders](https://user-images.githubusercontent.com/40031239/71994847-c0f49300-3239-11ea-8fa7-3211cd551b9b.JPG)

thank you

**Comment by khouloudbelguith** [comment]
@Kis-shoes, in which page this exception is displayed? Is it in the Bo or Fo?
Those issues are partially fixed in PS1761 and completely fixed in the PS1762 as reported here:
https://github.com/PrestaShop/PrestaShop/issues/15376
https://github.com/PrestaShop/PrestaShop/issues/15486
https://github.com/PrestaShop/PrestaShop/issues/14595

Thanks to check and feedback.

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith,

It is in backend when I click on order tab, thanks

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith,
this was produced when I was deleting some inactive languages in the localization
![Language delete error](https://user-images.githubusercontent.com/40031239/72061423-21391280-32d6-11ea-9e4a-35f649e4cd3d.JPG)

Regards

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith,

As you may remember you closed the other issue without really a solution, hoping that proceeding updates will solve the issues. 

This issue is becoming more complicated than I can handle. what would be your advice on how I can fix this issue efficiently, a fresh DB access or fresh installation? Thanks

Regards

**Comment by Kis-shoes** [comment]
Hi @khouloudbelguith ,

Have got the time to review my last message?
Looking forward to your response.

Regards

**Comment by khouloudbelguith** [comment]
Hi @Kis-shoes,

Sorry for the late answer.
As you can see in this screenshot
![image](https://user-images.githubusercontent.com/16067358/72248477-8bfc8d80-35f7-11ea-9f03-1305c9f548a1.png)
You have an issue in a table provided by your custom module supercheckout.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Kis-shoes,

It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I invite you to contact your module author.
I will close the issue, feel free to open a new one when needed.
Thanks!
