### ISSUE TITLE
Duplicate orders with ps_wirepayment module

### ISSUE THREAD

**Issue by mathieuhen** [PrestaShop/PrestaShop#17312]
Hi, 

We have sometime duplicate orders when we use the ps_wirepayment module. 
But not every time. 

I place orders with a clean browser each time and as a guest customer. 
And once in a while (between 1/5 or 1/10), we have duplicate orders (with the same id_cart but different reference).

I enabled the debug mode in the class PaymentModuleCore and I added a log to the front controller of the validation in the module ps_wirepayment.

And there are logs below:

![Capture](https://user-images.githubusercontent.com/43207184/72969897-b6ec9b80-3dc6-11ea-858a-e1cb51ea8b06.PNG)

Sometime the function postProcess() is called twice and sometime not.
Why and how is it possible ?

**Additional information**
PrestaShop version: 1.7.5
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @mathieuhen,

Thanks for your report.
Did you see the Mailchimp module? if yes, what is the exact version used?

Thanks!

**Comment by mathieuhen** [comment]
Hi, 

no, the mailchimp module is not installed. 
Is there a possible link with this issue ?

**Comment by khouloudbelguith** [comment]
@mathieuhen, Previously, we have this issue: http://forge.prestashop.com/browse/BOOM-5486 with Mailchimp Version1.1.3., but it is fixed.

Thanks!

**Comment by mathieuhen** [comment]
Ok, but we don't have mailchimp module. 
Do you have another idea ? 
Or do you know what the module Mailchimp did before the fix ?

**Comment by khouloudbelguith** [comment]
@mathieuhen,
About this error:
`Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart` in the logs page => it is different => issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9866

What is the exact version of the ps_wirepayment module did you use?

Thanks!

**Comment by mathieuhen** [comment]
Ok, the error 

> Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

is not the same issue. 
But it seems not resolved ? 

We use the last version of the ps_wirepayment module : v2.0.4.

**Comment by khouloudbelguith** [comment]
@mathieuhen,

>But it seems not resolved?

Yes, not resolved yet.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @mathieuhen,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
