### ISSUE TITLE
error in translation when using a theme other than classic in Prestashop 1.7.6.0

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#17324]
Hi,

I use the Prestashop 1.7.6.0 and custom theme. I have a problem with the back office translations on my site which is in multiboutique. The translation is not working for my custom theme (i.e., not classic).

I saw the old ticket (https://github.com/PrestaShop/PrestaShop/pull/14962) and with the help of this, I had also checked my code where everything seems to be normal but still I can't edit the translations for my theme custom.

And here is the error I get when I want to translate in my custom theme -

**Invalid resource provided: "1.2"; Errors: [ERROR 1871] Element '{urn:oasis:names:tc:xliff:document:1.2}xliff': Missing child element(s). Expected is one of ( ##other{urn:oasis:names:tc:xliff:document:1.2}*, {urn:oasis:names:tc:xliff:document:1.2}file ). (in /data/www/gti/gti-moondream/ps17/adminmoon/ - line 2, column 0)**

If someone has a solution ? 

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Gaja-A,

Your issue is fixed with PS1.7.6.1 with this PR: https://github.com/PrestaShop/PrestaShop/pull/14962
Your ticket is a duplicate of #14733
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #14733

**Comment by Gaja-A** [comment]
Hi @khouloudbelguith,

I tried the steps and commits mentioned in those tickets but nothing works for me ? I still have the error.

Thanks !

**Comment by khouloudbelguith** [comment]
@Gaja-A,

with PS1.7.6.0, we cannot translate a Back office or modules when using a theme other than classic
#15133 fixed with this PR: #15139
#14733 fixed with PR: #14962

They are fixed in the PrestaShop v1.7.6.1.
Thanks!

**Comment by Gaja-A** [comment]
Hi @khouloudbelguith,

Infact, we already have the same code as like in the ticket https://github.com/PrestaShop/PrestaShop/pull/14962 but it doesn't works. So I tried to do with https://github.com/PrestaShop/PrestaShop/pull/15139, where I modified all the files as mentioned in that ticket but still have the same error ?

Thanks !

**Comment by khouloudbelguith** [comment]
@Gaja-A, I did not manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.1.
It is fixed.
I attached a screen record
https://drive.google.com/file/d/16riTYgpDjHNNDYSlqb8E374VncdTdEmh/view
Thanks!

**Comment by Gaja-A** [comment]
@khouloudbelguith, I understand that it is fixed with PS1.7.6.1. 
But I need to clarify something. In our case, we are using PS1.7.6.0 and I tried both PRs on my current PS (PR: https://github.com/PrestaShop/PrestaShop/pull/15139 and PR: https://github.com/PrestaShop/PrestaShop/pull/14962), but still I got the same error.  
So could you confirm me that it's just enough to put those PRs on or anything else to do?
Thanks !

**Comment by khouloudbelguith** [comment]
@Gaja-A, Other issues fixed in PS1.7.6.1 related to the translations:
https://github.com/PrestaShop/PrestaShop/issues/14932
https://github.com/PrestaShop/PrestaShop/pull/14966
https://github.com/PrestaShop/PrestaShop/pull/15051
https://github.com/PrestaShop/PrestaShop/pull/15017
https://github.com/PrestaShop/PrestaShop/pull/14938
https://github.com/PrestaShop/PrestaShop/pull/14719
You can check the changelog for PS1.7.6.1: https://www.prestashop.com/en/system/files/ps_releases/changelog_1.7.6.1.txt

Thanks!

**Comment by ShaimyWinda** [comment]
@khouloudbelguith Hi !

The problem is that we can no longer translate our theme. (soundtrack > Translation > Theme translation)
Where we used to be able to. We've put in your various PRs and nothing works.

And in Apache, I have this error:
[Fri Jan 24 18:33:52.204726 2020] [php7:error] [pid 14287] [client 45.90.224.168:41770] script '/var/www/preprod.moondreamwebstore.fr/adminmoon/themes/new-theme/public/index.php' not found or unable to stat, referer: https://fr.preprod.moondreamwebstore.fr/adminmoon/index.php/improve/international/translations/?lang=fr&type=themes&locale=fr-FR&selected=moondream&_token=HJb8pDzKb_aCR7h7aQQsCPsIa7p_zlVLsA2psrHlnYM

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ShaimyWinda,

This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!
