### ISSUE TITLE
Email template preview 403 error

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#17759]
Cannot preview email templates from admin statusses when click on preview.
<img width="1064" src="https://user-images.githubusercontent.com/533123/74936484-81999480-53ea-11ea-8fe2-de6c228d26ba.png">

Getting this error:
<img width="1002" alt="Schermafbeelding 2020-02-20 om 14 11 28" src="https://user-images.githubusercontent.com/533123/74936726-fbca1900-53ea-11ea-947f-bc928b47e25c.png">

Temporary fixed by commenting .htaccess
<img width="339" alt="Schermafbeelding 2020-02-20 om 14 12 42" src="https://user-images.githubusercontent.com/533123/74936827-23b97c80-53eb-11ea-8fd6-da6c3e37ca00.png">

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by florine2623** [comment]
Hi @sharkooon ,
I manage to reproduce the issue with PrestaShop version 1.7.5.2 and 1.7.6.3.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

This issue is reproduced with PS1.7.5 and PS1.7.6.
Can we remove the label `regression`?

Thanks!

**Comment by lazaPH** [comment]
@khouloudbelguith 

We encounter the same issue on 1.7.6.4, in .htaccess in  _/mails_ directory.

With 
`# Apache 2.4`
`<IfModule mod_authz_core.c>`
`    Require all granted`
`</IfModule>`

the issue is gone. But are there any security issues with this code.

Thank you.

**Comment by khouloudbelguith** [comment]
Hi @sharkooon,

This issue is fixed during migration.
It is fixed in the next release 1.7.8.0.
![image](https://user-images.githubusercontent.com/16067358/89916577-0fb34280-dbf8-11ea-99b5-0c520fc4ca57.png)

Thanks!

**Comment by Prestaplugins** [comment]
Why is this issue still not fixed in 1.7.7.4 ?

**Comment by Prestaworks** [comment]
This issue exists on PS 8.1.2 also.
@khouloudbelguith

**Comment by marianhlavac** [comment]
Issue still present in 8.1.2, can someone re-open this issue, please? @khouloudbelguith

```
Server information: Linux #16~22.04.1-Ubuntu SMP Tue Oct 10 17:11:51 UTC 2023 x86_64
Server software version: Apache/2.4.52 (Ubuntu)
PHP version: 8.1.2-1ubuntu2.14
Memory limit: 128M
Max execution time: 30
Upload Max File size: 128M
```

**Comment by Juiliard** [comment]
this issue exist on 8.1.3
Server information: Linux 1 SMP Thu Jan 18 00:11:11 CST 2024 x86_64
Server software version: Apache
PHP version: 8.1.18
Memory limit: 512M
Max execution time: 300
Upload Max File size: 20M

**Comment by KodeToad** [comment]
Problem still exists in 8.1.5
renaming the .htaccess file solves the problem but allows access to anyone.
Shouldn't these templates be kept in the administration directory?
This problem should be reopened.
