### ISSUE TITLE
Faceted search changes category listing order when active

### ISSUE THREAD

**Issue by ftardio** [PrestaShop/PrestaShop#18151]
When faceted search is active and you open a category having subcategories at front-end, the order for products is not following the value specified at Prestashop Shop Parameters -> Product options -> Pagination -> Order by. It's using another order (I suspect it's listing products from every subcategory, one after another). If you deactivate this module, the order is followed correctly.

For example, you can specify "order by:  position", order products in a category as you like, and when you view this category from front-end, if it has subcategories, you'll find that this order is not followed when "faceted search" module is active.

**Comment by khouloudbelguith** [comment]
Hi @ftardio,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4 and the ps_facetedsearch module v3.4.1.
I attached a screen record
[Untitled_ Mar 17, 2020 11_33 AM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4342971/Untitled_.Mar.17.2020.11_33.AM.webm.zip)

As you can see [here](https://github.com/PrestaShop/PrestaShop/issues/9956#issuecomment-493442905), this issue is fixed.
What is the exact version PS and ps_facetedsearch module did you use?

Thanks!

**Comment by ftardio** [comment]
I'm using PS v1.7.6.2 and Faceted Search v3.4.1.

The order is correct in categories without subcategories, but at categories containing subcategories, the order is wrong.

I have configured order by: position at Prestashop options, when I go to products, filter by category and order by position, the order is accurate at backend, but at front-end order is not the same for this category. If I deactivate faceted search, then order is correct (products are ordered by position).

**Comment by khouloudbelguith** [comment]
@ftardio, thanks for your feedback.
I tried with PS1.7.6.2 and it is OK also.
In the BO => Catalog => Products page, I tried to filter by the `Accessories` category which has `stationery` and `Home Accessories` sub-categories and I sorted by position in the ascending order.
![image](https://user-images.githubusercontent.com/16067358/76855325-2e7ff980-6851-11ea-8d4f-e7b836895f2c.png)

In the BO => Shop Parameters => Product Settings page, I have this configuration
![image](https://user-images.githubusercontent.com/16067358/76855526-9d5d5280-6851-11ea-838b-b412ee29a4f7.png)

In the FO => `Accessories`  page, Products are well sorted
![image](https://user-images.githubusercontent.com/16067358/76855577-b49c4000-6851-11ea-81dc-a17fd0f9cbee.png)

Thanks to check and feedback.

**Comment by ftardio** [comment]
In my case, it's not working fine.

Try to order inside subcategories in a different order as parent category (I think this can be the key), and then look at parent category order at front-end...

**Comment by khouloudbelguith** [comment]
@ftardio, I attached a screen record
[Untitled_ Mar 17, 2020 2_13 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4343586/Untitled_.Mar.17.2020.2_13.PM.webm.zip)
Thanks to check and feedback.

**Comment by marlon8511** [comment]
Hello I have the same issue
Prestashop Version 1.7.6.4
Faceted Search 3.4.1

### Product Settings in shop parameters
Default order by  **position inside category**
Default order method **Descending**

### Faceted Search  settings
Show products from subcategories **Yes**

In the Front-end
The order products in **subcategories** is according to the parameters
The order products in **the main category** is not ok

If the faceted search module is deactivated the order products in **the main category** is according to the parameters.

I deleted and reinstalled the faceted search module and clear the cache but this didn't fix the issue.

**Comment by khouloudbelguith** [comment]
Hi @marlon8511,

I tried to follow all the steps provided.
But it is ok with PS1.7.6.4 and ps_facetedsearch module v3.4.1.
I attached a new screen record
[Untitled_ Mar 17, 2020 5_57 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4344711/Untitled_.Mar.17.2020.5_57.PM.webm.zip)
Thanks!

**Comment by marlon8511** [comment]
Hello, this is weird it looks like the module changes the behavior of the position of the products.
I also noticed that when the module is activated the box with the word relevance disappears.

**Comment by ftardio** [comment]
Right! As marlon8511 says, when module is active, I get those options at "order by" select at front-end (by default, "predetermined order" appears selected):
![image](https://user-images.githubusercontent.com/12235140/76887963-58eaaa80-6883-11ea-95ff-7be80794e37c.png)
But if I deactivate it, I "lost" first order select option ("predetermined order"):
![image](https://user-images.githubusercontent.com/12235140/76888183-c565a980-6883-11ea-8c34-07a7c869f4de.png)
Anyway, "Relevance" option get an order totally different when module is active and when it isn't, at any category.

**Comment by khouloudbelguith** [comment]
@ftardio, @marlon8511,

We have two issues:
- Product sorting (by position) is reversed when `ps_facetedsearch` module is disabled => this issue is fixed in the PS1.7.8.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/17402 as reported here: https://github.com/PrestaShop/PrestaShop/issues/17400
- An empty box for the sort options when selected not default one => this issue is fixed in the PS1.7.7.0 with this PR: https://github.com/PrestaShop/PrestaShop/pull/17005 as reported here: https://github.com/PrestaShop/PrestaShop/issues/14210

Thanks to check and feedback.

**Comment by marlon8511** [comment]
Hello @khouloudbelguith 
The first point is not the same. 
What happens is:  Product sorting (by position)  is not ok in the **main category** when ps_facetedsearch module is **enable**

**Comment by khouloudbelguith** [comment]
@marlon8511, as discussed previously, I cannot reproduce the issue.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by marlon8511** [comment]
@khouloudbelguith
I watched this video that you sent  before in this case #16130 (same case)
https://drive.google.com/file/d/1cQjMHMS7gb1E1JOLQDBJb_3i68kAEOCk/view

You can try to change the position of one product (could be "mountain fox notebook") of the subcategory (stationary) to see what happens. Place it first or between the products of the "home accessories" category

I think that way you could reproduce the issue.
Thanks for reply

**Comment by khouloudbelguith** [comment]
@marlon8511, thanks for your feedback.
Following steps that you described, but seems ok also.
I attached a screen record
[Untitled_ Mar 18 2020 5_13 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4350040/Untitled_.Mar.18.2020.5_13.PM.webm.zip)
Thanks to check and feedback.

**Comment by marlon8511** [comment]
Hi @khouloudbelguith  thanks
I can see that works well. 

I also made a ticket to the developer theme and this was the answer **"It is not theme issue, same happen with classic template, simply becue you set order of products separately for each category, and then you show them all combined in one category so the order is not valid anymore in parent category"**

But in your video works. 

I made this video.
[Untitled1.zip](https://github.com/PrestaShop/PrestaShop/files/4351253/Untitled1.zip)

**Comment by khouloudbelguith** [comment]
@marlon8511, thanks for your feedback.
I tried to create a similar situation
1. 
![image](https://user-images.githubusercontent.com/16067358/77045647-ee8c5400-69c1-11ea-8328-055984ac2239.png)
2. 
![image](https://user-images.githubusercontent.com/16067358/77045721-12e83080-69c2-11ea-8935-a910a5f7e5ef.png)
3. In the FO => ok
![image](https://user-images.githubusercontent.com/16067358/77045786-2e533b80-69c2-11ea-9504-889dc0f42bdd.png)

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by marlon8511** [comment]
@ftardio @khouloudbelguith 
Hello I fixed the problem using this:

 "/modules/ps_facetedsearch/src/Adapter/MySQL.php" 

in "getFieldMapping" method:
...
'position' => [
                'tableName' => 'category_product',
                'tableAlias' => 'cp',
                **'fieldName' => 'position',  // <- ADD THIS**
                'joinCondition' => '(p.id_product = cp.id_product)',
                'joinType' => self::INNER_JOIN,
            ],
I found this solution here #15062 by @Mindfield-Studio

**Comment by ftardio** [comment]
@marlon8511 
Yes! Your solution works! Thank you very much, it solves the problem.... so it's evident there is a problem (or a bug) with module....

**Comment by khouloudbelguith** [comment]
Hi @marlon8511,

If you have already fixed it on your end, please do send us a pull request so our developers can review it.
https://github.com/PrestaShop/ps_facetedsearch
Thanks!

**Comment by vipulhadiya** [comment]
I still have the same issue with PrestaShop 1.7.6.7 and ps_facetedsearch 3.5.0

**Comment by vipulhadiya** [comment]
> @ftardio @khouloudbelguith
> Hello I fixed the problem using this:
> 
> "/modules/ps_facetedsearch/src/Adapter/MySQL.php"
> 
> in "getFieldMapping" method:
> ...
> 'position' => [
> 'tableName' => 'category_product',
> 'tableAlias' => 'cp',
> **'fieldName' => 'position', // <- ADD THIS**
> 'joinCondition' => '(p.id_product = cp.id_product)',
> 'joinType' => self::INNER_JOIN,
> ],
> I found this solution here #15062 by @Mindfield-Studio

It does not work for PrestaShop 1.7.6.7 and ps_facetedsearch 3.6.0

**Comment by JavierEB** [comment]
I also continue with the same problem, with PS 1.7.4.3 and Faceted Search 3.7.0. Is there a way to solve this even if it is a patch ...

**Comment by djoo** [comment]
> ps_facetedsearch

Thanks a lot ! It works ! I was looking for this since a long time. Shame than prestashop doesn't fix this.

**Comment by djoo** [comment]
> > @ftardio @khouloudbelguith
> > Hello I fixed the problem using this:
> > "/modules/ps_facetedsearch/src/Adapter/MySQL.php"
> > in "getFieldMapping" method:
> > ...
> > 'position' => [
> > 'tableName' => 'category_product',
> > 'tableAlias' => 'cp',
> > **'fieldName' => 'position', // <- ADD THIS**
> > 'joinCondition' => '(p.id_product = cp.id_product)',
> > 'joinType' => self::INNER_JOIN,
> > ],
> > I found this solution here #15062 by @Mindfield-Studio
> 
> It does not work for PrestaShop 1.7.6.7 and ps_facetedsearch 3.6.0

It works for parent category, but put the mess in child category :/
Ane idea how to fix this ?

**Comment by bedruskos** [comment]
Same issue here, mess in child categories. Did anybody found the solution? 

Issue with the reproducing is probably related to the Product placement: it should be placed in several categories. 

ps_facedsearch: v3.7.1

**Comment by vskand** [comment]
~~**BAD SOLUTION (but it works)**~~
~~A bad solution I found that works for my case is the following.~~

## **NOT WORKING** 
#### Maybe it works for someone else's case so I am leaving it here
In /modules/ps_facetedsearch/src/Adapter/MySQL.php in function getFieldMapping() add before return $filterToTableMapping;
```php
$context = Context::getContext(); // Getting the context

if ($context->controller->php_self == 'category') // Checking if current controller (page) is category
{
        if ($context->controller->getCategory()->id_parent == 2) // Checking if parent category of current category is 2 (root) and thus we know we are in a first level (parent) category
	{
	      $filterToTableMapping['position']['fieldName'] = 'position'; // Adding to the query
	}				
}
```

**Comment by matthieubrunet** [comment]
Try to check "display products in sub-categories" in the facetedsearch configuration to reproduce the bug. In my case, I had the same problem, and unchecking the option restored the correct sort.

**Comment by bc-devle** [comment]
Thanks @matthieubrunet it works
