### ISSUE TITLE
Error getting Cart delivery zone

### ISSUE THREAD

**Issue by Veiss** [PrestaShop/PrestaShop#18798]
#### Describe the bug

In an order an error has occurred in the calculation of shipping costs. We have verified that the carrier is correct and the province of the address was also correct, even so the order has been saved with € 0 of shipping costs when they should be 10€.
Carriers are correctly configured with their price ranges and zones.

Investigating the error we have come to the problem, for reasons unknown, in the table ps_cart_product the lines of that cart related to the order there were some with id_address_delivery at 0 and others had the correct address id 4007. In the calculation of shipping costs in the function: getPackageShippingCost of class Cart.php there is a call to isMultiAddressDelivery line 3287. If this condition is not met, the zone is obtained from the default country so the zone is incorrect, because the address has a different zone than default

We believe that in the isMultiAddressDelivery function: The statement:
public function isMultiAddressDelivery ()
    {
        static $ cache = array ();

        if (! isset ($ cache [$ this-> id])) {
            $ sql = new DbQuery ();
            $ sql-> select ('count (distinct id_address_delivery)');
            $ sql-> from ('cart_product', 'cp');
            $ sql-> where ('id_cart ='. (int) $ this-> id);

            $ cache [$ this-> id] = Db :: getInstance () -> getValue ($ sql)> 1;
        }
        return $ cache [$ this-> id];
    }
You should add the condition that id_address_delivery! = 0

#### Expected behavior

Correct calculation of shipping cost

#### Steps to Reproduce

We found that errors on ps_cart_product in 13 carts, we dont know why it happens.

**Screenshots**
<img width="1084" alt="Captura de pantalla 2020-04-24 a las 10 59 08" src="https://user-images.githubusercontent.com/2429100/80194560-d770ff80-861a-11ea-886b-4732b7f48740.png">

#### Additional information

* PrestaShop version: 1.7.1.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Veiss ,
Could you give me the exact steps to reproduce your issue please ?
Example : 
- Go to Delivery > Carriers
- Create Carrier
- Create price range

Thanks!

**Comment by Veiss** [comment]
@florine2623 
Hi, i try to explain:
First you have to create a carrier with two range price like from 0.000€ to 37.999€ and other range from 38.00€ to 99999€ for example. Then in that carrier there will be two available zone one Spain peninsula, and other Spain not peninsula, like balears islands. The shipping cost for Spain peninsula from 0€ to 37.99 are 4.9€ and up to 38€ free shipping, in last zone, Spain not peninsula from 0€ to 37€ 10.99€ of shipping cost and up to 38€ also the shipping cost are 10.99€
Now you have to create and account with one address from balers island that is associated to Spain not peninsula zone. Then add products to cart to spend about 38€ or more. Then go to DDBB and simulate in one of each product id_delivery_address = 0, this step i dont know how is posible to stay at 0 because theoretically when customer login all cart product id_delivery_address change to correct address, but in my case there is sometimes that not happens at all.
If you hardcoded that rows of ps_cart_product there will be some rows with correct id_address_delivery and others with 0 id_address_delivery like in uploaded screenshot.
If you paid the order the shippings cost will be 0€ instead of the correct cost of 10,99€ because that function return that order has multiAddressDelivery and takes the default country zone instead of correct no peninsular zone.
I think that in that function of isMultiAddressDelivery there will be a new condition with id_address_delivery != 0 to avoid considering id_address_delivery like correct delivery address.
Thanks a lot!!

**Comment by florine2623** [comment]
Hi @Veiss ,
Sorry for taking so long to answer.
I've created the carriers as you said : 
![Capture d’écran 2020-05-05 à 16 38 39](https://user-images.githubusercontent.com/16019289/81080584-2d825480-8ef1-11ea-9072-4206d6a5160a.png)
I've created a order with a Balears address and a cost superior 38€ : 
![Capture d’écran 2020-05-05 à 16 57 27](https://user-images.githubusercontent.com/16019289/81081032-b5685e80-8ef1-11ea-9059-34750a769bd4.png)
The order went fine.

What table did you change exactly and why would you change it?
If I'm understanding well, your issue has nothing to do with the PrestaShop solution on its own ?
Thanks!

**Comment by Veiss** [comment]
@florine2623 Hi!!

The carriers configuration that perfect.
To reproduce the bug you have to access to DDBB ps_cart_product, filter by rows for current cart id and one of the rows id_address_delivery set to 0 like in the image that previously attached.
I don't know how is posible to some of ps_cart_product rows id_address_delivery has 0 value, i don't set it manually. In my production store about 13 orders has some rows with id_address_delivery value as 0... 
Thanks

**Comment by florine2623** [comment]
Hi @Veiss ,
When a cart is being created, with **no** customer logged in and **no** carrier chosen, is it normal that the id_address_delivery in ps_cart_product is empty.

Example : 
My cart with no customer logged in and no address chosen yet : 
![Capture d’écran 2020-05-07 à 14 02 14](https://user-images.githubusercontent.com/16019289/81292185-6e05dd80-906b-11ea-85be-f847d67a8009.png)

What I have in the database : 
![Capture d’écran 2020-05-07 à 14 02 24](https://user-images.githubusercontent.com/16019289/81292208-778f4580-906b-11ea-82f2-e096bbd68b19.png)

I hope it is clear enough :)
Thanks!

**Comment by Veiss** [comment]
Hi @florine2623 .
Yes i know, in my online shop id_address_delivery still set to 0 after the order was completed.
At the image previously uploaded all of product are from a cart/order that was completed, the user had logged, with address and with carrier selected. I know that in the major of cases id_address_delivery set to selected address id after user logged, but in some very small cases, i dont know why and i thinks it is very difficult to reproduce, some product in the same cart has that id to 0.

The temporally solution that i applied to my shop is what i explain at the first comment, to prevent that cases. But i know that is very difficult for you reproduce that behaviour. 
Thanks a lot!

**Comment by florine2623** [comment]
Hi @Veiss ,
Thanks for clearing that up !
Indeed I did not manage to reproduce exactly your case.
Every time a cart is created and affiliate to a customer and carrier, the data in database is correct for me in a PS1.7.6.5.
Is this issue occurring a lot ?

**Comment by Veiss** [comment]
@florine2623 
Hi, not too much, i only discovered in one shop with PS 1.7.1.2 in 17 orders more or less. 
When i has more time i will check in other shops executing that mysql query:

> SELECT DISTINCT chtown_cart_product.id_cart FROM chtown_cart_product INNER JOIN chtown_orders ON chtown_orders.id_cart = chtown_cart_product.id_cart WHERE chtown_cart_product.id_address_delivery = 0;

Thanks a lot

**Comment by florine2623** [comment]
I think the issue might have been solved in PS1.7.6.5 because I can't reproduce it.
Have you thought about doing an upgrade ?

**Comment by Veiss** [comment]
Hi @florine2623 . For that shop not actually, but does'nt matter, in new projects we are using the last version, so, dont worry about it.
Thanks a lot!!

**Comment by florine2623** [comment]
Ok @Veiss ,
Do you need more info or can I close the issue ?

**Comment by Veiss** [comment]
Hi @florine2623 
Close the issue.
Thanks for the support.
Bye!!

**Comment by Guisardo** [comment]
Hi all, I'm having this exact issue at version 1.7.7.3 with new orders. Still not sure how the cart_product reach that state.
