### ISSUE TITLE
js added in displayBackOfficeHeader doesn't have jquery

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#20292]
#### Describe the bug

js added by modules in hook displayBackOfficeHeader with addJS don't have jquery available because it's loaded after.

#### Expected behavior
For example, in ps_faviconnotificationbo module, the js is loaded before jquery.
<script type="text/javascript" src="/modules/ps_faviconnotificationbo/views/js/favico.js"></script>
<script type="text/javascript" src="/modules/ps_faviconnotificationbo/views/js/ps_faviconnotificationbo.js"></script>
<script type="text/javascript" src="/js/jquery/jquery-3.4.1.min.js"></script>

Jquery should be loaded before any addJs call
It's a regression regarding 1.7.6

#### Additional information

* PrestaShop version: 1.7.7 beta 1
* PHP version: 7.2

**Comment by jf-viguier** [comment]
Maybe fixed by https://github.com/PrestaShop/PrestaShop/pull/19712

**Comment by ttoine** [comment]
may be related to #19244

**Comment by florine2623** [comment]
Hi @jf-viguier ,
Thanks for your report, indeed it order of the scripts is different between 1.7.6.7 and 1.7.7.0.
In PS 1.7.6.7 :
![Capture d’écran 2020-07-23 à 15 34 16](https://user-images.githubusercontent.com/16019289/88294797-f7d55680-ccfc-11ea-8f1d-1e1b5fbcf867.png)

In PS 1.7.7.0 :
![Capture d’écran 2020-07-23 à 15 34 27](https://user-images.githubusercontent.com/16019289/88294813-fc9a0a80-ccfc-11ea-8d1a-cad8663d431f.png)

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

I need your knowledge on this topic !
The issue seems to be fixed with https://github.com/PrestaShop/PrestaShop/pull/19712 but it is still occurring.
What should be done in that case ?

Thanks!

**Comment by elboletaire** [comment]
> Maybe fixed by #19712

I can confirm that change actually fixes the issue. ~~But this is also an issue in 1.7.6.X, it should be fixed there too.~~ Nevermind, for a moment I thought the fix was on a non-existent 1.8 branch :_)

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

>Maybe fixed by #19712

So, can we close this issue?

Thanks!
