### ISSUE TITLE
BO - Orders page - Multi-invoice issue - Discount is applied in all invoices

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20778]
#### Describe the bug

In the BO > Order details page, when we have a multi-invoices, adding a discount to a selected invoice, it will be applied in all invoices.

#### Steps to Reproduce

1. You have already an order with multi-invoices (Product1 => IN0007) and (Product2 => IN0008)
2. Add a discount 100% for IN0007 =100%
3. The discount is applied in all invoices

**Screenshots**
After
![image](https://user-images.githubusercontent.com/16067358/91583037-eeb95400-e950-11ea-9325-ad05413b038a.png)
Before
![image](https://user-images.githubusercontent.com/16067358/91583076-f842bc00-e950-11ea-831d-fb59b60a1387.png)

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Ping @jolelievre should be fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/20776 is it?

Thanks!

**Comment by jolelievre** [comment]
@khouloudbelguith yep exactly :)

**Comment by jolelievre** [comment]
Note: this bug was partially fixed in https://github.com/PrestaShop/PrestaShop/pull/20776 but now requires more specification to decide the expected behaviour

Many fixes from the PR have been moved in separate ones (shipping fixes among other things) The PR is closed but some elements might be interesting when the issue is re-defined and fixed so I mention it here

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-council & @PrestaShop/prestashop-sa-product-managers we need specification to decide the expected behavior

**Comment by boo-code** [comment]
Still reproduces on 9.2, and the specification this is waiting for is already in the repository.

**Mechanism.** `OrderAmountUpdater::updateOrderInvoices()` computes each invoice's totals with
`Cart::getOrderTotal(..., Cart::ONLY_DISCOUNTS, $currentInvoiceProducts, ...)`. The products argument
narrows the base to that invoice, but `getOrderTotal()` fetches every cart rule of the cart, so each
invoice gets the full rule applied to its own products. `order_cart_rule.id_order_invoice` records the
invoice the discount was added to and is never read back.

Measured by replaying the back office commands, product split asserted first so neither invoice is
empty:

```
BASE   invoice A products=59.80 discount=29.90   <- not targeted, reduced anyway
       invoice B products=20.00 discount=10.00
       order    discounts=39.90
```

**The expected behaviour is written down in the project's own scenario file, commented out.**
`tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature` has 204 commented
table rows. The scenario "apply percent discount on one invoice" states an untargeted invoice at
`total_discount_tax_excl 0.0`, the invoice carrying a 50 percent rule over 50.00 of products at
`25.00` / `26.50`, and the order at `30.19` / `32.00` - which is `5.19 + 25.00` and `5.50 + 26.50`,
the sum of the invoice discounts. That is a complete specification for the discount half.

Three things follow from it, and the third is why a narrower fix does not work: per-invoice totals must
use only that invoice's rules; the amount recorded in `order_cart_rule.value` must be what the rule
takes off that invoice, not off the whole cart (it currently records the whole-cart amount for an
invoice-scoped rule); and the order discount is then the sum of those amounts. Scoping only the
invoice totals leaves the order disagreeing with its own invoices, because today's wrong behaviour is
at least self-consistent.

**Shipping is the part that is genuinely unspecified.** Shipping sits on the first invoice only, and
`isFreeShipping()` inspects every rule of the order with no invoice filter, so a free shipping rule
attached to the second invoice affects shipping carried by the first. That needs a decision; the
discount half does not.
