### ISSUE TITLE
Refund always increment stock

### ISSUE THREAD

**Issue by guigplt** [PrestaShop/PrestaShop#21005]
On BO order page, when I click on standard refund or partial refund : 

![image](https://user-images.githubusercontent.com/44002621/93324206-ddf45380-f815-11ea-8e09-2f66a8369763.png)

And I don't select the checkbox reinjectQuantities (because I just want to refund, without adding quantity in stock) : 

![image](https://user-images.githubusercontent.com/44002621/93324420-2449b280-f816-11ea-8d3d-db6851c473fd.png)

The stock is still incremented.

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @guigplt 

Thank you for your feedback!

I reproduce this issue : 
in 1.7.6.X : https://drive.google.com/file/d/1DMWzHQibNVy6RkxJqDCZMqUdfCgn_xZ0/view
in 1.7.7.x : https://drive.google.com/file/d/1DMWzHQibNVy6RkxJqDCZMqUdfCgn_xZ0/view

Could be related to #16869

**Comment by MatShir** [comment]
Hi @sarahdib and @khouloudbelguith,
Could you share the video for the 1.7.7.x version? I can't reproduce the issue. 

My steps:
1. Order demo_16 white
2. Change the status of the order to "delivered"
3. Check on the stock page the stock for the product 
4. Do a partial refund
5. Don't check reinject stock
6. Refund
7. Check the stock, => it is unchanged ✔️ 
 
Thanks

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

Yes, it is ok with 177x branch.
https://www.awesomescreenshot.com/video/1333067?key=7d7de8feabbb7fdf26347ca9eac59276
Since it is fixed, I close the issue.

Thanks!

**Comment by guigplt** [comment]
Hi,
Can I fix it in my 1.7.5.1 ?

**Comment by MatShir** [comment]
Hi @guigplt, 
To fix the bug on your side, we strongly advise you to upgrade your shop. The fix is integrated into the 1.7.7 version which will be released soon. The refund feature has been reworked, sadly you can't just take the part that this fixes it.

**Comment by DelosTR** [comment]
Hi, sorry to come back to this, but I still have the issue.
I'm on 1.7.7.8 version, I would try to fix it myself, but first I need to know in which version this fix was released.
I search in the changelog from 1.7.0.1 to 1.7.8.2
And nothing mention this bug #21005

Or at least, does someone could tell me which file cause this bug, thanks!

Edit:
ok it seems I found why, maybe it will help others:
This file: www\src\Adapter\Order\CommandHandler\IssuePartialRefundHandler.php
Search for: 
$shouldReinjectProducts = !$order->hasBeenDelivered() || $command->restockRefundedProducts();
And then comment or delete that "!$order->hasBeenDelivered() ||" :
$shouldReinjectProducts = /*!$order->hasBeenDelivered() ||*/ $command->restockRefundedProducts();

In my case, order delivered or not, it would not take into account the fact that I click on restock or not.
Warning, this is a core edit, maybe the "hasBeenDelivered" function has been updated in the next versions.
So now it works, it update the stock if I want it or not.
