### ISSUE TITLE
Automatic Discounts and Order Edit Bug

### ISSUE THREAD

**Issue by z72diego** [PrestaShop/PrestaShop#21428]
#### Describe the bug

The bug that happens when i manually edit an already created order in prestashop backoffice.

**The error occurs because I have set up automatic discounts for certain customer groups.**

The situation is like this. Customer "X" has an automatic discount of 10%, therefore, when a new order is created, this discount will be applied to all the products in the cart.

So far so good.

The problem occurs when **editing this order,** since if I add new products, the discount is also applied automatically (which should not happen, it should only happen in the cart, not in the order) and then it is not possible remove this discount in any way.

Please check this video: https://drive.google.com/file/d/1dzfiUAgdKE3EoaHqeecKTjYn0RjfT0GX/view

#### Expected behavior

When adding new products to the already created order in backoffice, no automatic discounts should be applied.

#### Steps to Reproduce

1. Go to 'Catalog -> Discounts'
2. Click on 'Add new discount' and leave discount code empty, so discount it's applied automatically. If you want, add some kind of condition (ie. user group) and in 'Actions' apply a 10% discount to Order (without shipping).
3. Add a new order from backoffice to user that has the discount applied. You will see the discount detailed perfectly.
4. Confirm the order and now, from backoffice too, try to add a new product scrolling down to 'Add new product'. After doing this you will notice that the automatic discount will also be applied to this new product. And then, if you try to delete it, the calculations will be wrong.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.34

**Comment by khouloudbelguith** [comment]
Hi @z72diego,

The issue is fixed in 1770.
In my case, I did not manage to reproduce the issue with PS1770rc1build1.
I attached a screen record
https://www.awesomescreenshot.com/video/1337262?key=80a59b6e4d0e0ca8e624ef2fdec20efb
Thanks to check and feedback.

**Comment by z72diego** [comment]
Hi @khouloudbelguith,

Thanks for your reply. 1.7.7 is still beta. How can I apply a fix for this error in my version?

**Comment by SimonGrn** [comment]
> Hi @khouloudbelguith,
> 
> Thanks for your reply. 1.7.7 is still beta. How can I apply a fix for this error in my version?

Hello,

there is no simple way, you may need to do some research on the code to find how the fix was applied. Easiest way is to upgrade when the 1.7.7.0 version will ship out.
We won't make a patch version for 1.7.6 for anything besides critical issues and security patches.

Thanks for your understanding.

**Comment by z72diego** [comment]
Hi, i just tested the problem in PS 1.7.6.8 and still happening. Can anyone give me a hand with a fix for 1.7.6.x branch?

Thanks

**Comment by SimonGrn** [comment]
Hello,

I already answered, we can't give you the exact fix as it may involve a lot of modifications.
You can however check for the fix in the code since everything is public.

I close this issue, thank you for your understanding.
