### ISSUE TITLE
[WS] Duplicate entry error generated when creating a pack 

### ISSUE THREAD

**Issue by pakka63** [PrestaShop/PrestaShop#22561]
#### Describe the bug
When I insert a product with the web service API, sometimes it happens that the operation reports an error like: 
_This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error
 code=97 message=[SQL Error] Duplicate entry '14198-10140-17460' for key 'PRIMARY'. From DbCore->insert() Query was : INSERT INTO
 `ps_pack` (`id_product_pack`, `id_product_item`, `id_product_attribute_item`, `quantity`) VALUES ('14198', '10140', '17460', '2'
)_
#### Expected behavior
The bundled product should be successful inserted.

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Create a product (ex:t-shirt) with two combinations (color: yellow and blue)
3. **BO**>**CONFIGURE**>**Advanced Parameters**>**Webservice**
4. Create a WS where you can send POST/GET request for Products
5. Try with **Postman** to insert this code in the body of your request

```
<prestashop>
<product>
	<id_category_default>2</id_category_default>
	<id_tax_rules_group >1</id_tax_rules_group>
	<id_shop_default>1</id_shop_default>
	<reference>pack_ws1</reference>
  	<price>35</price>
	<state>1</state>
	<minimal_quantity>1</minimal_quantity>
	<active>1</active>
  	<id_manufacturer/>
  	<id_supplier>1</id_supplier>
  	<link_rewrite>pack</link_rewrite>
	<available_for_order>1</available_for_order>
	<condition>new</condition>
	<show_price>1</show_price>
	<visibility>both</visibility>
	<pack_stock_type>3</pack_stock_type>
	<name><language id="1" >Pack Bundle WS 1</language></name>
	<description><language id="1">New Pack</language></description>
	<description_short><language id="1" >New Pack short</language></description_short>
	<associations>
		<categories nodeType="category" api="categories">
			<category>
				<id>2</id>
			</category>
		</categories>
		<stock_availables nodeType="stock_available" api="stock_availables">
			<stock_available>
				<id>53</id>
			</stock_available>
		</stock_availables>
		<accessories nodeType="product" api="products"/>
		<product_bundle nodeType="product" api="products">
		  <product>
			<id>71</id>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>14</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>16</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		</product_bundle>
	</associations>
</product>
</prestashop>
```

6. **SEND**
7. See error

`[SQL Error] Duplicate entry '80-73-548' for key 'ps_pack.PRIMARY'. From DbCore->insert() Query was : INSERT INTO 'ps_pack' ('id_product_pack', 'id_product_item', 'id_product_attribute_item', 'quantity') VALUES ('80', '73', '548', '1')`

I can see that the pack is already created but there's the third product with the Yellow combination is missing :sweat: 

![image](https://user-images.githubusercontent.com/23308427/103356631-92f30900-4ab1-11eb-96e1-b4220c42a8fa.png)

> The problem is corrected by changing the word "product_attribute_id" to "id_product_attribute" in the setWsProductBundle method of the Products class (classes/Product.php)

If I change "product_attribute_id" to "id_product_attribute" in my request body, I get this :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/103356161-760a0600-4ab0-11eb-8323-d0f166f97741.png)

While my product has two combination (attributes): blue and yellow

![image](https://user-images.githubusercontent.com/23308427/103356198-8fab4d80-4ab0-11eb-8f00-3d6f67f283d0.png)

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.27

**Comment by hibatallahAouadni** [comment]
Hello @pakka63 

I didn't manage to reproduce your issue with PS1.7.6.3, PS1.7.6.9 and PS1.7.7.0, see the attached screenshot below:

### PS1.7.6.3:

![image](https://user-images.githubusercontent.com/23308427/103016539-7c453300-4542-11eb-8bb7-e7fd2de98621.png)

### PS1.7.7.0:

![image](https://user-images.githubusercontent.com/23308427/103015668-2328cf80-4541-11eb-92ce-b0384f720bab.png)

Please check and feedback.
Thanks!

**Comment by pakka63** [comment]
The problem is not in the GET method but in the POST (insert) of a new product.
The GET is display correclty

**Comment by hibatallahAouadni** [comment]
Hello @pakka63 

Could you please provide the xml structure that you use to create a Pack.

Thanks in advance!

**Comment by pakka63** [comment]
Try this XML payload in POST:
[payload.txt](https://github.com/PrestaShop/PrestaShop/files/5736358/payload.txt)
Before performing the POST operation make sure that the product product_id = 5 has 2 attributes: 19 and 20

**Comment by hibatallahAouadni** [comment]
Hello @pakka63 

Thanks for your XML.
Well, here's the body of my POST Request:
```
<prestashop>
<product>
	<id_category_default>2</id_category_default>
	<id_tax_rules_group >1</id_tax_rules_group>
	<id_shop_default>1</id_shop_default>
	<reference>pack_test</reference>
  	<price>25</price>
	<state>1</state>
	<minimal_quantity>1</minimal_quantity>
	<active>1</active>
  	<id_manufacturer/>
  	<id_supplier>1</id_supplier>
  	<link_rewrite>pack</link_rewrite>
	<available_for_order>1</available_for_order>
	<condition>new</condition>
	<show_price>1</show_price>
	<visibility>both</visibility>
	<pack_stock_type>3</pack_stock_type>
	<name><language id="1" >Pack Bundle</language></name>
	<description><language id="1">New Pack</language></description>
	<description_short><language id="1" >New Pack short</language></description_short>
	<associations>
		<categories nodeType="category" api="categories">
			<category>
				<id>2</id>
			</category>
		</categories>
		<stock_availables nodeType="stock_available" api="stock_availables">
			<stock_available>
				<id>53</id>
			</stock_available>
		</stock_availables>
		<accessories nodeType="product" api="products"/>
		<product_bundle nodeType="product" api="products">
		  <product>
			<id>22</id>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>23</id>
			<id_product_attribute>14</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>23</id>
			<id_product_attribute>16</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		</product_bundle>
	</associations>
</product>
</prestashop>
```
Here's the result:

![image](https://user-images.githubusercontent.com/23308427/103095431-da385000-4600-11eb-88ac-0e6bd858612d.png)

In BO:

![image](https://user-images.githubusercontent.com/23308427/103095539-313e2500-4601-11eb-9f83-816bd9af2233.png)

Please check and feedback.
Thanks!

**Comment by pakka63** [comment]
Hello @hibatallahAouadni.
You have encounter the bug.
The id_product_attributes are not considered in the post operation. They are always evaluated to "unset".
The first id_product_attribute evaluated to "unset" leads to insert the value of the default attribute which in your case is 40.
The second id_product_attribute evaluated to "unset" leades to a "Duplicated entry error" because the default attribute id is already present (this error is observed if you enable the debug messages in BO) and is not inserted.

The problem is corrected by changing the word "**product_attribute_id**" to "**id_product_attribute**" in the setWsProductBundle  method of the Products class (classes/Product.php)

![img](https://user-images.githubusercontent.com/28590405/103166634-5f4f7f00-4824-11eb-9555-393523e85610.png)

**Comment by hibatallahAouadni** [comment]
Hello @pakka63 

Thanks for the clarification :slightly_smiling_face: 
So, I managed to reproduce the issue with PS1.7.6.3 and PS1.7.7.0, here's the steps to reproduce the issue:

1. **BO**>**SELL**>**Catalog**>**Products**
2. Create a product (ex:t-shirt) with two combinations (color: yellow and blue)
3. **BO**>**CONFIGURE**>**Advanced Parameters**>**Webservice**
4. Create a WS where you can send POST/GET request for Products
5. Try with **Postman** to insert this code in the body of your request

```
<prestashop>
<product>
	<id_category_default>2</id_category_default>
	<id_tax_rules_group >1</id_tax_rules_group>
	<id_shop_default>1</id_shop_default>
	<reference>pack_ws1</reference>
  	<price>35</price>
	<state>1</state>
	<minimal_quantity>1</minimal_quantity>
	<active>1</active>
  	<id_manufacturer/>
  	<id_supplier>1</id_supplier>
  	<link_rewrite>pack</link_rewrite>
	<available_for_order>1</available_for_order>
	<condition>new</condition>
	<show_price>1</show_price>
	<visibility>both</visibility>
	<pack_stock_type>3</pack_stock_type>
	<name><language id="1" >Pack Bundle WS 1</language></name>
	<description><language id="1">New Pack</language></description>
	<description_short><language id="1" >New Pack short</language></description_short>
	<associations>
		<categories nodeType="category" api="categories">
			<category>
				<id>2</id>
			</category>
		</categories>
		<stock_availables nodeType="stock_available" api="stock_availables">
			<stock_available>
				<id>53</id>
			</stock_available>
		</stock_availables>
		<accessories nodeType="product" api="products"/>
		<product_bundle nodeType="product" api="products">
		  <product>
			<id>71</id>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>14</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>16</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		</product_bundle>
	</associations>
</product>
</prestashop>
```

6. **SEND**
7. See error

`[SQL Error] Duplicate entry '80-73-548' for key 'ps_pack.PRIMARY'. From DbCore->insert() Query was : INSERT INTO 'ps_pack' ('id_product_pack', 'id_product_item', 'id_product_attribute_item', 'quantity') VALUES ('80', '73', '548', '1')`

I can see that the pack is already created but there's the third product with the Yellow combination is missing :sweat: 

![image](https://user-images.githubusercontent.com/23308427/103356631-92f30900-4ab1-11eb-96e1-b4220c42a8fa.png)

> The problem is corrected by changing the word "product_attribute_id" to "id_product_attribute" in the setWsProductBundle method of the Products class (classes/Product.php)

If I change "product_attribute_id" to "id_product_attribute" in my request body, I get this :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/103356161-760a0600-4ab0-11eb-8323-d0f166f97741.png)

While my product has two combination (attributes): blue and yellow

![image](https://user-images.githubusercontent.com/23308427/103356198-8fab4d80-4ab0-11eb-8f00-3d6f67f283d0.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by boo-code** [comment]
Still reproduces on 9.2.x, and @pakka63's diagnosis was right.

The association declares three fields in `Product::$webserviceParameters`:

```php
'product_bundle' => [
    'resource' => 'product',
    'api' => 'products',
    'fields' => [
        'id' => ['required' => true],
        'id_product_attribute' => [],
        'quantity' => [],
    ],
],
```

`getWsProductBundle()` returns those same names. `setWsProductBundle()` read `product_attribute_id`, which appears nowhere in the schema, so a payload built from the documented fields — or round-tripped from a GET response — always fell into the `isset` branch and passed 0.

`Pack::addItem()` turns that 0 into the item's default combination, and `ps_pack` is keyed on `(id_product_pack, id_product_item, id_product_attribute_item)`. Sending combinations 10, 11 and 12 of a product whose default is 9:

```
Duplicate entry '19-2-9' for key 'ps_pack.PRIMARY'
INSERT INTO `ps_pack` (`id_product_pack`, `id_product_item`, `id_product_attribute_item`, `quantity`) VALUES ('19', '2', '9', '1')
```

Worth adding to the report: the error is the lucky case. A pack with a single mis-keyed item stores the wrong combination and reports nothing, so this can also corrupt quietly.

Fix prepared on `9.2.x`: read `id_product_attribute`, keeping `product_attribute_id` as a fallback so anything written against this method's actual behaviour keeps working. `Product::addCustomizationPrice()` already handles the same pair of names that way, so it follows existing precedent rather than inventing one.

Covered by four integration tests; reverting `classes/Product.php` alone makes two of them fail with that same duplicate entry error, while the two pinning unchanged behaviour still pass. `tests/Integration/Classes/` is 187/187.

I am at the open-PR limit, so I cannot open it yet. I will link it here as soon as a slot frees.
