### ISSUE TITLE
Move the ecotax VAT selection

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#22827]
#### Is your feature request related to a problem?

The ecotax can be toggled in the "Tax Options" section from the _International > Taxes_ page.
Once enabled, a new drop-down is displayed containing all the tax rules, allowing the merchant to choose the VAT rate that will be applied on the ecotax.

The ecotax is subject to VAT at the same rate applicable to the product.

So, it's a no sense to have the ecotax VAT drop-down on this page.

#### Describe the solution you'd like

The ecotax VAT drop-down should be on the product page, in the pricing tab and also while editing a combination instead of in the _International > Taxes_ page

**Comment by Julievrz** [comment]
@MatShir @camilleganzin 

I have a question about the wording of this issue: 

![image](https://user-images.githubusercontent.com/70583503/156733003-7f7148bc-9f99-49b0-bc68-43aecd66c13d.png)

If I understand well, the "Ecotax" field allows defining the VAT rate to be applied to the ecotax (see [specs](https://build.prestashop.com/prestashop-specs/1.7/broader-topics/ecotax.html#where-is-the-ecotax-in-prestashop)). 

With the current wording, it seems like the merchant needs to define the rate of the ecotax (and not of the VAT rate applied to the ecotax). This is confusing, as "[the amount of the ecotax is fixed](https://build.prestashop.com/prestashop-specs/1.7/broader-topics/ecotax.html#what-is-the-ecotax)".)

I think the help text should rather be "Set the VAT rate to be applied to the ecotax." 

Also, according to the specs "[the ecotax is subject to VAT at the same rate applicable to the product.](https://build.prestashop.com/prestashop-specs/1.7/broader-topics/ecotax.html#how-does-the-ecotax-work)"

If the VAT is the same, why does the user need to select it again?

If it is not possible to apply the same VAT rate as the product automatically, then it should be specified in the help text: "Define the VAT rate to be applied to the ecotax. It should be the same as the product's VAT rate."

**Comment by armellerom** [comment]
Hello,
Any News for this issue ?
Vat calculation for ecotax is still incorrect in prestashop 8.2 and more
The legal rule is "The ecotax is subject to VAT at the same rate applicable to the product."
Prestashop is not doing that
Can you change prestashop to enter ecotax excluding tax in the product page and then calculate the tax ?
- price excl. VAT + ecotax excl. VAT = total excl. VAT
- Total excl. VAT x % tax = tax amount
- Total excl. VAT + tax amount = total including tax.

thanks

**Comment by boo-code** [comment]
Still the case on 9.2, and armellerom's 2025 comment reframes this from a placement question into a correctness one, which is worth separating.

`PS_ECOTAX_TAX_RULES_GROUP_ID` is a single global configuration value, and it is applied independently of the product's own tax rule in several places:

- `classes/tax/Tax.php:172` builds the tax manager for the ecotax from it directly
- `classes/Product.php:3743` caches it into `self::$psEcotaxTaxRulesGroupId`
- `src/Adapter/Order/OrderDetailUpdater.php:551` uses it when recalculating an order line
- `src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php:304` and `Combination/QueryHandler/GetCombinationForEditingHandler.php:206` read it to present the value

So there are two distinct requests on this thread and they need different answers:

1. **Move the drop-down to the product page.** That is a placement change, and it turns one global setting into per-product data - a new column plus a migration, not a form move.
2. **Make the ecotax follow the product's tax rate**, which is what armellerom is asking for and what the quoted legal rule implies. That does not need a drop-down anywhere: it means the ecotax stops having a tax rule of its own and uses the product's, which makes `PS_ECOTAX_TAX_RULES_GROUP_ID` redundant rather than relocated.

The two are mutually exclusive - the second removes the setting the first wants to move. Which one is intended changes the whole shape of the work, and the second also changes tax amounts on existing shops, so it is a fiscal decision rather than a technical one. The `Ready` label predates the 2025 comment, so it likely refers to the first reading only.
