### ISSUE TITLE
Problem when fast clicking and adding more items to cart than in stock

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#23187]
#### Describe the bug

When you change product quantity fast, you are able to add more items to cart than is in stock.
This is a problem only when order-out-of-stock-products is disabled.

#### Expected behavior
- User should not be able to input more items than in stock, if OOSP is disabled.
- Even if he manages to submit this by manually submitting the URL or whatever bug like this, cart controller should adjust this back to the number that is in stock, if OOSP is disabled.

#### Steps to Reproduce

1. Make a product, set 4 pieces in stock. Set deny orders if not in stock.
2. Go to this product in FO.
3. Quickly click to add more pieces in stock, then immediately hit Add to cart, before the page updates.
4A. On classic theme, cart modal does not appear. When you hit refresh, items are in cart.
4B. On classic-rocket theme, cart modal appears, but left side is empty.
5. Go to cart, see that more items are added to cart, then in stock.

**Video**
https://drive.google.com/file/d/1gBx_dvnqWDgDoCib1gvCpGFlsRjwTvaZ/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6.2, 1.7.7
* Themes: Classic, https://github.com/prestarocket-agence/classic-rocket
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

You may add more than the stock (if you click fast) but you can't proceed to checkout, as you can see the **Proceed to checkout** button is disabled:

![image](https://user-images.githubusercontent.com/23308427/107351204-9e7f1a00-6aca-11eb-8f6b-a8ce1793a0fd.png)

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
Hi @hibatallahAouadni, yes that is correct. But the modal does not appear at all and it looks like nothing was added to cart, until you manually refresh the page.

And he should not be allowed to click the button at all. 😎

**Comment by kpodemski** [comment]
Please test it on `develop` as this was fixed there from what I remember

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

On develop branch, the modal doesn't shown up and an error alert displayed :heavy_check_mark: 
But if you refresh the page, you will see that the product already add to the cart with the given quantity :confused: 
See the attached screen record below:

https://drive.google.com/file/d/1zKIuc4-rbReXgRhUS3bQoim6qqNW5oXj/view

Please check and feedback.
Thanks!

**Comment by kpodemski** [comment]
Right, there's a problem, maybe it would be good to disable button on the time ajax request is processed 🤔 The moment we click +1 or -1 we should have a little delay to allow PrestaShop to check if we can add or not product to cart, or - we could check this on `CartController` 🤔

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@kpodemski it means this issue need specs :wink: 
@Hlavtox thanks for your issue and helping PS to be better :wink: 

Ping @PrestaShop/product-team I think this bug need specs, could you please check @kpodemski proposition.
Thanks in advance.

**Comment by Hlavtox** [comment]
@kpodemski @hibatallahAouadni Good idea, this would be the fix for the buttons.

```
$(document).on('click','.product-add-to-cart .js-touchspin', {} ,function(e){
    $('.js-add-to-cart').attr('disabled','disabled');
});
```

However, it still does not prevent the user from typing the number manually into the box and clicking add to cart.
It must be first prevented on the controller side. Would this "simple" check be sufficient?

```
if ($quantity_to_add > $amount_in_stock && $product.oosp === false) {
  $quantity_to_add = $amount_in_stock;
}
```

**Comment by boo-code** [comment]
Both concrete asks in this thread are implemented on 9.2.x. Measured rather than read.

**Server side** - @Hlavtox's "it must be first prevented on the controller side". Product with 4 in stock, "Deny orders" set (`out_of_stock = 0`, `isAvailableWhenOutOfStock` false), calling `Cart::updateQty()` directly:

```
updateQty(10) returns false  -> cart holds 0
updateQty( 5) returns false  -> cart holds 0
updateQty( 4) returns true   -> cart holds 4
```

A single oversized quantity is therefore refused. Since the report is about a race rather than one large request, I also modelled the interleaving - two `Cart` objects on the same cart id, alternating `+1`, which is the shape of several add requests in flight:

```
round 1: A=true   B=true   -> cart holds 2
round 2: A=true   B=true   -> cart holds 4
round 3: A=false  B=false  -> cart holds 4
round 4: A=false  B=false  -> cart holds 4
```

It stops at stock, and `checkQuantities()` on the result is true. The guard re-reads stock on each call, so successive clicks do not accumulate past it. That models interleaved requests, not two processes racing inside the same read-then-write window, which this does not rule out.

For completeness, forcing a quantity past the guard with the skip-availability flags leaves 10 in the cart and `checkQuantities()` correctly returns false, so the checkout gate behind it still holds.

One difference from the request worth noting: expected behaviour 2 asked that the controller "adjust this back to the number that is in stock". Core does not clamp - it refuses the whole update and returns an error. Arguably the better of the two, since silently changing the requested quantity is its own surprise, but it is not literally what was asked for.

**Front office** - @kpodemski's "it would be good to disable button on the time ajax request is processed". That is in place: `themes/_core/js/cart.js:85` sets `addToCartButton.prop('disabled', true)` on submit and re-enables it at line 151, and the error branch at 175-179 fills `.js-error`. It arrived after this report:

| release | button disabled during request |
| --- | --- |
| 1.7.6.2, 1.7.7.0 (reported) | no |
| 1.7.8.11 and later | yes |

PR #28571, which reworked the same file's error response, was closed unmerged, so the current behaviour is the 1.7.8-era version and not that PR's.

Not verified: I did not drive the fast-click race in a browser, so this covers the two mechanisms the thread asked for, not the exact video. Given both are present, re-testing the original scenario looks like the remaining step before this can be closed.
