### ISSUE TITLE
BO - Orders - Order message - Order message with the same title is not displayed in the "order_message" list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24535]
#### Describe the bug

In the BO > Orders > Order details page > in the messages block, The order messages with the same title is not displayed in the "order_message" list

#### Expected behavior

In the PS1769, they are well displayed
![image](https://user-images.githubusercontent.com/16067358/118527980-1b610600-b742-11eb-88c6-c04c8f27f360.png)

#### Steps to Reproduce

1. Go to BO > Customer Service > Order message > Create two message with the same title for example "Test"
![image](https://user-images.githubusercontent.com/16067358/118528445-9fb38900-b742-11eb-92a0-287bc2149ab2.png)
2. Go to BO > Orders > Orders page
3. View any order
4. In the Message block > Only the last one is displayed in the order_message list
![image](https://user-images.githubusercontent.com/16067358/118528493-b1952c00-b742-11eb-8dab-23e0173b44ec.png)

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

**Comment by Progi1984** [comment]
@MatShir We have exactly the same problem as this issue : https://github.com/PrestaShop/PrestaShop/issues/22870#issuecomment-771720714. Do we conclude on the same conclusion (unicity on name) ?

**Comment by MatShir** [comment]
Yes, it would make more sense for the name to be unique to avoid confusion in the system and for merchants.

**Comment by Progi1984** [comment]
@MatShir No problem. I lock creation if name is existing.

**Comment by Progi1984** [comment]
@MatShir I labelled the issue as "PM :heavy_check_mark: "

**Comment by Progi1984** [comment]
Fixed in #24579 by @Progi1984

**Comment by kmorgen** [comment]
Not sure if related to this bug, but noticed the pre-made Order Messages are no longer in the customer language anymore - but only in the shop default/admin language.

Noticed it in 1.7.7.4 (not sure if introduced in earlier version, but used to work fine in +1.7.7), and still not working in 1.7.7.5.

**Comment by Progi1984** [comment]
@kmorgen Thank you for your feedback. Please open an issue if you think you have found a bug.
