### ISSUE TITLE
BO - the supplier of the demo pack is not selected 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24617]
#### Describe the bug

>When we create an order for the demo pack product, an exception is displayed

This issue is fixed by another PR
But we have only another issue with the **demo pack**.
The supplier of the demo pack is not selected

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Edit the pack product > Options tab
3. Check the supplier

![image](https://user-images.githubusercontent.com/16067358/119169193-034ef680-ba62-11eb-8ada-9e5538d0e811.png)

With PS177, we don't have any supplier created at the installation
#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4, 7.2

**Comment by PierreRambaud** [comment]
I think it has already been fixed by this PR: #24611

**Comment by MatShir** [comment]
Hi,
I can't reproduce the issue. @khouloudbelguith or @hibatallahAouadni could you do a second check please 🙏

**Comment by hibatallahAouadni** [comment]
Hello everyone,

I didn't reproduce the issue, LGTM see the attached screen record below:

https://drive.google.com/file/d/1TMMB95nxWlAO9cobt-Qdh_UkH9yHZ-iW/view

I think we should close the issue :sweat_smile: 
@khouloudbelguith wdyt?

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud, @MatShir, @hibatallahAouadni,

The First issue is OK :heavy_check_mark: 
There is no exception on the FO > Order confirmation page.
But the second issue is still reproduced:

1. Go to BO > Catalog > Products page
2. Edit the pack product > Options tab
3. Check the supplier

https://drive.google.com/file/d/16uj4Dxs8MyWActPgcC_n8liLbc3MPVVZ/view?usp=sharing
I used PHP7.4.

Thank you!

**Comment by PierreRambaud** [comment]
@khouloudbelguith I've the same problem using PHP7.2, it's not related to PHP7.4
![image](https://user-images.githubusercontent.com/1462701/120653782-51f88980-c481-11eb-999a-7c5ec013add7.png)

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I will update my issue.

Thanks!

**Comment by PierreRambaud** [comment]
Afaik, it couldn't be considered as a regression since there was nothing in the previous version. Seems to be a trivial bug :thinking:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/24924
