### ISSUE TITLE
Error on fresh Prestashop install

### ISSUE THREAD

**Issue by PrestaTurk** [PrestaShop/PrestaShop#25191]
#### Describe the bug

Hi. I'm getting an error on fresh (downloaded from offical website) Prestashop install. I can't install Prestashop 1.7.6.5 anymore. Problem is throwing an error on module addons install step 67%. If I turn on debug mode on I see an error about of ps_facebook. Prestashop trying to install ps_facebook module but can't. There is some issue for ps_facebook module.

#### Steps to Reproduce
Download Prestashop 1.7.6.5 and try to install.

#### Additional information
* PrestaShop version: 1.7.6.5
* PHP version: 7.1

#### For somebody my temporary solution is 

Before the install. Open `src/PrestaShopBundle/Install/Install.php` file and search for 
```
/**
         * TODO: Remove blacklist once 1.7 is out.
         */
        $blacklist = array(
            'bankwire',
            'blockadvertising',
            'blockbanner',
            'blockbestsellers',
            ...
```
 lines. Add `'ps_facebook',` top of the `'bankwire',` line. Prestashop will skip the ps_facebook module on install. You can try to install again after that fix.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaTurk 

Could you please check it again, I think the issue is fixed. We use to have some issue with Addons API.
Please check and feedback.

Thanks!

**Comment by han0032** [comment]
Same problem I have in 1.7.7.5
![error_ps_facebook](https://user-images.githubusercontent.com/73722211/124113729-0deea980-da6c-11eb-841d-b45ebeb5af52.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @Carefreelol 

Try to comment these lines https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/install-dev/controllers/http/process.php#L245-L252

```
if (($module = Tools::getValue('module')) && $id_module = Tools::getValue('id_module')) {
            $result = $this->model_install->installModulesAddons(array('name' => $module, 'id_module' => $id_module));
        } else {
            $result = $this->model_install->installModulesAddons();
        }
        if (!$result || $this->model_install->getErrors()) {
            $this->ajaxJsonAnswer(false, $this->model_install->getErrors());
        }
```

And reinstall. Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaTurk 

I encounter another issue while installing the PS1.7.6.5, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/124116841-b6ead380-da6f-11eb-810b-e19feb8ada28.png)

Ping @PrestaShop/prestashop-core-developers any idea about this issue? cause even @SD1982 encounter the same issue about ps_facebook :confounded:

**Comment by PrestaTurk** [comment]
Same issue still going on. I just tested version Prestashop 1.7.6.5, I don't know what is going on other versions. I was getting this error not today. Some couple of months ago, I'm tryed to install Prestashop but I couldn't. This error is not new I guess.

#### For somebody my temporary solution is 

Before the install. Open `src/PrestaShopBundle/Install/Install.php` file and search for 
```
/**
         * TODO: Remove blacklist once 1.7 is out.
         */
        $blacklist = array(
            'bankwire',
            'blockadvertising',
            'blockbanner',
            'blockbestsellers',
            ...
```
 lines. Add `'ps_facebook',` top of the `'bankwire',` line. Prestashop installer will skip the ps_facebook module on install. You can try to install again after that fix.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Sorry to tell you that this issue is not related to the Core but to Addons.
And right now, the Addons Team is working to fix the issue :tada: it will be fixed ASAP
So, I'm closing this issue but I will notify you on this issue when it fix.

Thanks for understanding :pray:

**Comment by stefan776** [comment]
> Hello @Carefreelol
> 
> Try to comment these lines https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/install-dev/controllers/http/process.php#L245-L252
> 
> ```
> if (($module = Tools::getValue('module')) && $id_module = Tools::getValue('id_module')) {
>             $result = $this->model_install->installModulesAddons(array('name' => $module, 'id_module' => $id_module));
>         } else {
>             $result = $this->model_install->installModulesAddons();
>         }
>         if (!$result || $this->model_install->getErrors()) {
>             $this->ajaxJsonAnswer(false, $this->model_install->getErrors());
>         }
> ```
> 
> And reinstall. Please check and feedback.
> Thanks!

Not working :)

**Comment by stefan776** [comment]
![image](https://user-images.githubusercontent.com/62173515/124518973-a2e8fe00-ddf0-11eb-8b89-a3ddb4ba42cf.png)
