### ISSUE TITLE
[FO] Add to cart not working when clicking on icon cart

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [PrestaShop/PrestaShop#26433]
#### Describe the bug

When we click on the cart icon inside add to cart button, product don't work.

#### Expected behavior

When we click on the cart icon inside add to cart button, product should work

#### Steps to Reproduce

1. Go to product page
2. Click on icon cart inside add to cart button
3. See product not added to cart

**Screenshots**

<img width="1126" alt="Capture d’écran 2021-10-26 à 19 06 42" src="https://user-images.githubusercontent.com/92941405/138927175-d6ec4ee2-a445-4179-a695-cf49f439dc9b.png">

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by alexandrebru83** [comment]
I think this bug come from this change #17243 :
`$(event.target).closest('form')`
to
`$(event.target.form)`

**Comment by kpodemski** [comment]
@alexandrebrubeyonds could you check the related PR? It should solve the issue.

**Comment by alexandrebru83** [comment]
Oh you already fixed it 🤣 too fast for me

I tested your PR, it's working and it's better than me !

Better & Faster 👏 

Just one thing with the improvement of move outside button working. If we click on icon when button is outside it's still not working.

**Comment by kpodemski** [comment]
@alexandrebrubeyonds can you show me an example? I think the icon is supposed to be inside a `button` tag, do you think of some other scenario?

**Comment by alexandrebru83** [comment]
I retested and it works even if button is outside the form and we click on icon. Good for me

**Comment by alexandrebru83** [comment]
@hibatallahAouadni PR is still available with #26434

**Comment by hibatallahAouadni** [comment]
Hello @alexandrebrubeyonds 

Thanks for reporting this issue!
I reproduce the issue only with PS1780 and develop, so it's indeed a **regression**!
I’ll add this to the debug backlog so that it’s fixed.

Thanks @kpodemski for your quick replies and your PR :rocket: 

Thank you

**Comment by PululuK** [comment]
Fixed by #26434
