### ISSUE TITLE
MULTISTORE_FIELD_PREFIX constant not recognized by symfony service

### ISSUE THREAD

**Issue by L3RAZ** [PrestaShop/PrestaShop#26884]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since Symfony version changed, definition of constants changed in .yml service definition files. But there is one file that wasn't changed and it's causing issues.

In  app/config/config.yml  line 85           
multistore_field_prefix: !php/const:PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler::MULTISTORE_FIELD_PREFIX
Shoud be changed to (replaced ":" with space) :
multistore_field_prefix: !php/const PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler::MULTISTORE_FIELD_PREFIX

![image](https://user-images.githubusercontent.com/25088641/144812988-db08e963-4eea-4217-9fac-7380e795f6c7.png)

### Steps to reproduce

1. Module is installed that uses multistore fields
2. Go to BO
3. See error

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by hibatallahAouadni** [comment]
Hello @L3RAZ 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by zuk3975** [comment]
This was fixed here https://github.com/PrestaShop/PrestaShop/pull/24609, but Its not in 1.7.8.x yet as I see.

**Comment by jolelievre** [comment]
Hi @L3RAZ 

I don't see the problem in this file on develop branch https://github.com/PrestaShop/PrestaShop/blob/fbf1db6512d7fa0f7d81ca9e1411bc073a3b3b42/app/config/config.yml#L28 and it's been modified along with the framework upgrade so there shouldn't be any invalid intermediate state

I don't understand why it's different for you, did you maybe upgrade your shop from 1.7?

**Comment by L3RAZ** [comment]
Hello @jolelievre This has been fixed and merged to develop in this commit: https://github.com/PrestaShop/PrestaShop/commit/7eb3edd57db41c99ef53c3195067a49ec357fa97
The issue was noticed on 1.7.8.1 and as I see it still persists on 1.7.8.2 release. I just downloaded new release zip and checked the file to confirm.
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/app/config/config.yml#L85

**Comment by L3RAZ** [comment]
Possible cause: A module had newer symfony/yaml dependency (by another composer dependency) which was causing this exception because of the old syntax used.

**Comment by pajasry** [comment]
I would like to reopen this issue as the bug still persist in 1.7.8.8. My [proposed solution](https://github.com/PrestaShop/PrestaShop/pull/28046) still works but missing in current version of prestashop.

The syntax was corrected on [line 28](https://github.com/PrestaShop/PrestaShop/blob/03cfb1c047e8406a7fa93bf3f1d21e662f7bd950/app/config/config.yml#L28) but not on [Line 85](https://github.com/PrestaShop/PrestaShop/blob/03cfb1c047e8406a7fa93bf3f1d21e662f7bd950/app/config/config.yml#L85)
