### ISSUE TITLE
SEO preview block in Category and Pages is not well displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27414]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On Edit a Category page, there are 2 bugs.
- 1 regarding the description not displayed
- 1 regarding the block being shifted when too many characters

On Edit a Page page, there is 1 bug.
- The SEO Preview block being shifted when too many characters

### Expected behavior

The description should be displayed when it exists
The SEO Preview block should not shift to the left

### Steps to reproduce

1. **Go to BO > Catalog > Categories > Edit a category**
2. Fill in a description
3. See error : the description should be displayed (now only the meta-description is displayed if filled in) 🚫 
<img width="781" alt="Screenshot 2022-01-19 at 15 31 55" src="https://user-images.githubusercontent.com/16019289/150379296-34fd70f3-aa5e-4be2-b7b6-ce740f0a4d0f.png">

<s>1. **Go to BO > Catalog > Categories > Edit a category**
2. Fill in Meta title with more than 62 characters
3. See error : The SEO Preview is shifted to the left (should not move) 🚫 </s>
<img width="1026" alt="Screenshot 2022-01-19 at 15 37 06" src="https://user-images.githubusercontent.com/16019289/150379362-7e59a989-d33f-4cfc-800d-32c3f6dd065e.png">

1. **Go to BO > Design > Page > Edit a page**
2. Fill in Meta title with too a lot of characters
3. See error : The SEO Preview is shifted to the left (should not move) 🚫 
<img width="990" alt="Screenshot 2022-01-19 at 15 40 38" src="https://user-images.githubusercontent.com/16019289/150379470-6be362e5-680d-4bde-ad13-52246770a09b.png">

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
First 2 issues are fixed on 9.0.0.

![Image](https://github.com/user-attachments/assets/0039049d-bb66-4bc9-8c46-c29fac9fccdf)

**Comment by Hlavtox** [comment]
@florine2623 SEO preview box is working correctly for me on 9.0.0, can you check? No shifting to the left. It goes full width only on small sceens, but that's expected.

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional

**Comment by paulnoelcholot** [comment]
Hello @Progi1984 

I reproduce the first bug : 

<img width="1186" height="671" alt="Image" src="https://github.com/user-attachments/assets/9ab2e586-2f9b-4d89-afce-88a8ad6f824c" />

The second bug is fixed : 

<img width="1188" height="304" alt="Image" src="https://github.com/user-attachments/assets/c65d0594-d44b-42e4-9ad9-fb6cc70b2677" />

The third bug is still here : 

<img width="673" height="407" alt="Image" src="https://github.com/user-attachments/assets/02a551d3-13f7-4cf8-bb4f-2aeac4a5a3cd" />

**Comment by Progi1984** [comment]
The third bug is fixed #39901

**Comment by Progi1984** [comment]
The first bug is fixed https://github.com/PrestaShop/PrestaShop/pull/39897
