### ISSUE TITLE
JS error in back office product page

### ISSUE THREAD

**Issue by grzegorzgit** [PrestaShop/PrestaShop#28047]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In back office, on product page there is an JS error:
 Uncaught SyntaxError: redeclaration of let moduleCardController
    <anonymous>my-url/adminxxxx/themes/default/js/bundle/module/module_card.js?1.7.8.3:1

There is also another error:
Uncaught Error: Syntax error, unrecognized expression: --here starts product description--

The second error says that "product description" is not valid javascript, and of course it is not. This second error appears randomly, after refreshing the page it may or may not appear. 

Someone has already [reported this issue](https://githubhot.com/repo/PrestaShop/PrestaShop/issues/27309), but without any solution.

### Expected behavior

This error breaks JavaScript execution on the back office product page, making it unable to edit products.

### Steps to reproduce

- Go to product page in back office to edit the products. 
- Open JS console, there is the error, and without debug mode it breaks all the js execution so even TinyMce is not loaded.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

 7.2.34 and 7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @grzegorzgit 

We already know this problem, but as @florine2623 answers, the old product page will be replaced by the new one, which you can test and you will not have any problem on it :wink: 
As you can see in the attached screen record below, I didn't encounter the issue on Product Page V2:

https://user-images.githubusercontent.com/23308427/160443702-b78f507d-7af4-40d0-86f0-311332f9c90e.mp4

Closing the issue as the bug is fixed in the new Product Page V2.
PS: If you need an explanation of why we won't fix the bug in the old product page, please let me know so I can ping the product team to explain it to you :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20484

**Comment by grzegorzgit** [comment]
Thank you @hibatallahAouadni for your answer. What do you mean by Product Pave V2? In which Prestashop version will it be available? I see you use 1.7.8.5, and it is still not there?

**Comment by hibatallahAouadni** [comment]
Hello @grzegorzgit 

Follow these steps to activate the Product Page V2 so you can use it :wink: 

1. **BO** > **CONFIGURE** > **Advanced Parameters** > **Experimental Features**
2. Enable the **Experimental product page** 
3. Save
4. **BO** > **SELL** > **Catalog** > **Products**
5. Click on **New Product on experimental page**
6. Enjoy it :tada: 

Or you can check the attached screen record on my comment above and follow my steps :wink: 

Thanks!

**Comment by grzegorzgit** [comment]
But it clearly says that experimental features should not be used in production. What should say to my client? That we need to make downgrade of recently updated shop, because versions since 1.7.8.3 don't work, and Prestashop decided to not fix it?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team can someone please answer @grzegorzgit question :pray: 
Thanks in advance!

**Comment by grzegorzgit** [comment]
Ok, I see it is just this way. Thank you @hibatallahAouadni anyway for the info and workaround solution.

**Comment by MatShir** [comment]
@grzegorzgit on the next version, the experimental product page would be the new product page. So your issue should be fixed :)

**Comment by jonasburneika** [comment]
HI @hibatallahAouadni thx for suggestion, but how about multistore? ![image](https://user-images.githubusercontent.com/44444305/177278429-d086c8b4-fb13-44d9-b790-690d2f44dcca.png)

**Comment by MatShir** [comment]
The product page v2 might not be stable for the next version. @PrestaShop/qa-functional could test again and check if it is a regression on the original page ? 🙏

**Comment by sLorenzini** [comment]
hello @grzegorzgit  @MatShir,

I reproduce the issue with PrestaShop version 1.7.8.0/1.7.8.6. But not on 1.7.7.8 & 1.7.6.9 version.
It's a regression.

- PS 1.7.8.6 ❌:
![1786-errorjs-productpageBO](https://user-images.githubusercontent.com/2854834/178296428-3e6c0c42-1f1b-48ef-80a4-f027f80b7b95.png)

- PS 1.7.8.0 ❌:
![1780-errorjs-productpageBO png](https://user-images.githubusercontent.com/2854834/178296460-d69cdae6-f4ae-4c1e-971a-44bc74788048.png)

- PS 1.7.7.8 ✅:
![1778-errorjs-productpageBO](https://user-images.githubusercontent.com/2854834/178297087-656efacf-dda2-4efb-b2e6-e8d400bf0f6d.png)


- PS 1.7.6.9 ✅:  
![1769-errorjs-productpageBO](https://user-images.githubusercontent.com/2854834/178296579-6441c4cf-e106-4aba-a431-22b241ec4b46.png)


I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by NeOMakinG** [comment]
Related to `ps_mbo`, I'll keep the issue opened until we get a response from the MBO team on what we should do in order to fix this!

For reference: https://github.com/PrestaShopCorp/ps_mbo/issues/217

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29307
