### ISSUE TITLE
"Re-display cart at login" feature is not working properly

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#28336]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

**"Shop Parameters > Customer Settings > Re-display cart at login"** feature is not working properly when enabled

Similar issue to unreproduced #23635, but I checked carefully and the bug is alive and with us in PS 1.7.8.5.

### Expected behavior

An abandoned cart should be recovered and displayed properly when a customer re-logins. 

### Steps to reproduce

1. Enable **_Shop Parameters > Customer Settings > Re-display cart at login_**
2. Login as customer and add a product to the cart
3. Logout
4. Login again and see cart is not recovered / shown.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello,

I didn't manage to reproduce your issue with the provided steps and (PS1.7.8.4 ,PHP7.4)

https://user-images.githubusercontent.com/89604350/165296431-68797074-de34-4f2b-b558-2dbb3a2d3f3a.mp4

Did I miss some thing? Could you please check and feedback.

Thanks,

**Comment by gennaris** [comment]
I did some more debug and the problem seems to occur only if the "**statsdata**" module is uninstalled,
so please try reproducing my described scenario by uninstalling the module first.

This way **id_guest** is not recorded in **ps_guest** table and so it is being set = 0 in the **ps_cart** table
even for abandonded carts with a valid **id_customer**.

I see that the **lastNoneOrderedCart** method has been modified [in PS 1.7.7.x](https://github.com/PrestaShop/PrestaShop/commit/e258cf52363a836218601c7fa83a7ece5e7b4da2)
to filter such carts from those to be recovered, but this case was not considered.

**Comment by marwachelly** [comment]
Hello @gennaris ,

Even with the "statsdata" module uninstalled. I wasn't able to reproduce the issue :

https://user-images.githubusercontent.com/89604350/165319567-9a3379ca-c145-4173-93a8-4bfd9f50c80d.mp4

Did I miss some thing? Could you please check and feedback.

Thanks,

**Comment by gennaris** [comment]
Hi @marwachelly 
are you re-testing from a clean DB ? 

You'll need to make sure to have a new cart with **id_guest = 0** in DB to reproduce the issue, so don't reuse the same customer after uninstalling the stats module otherwise an old cart will be recovered.

See id_carts > 9 in my dev DB after uninstalling the stats module, they all have id_guest = 0 :

![2022-04-26_16-26-47](https://user-images.githubusercontent.com/43071148/165323391-c25866d5-cf95-44f0-92e4-9080025605d1.png)

**Comment by hibatallahAouadni** [comment]
Hello @gennaris 

Your issue seems similar to this one #12198
Could you please check it :pray: 

Thanks!

**Comment by gennaris** [comment]
Hello @hibatallahAouadni !
no they are two separate problems.

My issue had been introduced by [this ](https://github.com/PrestaShop/PrestaShop/commit/e258cf52363a836218601c7fa83a7ece5e7b4da2)PR that doesn't take into account that legit customer carts can have **id_guest = 0** when **statsdata** module is not installed.

**Comment by HanaRebaiQA** [comment]
Hello @gennaris 

Despite our efforts, we were not able to reproduce your issue with the provided information. 
I tried to reproduce the issue with 1785 and php 7.4 when the **statsdata** is (enabled, disabled, uninstalled) 

https://user-images.githubusercontent.com/92912932/165967477-d35f5753-b83d-4a4c-afbc-047355a602e0.mp4


It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
I'll close this issue.

Thank you!

**Comment by HanaRebaiQA** [comment]
Hello @gennaris 

As discussed on Slack, i'm opening again this ticket and change it in `TBR`. 
So, could you please put here all the detailed explanations to can try to reproduce it by our team ?

Thank you!

**Comment by gennaris** [comment]
Hi @HanaRebaiQA ,
thank you for your efforts.

Please have a look at [this ](https://dev.prestalia.it/recordings/bug_cart_login.mp4)video where I reproduce the issue

Some additional explanations :

I started from a clean PS environment with sample data, first things I did is to enable _"Re-display cart at login"_
and disable "**statsdata**" module.
(( Disabling the "statsdata" module causes carts to be recorded without ID guest. ))

- I create a SQL query in SQL manager to show the **ps_cart table** for you to check.
- I create a cart and refresh the table, you'll see cart with ID 6 and ID GUEST = 3 , this is because **id_guest**
is retrieved from current session / cookie (and that's the reason why you didn't reproduced the issue before).
- I deleted the cookie (you cannot see this in my video, but you can just start from a new incognito window).
You'll see that next cart I create (1:08) have id_guest = 0.
- I'll checkout to create an account,  I create another cart while logged, I logout and login again and you'll see that
the cart is not recovered and bug is reproduced. 

As you can see from the table, all carts have id_guest = 0. 
After this, you can try to open other incognito windows and you'll reproduce the issue all the time.

Feel free to get in touch if you need more details

**Comment by Miheix** [comment]
> @gennaris

I've been trying to solve this problem for a few days. My version is 1.7.7.5 and I have the Guest mode store. Any contribution is helpful. Thank you!

**Comment by gennaris** [comment]
Hi @Miheix ,
do you have statsdata module disabled ?

Go in **Cart.php** // check **lastNoneOrderedCart** function and remove  the WHERE clause 

`AND c.`id_guest` != 0`

from the query.

See if this fixes the issue.

**Comment by Miheix** [comment]
Hi @gennaris ,
That seems to have fixed the error for me. The statsdata module is activated.
Thank you very much ☺️

**Comment by daresh** [comment]
This line:
AND c.id_guest != 0
seems to be some new change in the Cart class since 1.7.7. Anyone knows why it was introduced? Seems it has some side effects.

**Comment by daresh** [comment]
Found it:
https://github.com/PrestaShop/PrestaShop/pull/15533

**Comment by gennaris** [comment]
Yes, the PR does not take into account that the "statsdata" module is responsible to save the **id_guest** for front office carts and it causes the side effect described (and the reason I opened this issue) for merchants with disabled native stats.

**Comment by daresh** [comment]
I notice this bug also with the statsdata module enabled.

**Comment by daresh** [comment]
@matks - your change in Cart.php class seems to have really bad side effects.

**Comment by matks** [comment]
@daresh I believe you --> https://github.com/PrestaShop/PrestaShop/pull/15533#issuecomment-531296361

**Comment by sLorenzini** [comment]
Hello,

I reproduce the issue with PrestaShop version ps1785 and ps178x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Seb33300** [comment]
I run into this issue today and after digging into it, I found the root cause.

The SQL query that return the cart has the condition `c.id_guest != 0` in `CartCore::lastNoneOrderedCart`

The thing is that the `id_guest` is populated only if the method `Guest::setNewGuest()` is called.
This method update the id_guest value in the cookie, and the cookie is used to populate the cart data.

This method is called by the module `statsdata` in the hook `hookDisplayBeforeBodyClosingTag`
I think thie method should also be called by the core somewhere and not rely on a module.

@hibatallahAouadni n order to reproduce the issue you need to:
1. install a fresh prestashop (the ps_cart table must be empty)
2. disable `statsdata` module
3. clear all your cookies (or open a new private navigation window)
4. login as a customer
5. add an item to the cart (check in the database ps_cart, a new line is created with id_guest = 0)
6. logout
7. login again
8. See the empty cart


If you reproduce the same steps with `statsdata` module enabled, this should work as expected with id_guest not equal to 0

**Comment by Seb33300** [comment]
Just to be clear, the root cause is:

**When the `statsdata` module is disabled, the customer cookie is created without `id_guest`.**

This id_guest is used in different places in prestashop, so the creation of the cookie should be fixed to contains an id_guest even if statsdata module is disabled.

**Comment by Seb33300** [comment]
I created a pull request to fix the issue if you guys want to try it: https://github.com/PrestaShop/PrestaShop/pull/29104

**Comment by Hlavtox** [comment]
I think we don't need any id_guest thing at all. If the customer is registered, even when he is not, he will ALWAYS have proper unique id_customer, tied to the cart. I will have a look on it.

**Comment by mcaldex** [comment]
I'm still encountering this issue on latest version 8.1.7 , freshly installed prestashop.

Please reopen, #29104  doesn't fix the issue at all for me.

**Comment by kpodemski** [comment]
I can confirm that this issue exists on PrestaShop 8.1.7. I'm reopening the issue.

**Comment by kpodemski** [comment]
@MHostinato 

Hmm, I double-checked, and I've had an option for " Re-display cart at login" disabled. When I enabled it, it worked as expected.

If you have an issue, please record a video with preview of your settings and step by step scenario to reproduce it.

**Comment by mcaldex** [comment]
Hi @kpodemski , yes you're right, infact I have this issue only when a Cart gets created for the customer through an external script.
In the script, if I do not set the cart's id_guest property, even if the cart is created and attached to the customer properly and it is visible in Backoffice, the customer won't be able to see it in frontoffice until I set the id_guest.
I think the only solution now would be to create the Guest, and to set the id_guest property. I do not like this solution, but whatever.

However as @Hlavtox pointed out, maybe a more straightforward and clever solution is needed: e.g creating a new boolean property "display_in_fo" on the Cart, which can be used to control the display of the cart in front-office during the login, instead of relaying on the id_guest.

This new property would be set to "true" by default, but set to "false" whenver we need to create "fake cart" in the Backoffice as explained here https://github.com/PrestaShop/PrestaShop/pull/15533#issuecomment-531296361 .
This would be more clean imo.

**Comment by Hlavtox** [comment]
One proper to mitigate this issue is to stop messing and creating carts to make changes in orders in backoffice.

But, that still doesn't resolve a potential issue, that if you create a new cart in backoffice manual order, or programatically, customer can get this cart assigned. He should be assigned only the cart he last worked on.

Maybe we could introduce a property called `id_last_cart` on a Customer object that would keep track of last cart that the customer has worked with in FO.

**Comment by topfuel75** [comment]
The nature behavior of PrestaShop is to replace the previous saved cart with the newly created cart.

I have developed the module **Merge Carts** that fix this issue and merge the carts instead of deleting the old/previous saved cart.

**Get the module** — The module “Merge Carts” is available at:
https://addons.prestashop.com/en/social-login-connect/96287-merge-carts-prevent-lost-shopping-carts-on-login.html

**Demo** — You can try the demo at:
https://www.bulletproof.se/_demos/mergecarts/
(btw, the demo is darn easy to use. It's got some cool features, and it's super easy to create an account and log in).

**Video** — I explain the logic of how PrestaShop handles carts and how the module “Merge Carts” will fix it in this video:
https://youtu.be/mXKQUnPAjw8
