### ISSUE TITLE
Clear all button the filters not showing on mobile 1.7.8.6

### ISSUE THREAD

**Issue by GTriber** [PrestaShop/PrestaShop#28677]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The button "Clear all" in the filter part, on the mobile, isn't displayed

Tried on classic and custom theme. Same issue. "Clear all" showing only after i refresh the whole website. Tried on few devices and Internet browsers, clear the cache. Reset the module, upgrade.

PS: 1.7.8.6
PHP: 7.4

![filter](https://user-images.githubusercontent.com/60825638/172000042-87881792-a5f6-46e4-8d85-48df97c4ef85.jpg)
![filters](https://user-images.githubusercontent.com/60825638/172000202-5a7b44a8-9530-4d5d-8582-15c87fa99fae.png)

### Steps to reproduce

1. Install the module ps_facetedsearch v3.8.0
2. Go to FO with mobile device 
3. Scroll down and click on "All products"
4. Scroll down and clic on "Filter"
5. Check some categories 
6. /!\ The "clear all" button is disabled
7. Clic on "Ok"
8. The selector of filter should be hide, Clic on "Filter" again 
9. /!\You'll see only the "Ok" button
10. Refresh the link 
11. Clic on "Filter" 
12. The "clear all" and "OK" buttons are displayed
13. Clic on "Clear all"
14. The categories should be unchecked
15. /!\ The "Clear all" button is displayed

### PrestaShop version(s) where the bug happened

1.7.8.6 - 1.7.6.5 - 1.7.7.8 - develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.8.0

**Comment by AureRita** [comment]
Hi @GTriber 

Thank you for the reporting Issue.
I reproduced it on 1.7.8.6 as you can see on this video :

https://user-images.githubusercontent.com/100699445/172186284-642a43c2-827e-4b01-9335-16246f55d5b1.mp4

@NeOMakinG I think it's link with the ajax of the website, is it the intended behaviour ? 

@GTriber I will modify your steps to reproduce, could you check it if is something wrong on it ? 

Thanks

**Comment by GTriber** [comment]
@AureRita 
I have add this code to ps_facetedsearch.tpl
`<button data-search-url="{$clear_all_link}" class="btn btn-tertiary js-search-filters-clear-all">
            <i class="material-icons">&#xE14C;</i>
            {l s='Clear all' d='Shop.Theme.Actions'}
        </button>`

Seems working but after refresh, while any filter selected i got 2x same "clear all" buttons.

I don't mind, that "clear all" was there all the time.  But some clients select filters and refresh the website. So the see two buttons.

**Comment by GTriber** [comment]
Any news on that?

**Comment by NeOMakinG** [comment]
I'll take a look into that but we definitly need some product input on that

**Comment by leemyongpakvn** [comment]
@NeOMakinG This issue is related to PrestaShop/PrestaShop/pull/13081

**Comment by NeOMakinG** [comment]
Fixed

**Comment by leemyongpakvn** [comment]
@NeOMakinG In fact this issue may be fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/690, and it is still Open.

**Comment by matks** [comment]
Ping @PrestaShop/product-team we have a PR https://github.com/PrestaShop/ps_facetedsearch/pull/690 and we need your input on the desired behavior

**Comment by hibatallahAouadni** [comment]
@matks should we reopen the issue?

**Comment by mavalentin** [comment]
Hi, I still see this issue on Prestashop 8 and 9, it also happens on the https://demo.prestashop.com
