### ISSUE TITLE
BO - Localization - Local units are not limited, we can add too long units

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28910]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

BO - Localization - Local units are not limited, we can add too long units
![image](https://user-images.githubusercontent.com/16067358/176496473-a4a11eda-d1e7-44b4-98cf-4160eaa47f77.png)

In the BO > Shipping > Edit a carrier > See error in the `Shipping locations and costs` & `Size, weight, and group access` tabs
![image](https://user-images.githubusercontent.com/16067358/176496755-615c9da6-3114-4bad-ab13-d5f49f827533.png)
In the BO > Catalog > Product V1 > Shipping tab 
![image](https://user-images.githubusercontent.com/16067358/176496862-edeb9f89-60d0-4548-ad35-36f5b70454a2.png)

### Steps to reproduce

1. Go to BO > International > Localization 
2. Try to update locate units with too long-expression
3. Click on Save
4. See error: there is no red alert
5. Go to BO > Shipping > Edit a carrier > See errors in the `Shipping locations and costs` & `Size, weight, and group access` tabs
6. See error
7. BO > Catalog > Product V1 > Edit a product > Shipping tab 
8. See error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by aecarlosae** [comment]
Hi there!

### I fixed this bug and improved the implementation  **src/Adapter/Localization/LocalUnitsConfiguration.php**. I used a max length of 10. I still think the length should be a bit lower.

Now **src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml:: prestashop.adapter.local_units.configuration** looks like this:
![image](https://user-images.githubusercontent.com/8390579/177050271-ecb3d827-d21c-4bd5-9e1f-84258fed98f3.png)

Now **LocalUnitsConfiguration** use **Symfony\Component\Translation\TranslatorInterface** and **PrestaShop\PrestaShop\Adapter\Tools**
![image](https://user-images.githubusercontent.com/8390579/177050120-f3afff0b-ed86-4bf8-9004-f090084885be.png)

Now **LocalUnitsConfiguration** has two new properties and a new const like this:
![image](https://user-images.githubusercontent.com/8390579/177050325-3b1f857d-e516-4f4d-a90a-e6f994dddf09.png)

Now **LocalUnitsConfiguration::__construct(...)** looks like this:
![image](https://user-images.githubusercontent.com/8390579/177049939-b569205f-e466-451a-933b-ecb1ea24b2e6.png)

Now **LocalUnitsConfiguration::updateConfiguration(...)** looks like this:
![image](https://user-images.githubusercontent.com/8390579/177049986-8ee68f35-fbfd-4028-88ee-8dc947943541.png)

Now **LocalUnitsConfiguration::validateConfiguration(...)** looks like this:
![image](https://user-images.githubusercontent.com/8390579/177050050-7c0a7bee-dd54-44d2-a82b-c13e31b57e86.png)

Now **src/Adapter/Tools.php** has a new method **strlen()** using the **LegacyTools**
![image](https://user-images.githubusercontent.com/8390579/177050359-3802c373-743f-4708-ab86-f930d7c69a2c.png)

I'll do a PR.

**Comment by ghost** [comment]
Hello @aecarlosae 
Thank you, I already have a PR in progress on this form.
I added a constraint on it.
What do you think about this ? 

https://github.com/PrestaShop/PrestaShop/pull/27533/files#diff-bea60814075cf07f40249801b45f0458c406469d11fe22ad722ec330fc8d7e59R60-R72

**Comment by aecarlosae** [comment]
Excellent  @okom3pom. Sorry if I missed it, but I didn't see a length validation, is it there? or it should be done after your PR is completed?

**Comment by boo-code** [comment]
Still reproduces on 9.2.x, and the constraint @okom3pom pointed at never landed: #27533 was closed without being merged, so nothing from it is in the codebase.

`LocalUnitsType` builds all four fields as bare `TextType` with a label and a help text and **no constraints at all**, and `LocalUnitsConfiguration::validateConfiguration()` only checks that the four keys are present:

```php
public function validateConfiguration(array $config)
{
    return isset(
        $config['weight_unit'],
        $config['distance_unit'],
        $config['volume_unit'],
        $config['dimension_unit']
    );
}
```

So any string reaches `PS_WEIGHT_UNIT` and friends, and is then printed next to the fields of the carrier form and the product shipping tab.

**Prepared** against `9.2.x`: a `Length` constraint of 20 characters on each of the four fields, covered by an integration test that submits each field at the limit and one character over it.

**Where 20 comes from.** Parsing the `<unit>` elements of the 96 localization packs shipped under `localization/`, the longest unit value is **9 characters** — `سانتی‌متر` (centimeter, Persian, which carries a zero-width non-joiner); the next longest is 7. 20 is a little over twice that, which leaves room for an uncommon unit while staying short enough for the form suffixes. It is also the bound I used for the currency symbol on #28911, so the two related limits agree.

@aecarlosae, your 2022 proposal of 10 would be tight for exactly that reason: the longest unit PrestaShop itself ships is 9 characters.

Two things this deliberately does not change: `validateConfiguration()` still only checks that the keys exist, and the fields still accept an empty value. Neither is what this report is about.

The branch is ready; a PR can be opened on request.
