### ISSUE TITLE
Some fixes to do in product-jsonld.tpl and head.tpl

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#30024]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
in the classic theme and in the new hummingbird theme there are some problems about microdata

in **product-jsonld.tpl** it is necessary to do these fixes:
- for brand you need to replace "@type": "Thing" with "@type": "Brand"
- from "offers" it is necessary to remove the three lines about sku, ean13 and mpn because they are at the top into "@type": "Product", and it is the right place where set this data
- add a field, "productID": "{$product.id}", other the rest of references you should add this one
- the line `{if $product.condition == 'new'}"itemCondition": "https://schema.org/NewCondition",{/if}`  is wrong because in some sites $product.condition is void, but the product is new, not refurbished or used, so this condition should be {if $product.condition == 'new' || $product.condition == ''}"itemCondition": "https://schema.org/NewCondition",{/if}
- "availability": "{$product.seo_availability}", doesn't work in some sites I get Preorder instead of InStock, maybe it happens in sites where there is no warehouse management, but if there is not it means that they are always available, so pre-ordering is wrong

for the file **head.tpl** the problem is in the paginations
in a page like page = 2 the canonical url is set with url to page 2 instead should be the first page without parameters, in fact google search console alert me that is present a duplication of contents
this line is not good, because the page number parameters also appear
`<link rel="canonical" href="{$page.canonical}">`

### Steps to reproduce

these problems are present in the classic theme, the errors are reported from google search console

![1](https://user-images.githubusercontent.com/653230/196035154-d9104c00-ff9a-483a-81b7-4d02ddfcf8f1.png)
![2](https://user-images.githubusercontent.com/653230/196035156-adef5416-b1ce-4ed9-9371-eeb57e0f4707.png)

`https://www.velliniilluminazione.com/it/49-lampade-da-tavolo-abat-jour?page=2`

the canonical url should be

`https://www.velliniilluminazione.com/it/49-lampade-da-tavolo-abat-jour`

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment]
Hi @maofree,

> for brand you need to replace "@type": "Thing" with "@type": "Brand"

Good improvement, can you make a PR?

> from "offers" it is necessary to remove the three lines about sku, ean13 and mpn because they are at the top into "@type": "Product", and it is the right place where set this data

These keys are supported by Offer - https://schema.org/Offer, the more info we add, the better.

> add a field, "productID": "{$product.id}", other the rest of references you should add this one

What would you add to this field? Schema is not very clear about what this field should contain, they have a ISBN there, but not everyone sells books - https://schema.org/productID

> the line {if $product.condition == 'new'}"itemCondition": "https://schema.org/NewCondition",{/if} is wrong because in some sites $product.condition is void, but the product is new, not refurbished or used, so this condition should be {if $product.condition == 'new' || $product.condition == ''}"itemCondition": "[https://schema.org/NewCondition",{/if}](https://schema.org/NewCondition%22,%7B/if%7D)

Good catch, should be solved if this key is missing.

> "availability": "{$product.seo_availability}", doesn't work in some sites I get Preorder instead of InStock, maybe it happens in sites where there is no warehouse management, but if there is not it means that they are always available, so pre-ordering is wrong

Already made a PR to fix it - https://github.com/PrestaShop/PrestaShop/pull/29570

> for the file head.tpl the problem is in the paginations
> in a page like page = 2 the canonical url is set with url to page 2 instead should be the first page without parameters, in fact google search console alert me that is present a duplication of contents
> this line is not good, because the page number parameters also appear
> <link rel="canonical" href="{$page.canonical}">
> 

See google documentation - https://developers.google.com/search/docs/advanced/ecommerce/pagination-and-incremental-page-loading

```
Give each page a unique URL. For example, include a ?page=n query parameter, 
as URLs in a paginated sequence are treated as separate pages by Google.

Don't use the first page of a paginated sequence as the canonical page. 
Instead, give each page in its own [canonical URL](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls).
```

**Comment by Maofree** [comment]
Hi
I still don't know how to use github, so I can't do a PR, later I'm going to learn how to use it
a seo agency said me to set the first page to remove the duplications made from the rest of pages, because they have the same content (meta title, meta description, title, H1, description and it was alerted by search console), I'll try some tests

thanks
bye

**Comment by sallemiines** [comment]
Hello @maofree ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment]
Friendly reminder @PrestaShop/committers :pray:

**Comment by Hlavtox** [comment]
@hibatallahAouadni I explaind everything in my comment. :)

**Comment by Maofree** [comment]
Hi @Hlavtox 
there is this error
https://github.com/PrestaShop/PrestaShop/issues/33776
I think it is big, because I get it from some websites each time I upgrade ps_events (ps_accounts)

**Comment by boo-code** [comment]
Going through the six points against the current themes, every one of them is settled, either implemented or answered by @Hlavtox at the time. Nothing here looks outstanding.

| point | state |
| --- | --- |
| `"@type": "Thing"` → `"Brand"` | **done in both themes** |
| remove `sku` / `ean13` / `mpn` from `offers` | declined at the time: those keys are valid on `Offer` |
| add `productID` | not adopted; the question about what it should hold was never answered |
| `itemCondition` when the condition is empty | **resolved by omitting the key**, which is what was proposed in the thread |
| `availability` returning Preorder | fixed by #29570 |
| canonical on paginated pages | declined, per Google's own pagination documentation |

On the two that were actual code changes:

`classic-theme` on `develop` and `hummingbird` on `2.x` both emit

```smarty
"brand": {
  "@type": "Brand",
```

and hummingbird goes a step further than the request, using `Brand` when the product has a manufacturer and `Organization` when it falls back to the shop name, which is the more accurate pair since a shop is not a brand.

For the condition, neither theme emits `itemCondition` when `$product.condition` is empty. Classic only writes it for `new`, `used` and `refurbished`; hummingbird gates the whole key on `!empty($product.show_condition) && !empty($product.condition)`. So an empty condition produces no key rather than a wrong one, which is the outcome described in the thread as the right answer.

Suggest closing. If the `productID` question is still wanted, it is the one point here that never got an answer, and it would be clearer as its own issue with a decision about what the field should contain.
