### ISSUE TITLE
One Click Upgrade 4.15.0.: It's not possible to create a PHP session and no new version available.

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#30658]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you update the One Click Upgrade module to 4.15.0 on (At least Prestashop version 1.7.8.8) we get an error that it's not possible to create a PHP session.
This happends on multiple shops and we have no clue what is wrong. The module also doesn't see Prestashop 8.0.0

https://watch.screencastify.com/v/Nh8ObM9wUOgHlhgjgPnN

### Expected behavior

It should open a PHP connection.

### Steps to reproduce

1. Module list
2. Upgrade One Click Upgrade to 4.15.0
3. Configure the module
4. See the PHP connection error

This latest version adds this type of error which prevents the use of the module to update prestashop. Without this change in the plesk it would not be possible to update.
From what I know the problem is on all websites using plesk of every hosting, but with cpanel I have no problems.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4 8.0 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade 4.15.0

**Comment by sallemiines** [comment]
Hello @venditdevs 

Thanx for reporting the issue.

could you please provide more info
cause  I didn't manage to reproduce the issue with the provided infos ! and can you provide some screenshots or a screen record ?

Please check and feedback.

Thanks!

**Comment by JBWModules** [comment]
For me it asks for mainainance mode even though its activated (see screenshot) and does not find a new version (Modul is upgraded to 4.15.0)
![grafik](https://user-images.githubusercontent.com/47666330/209408338-9957fbcf-b989-45ab-baa2-d92cb24b2d69.png)

**Comment by kpodemski** [comment]
Hello everyone 

At the moment, there's only local archive option or local directory option available if you want to upgrade to PrestaShop 8.0.

You can see the process there:
https://youtu.be/SBz7lApJ_pA?t=1063

The difference is that you don't need to use your own distribution, you can use release from PrestaShop's GitHub

**Comment by alpinecare** [comment]
Hello everyone I also have the problem (screenshot) a bug?
P.S I have not modified anything except the update of update click
PS 1.7.8.8 PHP 


Informations du serveur : Linux #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.4.33

Limite de mémoire : 512M

Temps maximal d'exécution : 7600

Taille max. pour envoi de fichiers : 16M

![Screenshot 2022-12-24 at 18-43-05 1-Click Upgrade 1-Click Upgrade • Myalpine Shop](https://user-images.githubusercontent.com/78073201/209446474-a849d2d8-7180-4ee7-8d2e-cd0daba4159f.png)

**Comment by reiner56** [comment]
hi i have the same problem. 

Ubuntu Server 22.04 with Plesk

![FFFE0D3E-3DE7-4194-9817-11B1928BB790](https://user-images.githubusercontent.com/34655358/209538854-9729d9b1-a981-4db8-9b70-e269da0d03db.png)
![C0A14882-179E-4D91-A9F0-17DABE73808D](https://user-images.githubusercontent.com/34655358/209538857-a10eb22c-c161-451b-b42b-218d6f882fc7.png)

**Comment by reiner56** [comment]
![C34AE2AB-9CDE-419A-87DA-48D945904223](https://user-images.githubusercontent.com/34655358/209539377-750ef206-c1d0-4a0d-9871-0841503e1b24.png)

**Comment by venditdevs** [comment]
> Hello @venditdevs
> 
> Thanx for reporting the issue.
> 
> could you please provide more info cause I didn't manage to reproduce the issue with the provided infos ! and can you provide some screenshots or a screen record ?
> 
> Please check and feedback.
> 
> Thanks!

Hello,

Thanks for your reply. Unfortunatelly we don't have any more information regarding this issue, there are no clear/other errors than the message that it is not possible to create a PHP session. No info on serverside either. Screenshot is posted by another person above. With this error it;s not possible to upgrade Prestashop with a local archive either.

**Comment by totti240282** [comment]
Hello, i have same problem on 1 site.

**Comment by totti240282** [comment]
I have resolve with this settings

![immagine](https://user-images.githubusercontent.com/3179572/209644162-ace053b7-4df2-4130-a7eb-427ee5508ea6.png)

**Comment by reiner56** [comment]
the problem was in Ubuntu Plesk Open_basedir set to none and the error is gone
![Captura de pantalla 2022-12-27 a las 8 38 23](https://user-images.githubusercontent.com/34655358/209668370-02f66005-3972-4470-b4e7-bc53c3eca462.png)
![Captura de pantalla 2022-12-27 a las 8 38 45](https://user-images.githubusercontent.com/34655358/209668377-e601b0ae-d99a-4829-ab9f-25dfb0e05b3a.png)

**Comment by vnt** [comment]
Hello, i have same problem on 2 sites

> It's not possible to create a PHP session.

> PrestaShop requirements are not satisfied.

**Comment by venditdevs** [comment]
The problem is not fixed in combination with an Apache interface/server. It's allready on false, true or none won't make any difference.

**Comment by jzahariadis** [comment]
> the problem was in Ubuntu Plesk Open_basedir set to none and the error is gone ![Captura de pantalla 2022-12-27 a las 8 38 23](https://user-images.githubusercontent.com/34655358/209668370-02f66005-3972-4470-b4e7-bc53c3eca462.png) ![Captura de pantalla 2022-12-27 a las 8 38 45](https://user-images.githubusercontent.com/34655358/209668377-e601b0ae-d99a-4829-ab9f-25dfb0e05b3a.png)

is it a safe solution? I have the same issue in prestashop 1.7.8.7 it occured when i upgraded 1-Click Upgrade module to v4.15.0.
maybe something wrong with 1-Click Upgrade? does it include the right path?

**Comment by HartLarsson** [comment]
> the problem was in Ubuntu Plesk Open_basedir set to none and the error is gone ![Captura de pantalla 2022-12-27 a las 8 38 23](https://user-images.githubusercontent.com/34655358/209668370-02f66005-3972-4470-b4e7-bc53c3eca462.png) ![Captura de pantalla 2022-12-27 a las 8 38 45](https://user-images.githubusercontent.com/34655358/209668377-e601b0ae-d99a-4829-ab9f-25dfb0e05b3a.png)

this fix could be aproblem in a shared hosting, because that paramenter cannot be changed.

**Comment by HanaRebaiQA** [comment]
Hello @venditdevs 

Thanks for your report.
I was unable to reproduce your issue when upgrading from 1788 using php7.3 and 7.4.

Here is the information about my system : 

- **Server information**: Linux # 62~20.04.1 - Ubuntu SMP
- **Server software version**: Apache/2.4.51 (Debian)
- **PHP version**: 7.3.33 / 7.4.27
- **Memory limit**: 1024M
- **Max execution time**: 30
- **Upload Max File size**: 10000M


**Upgrade from PS1788 with php 7.3** : Only the maintenance error 

**Upgrade from PS1788 with php 7.4** : An error related to `memory_limit ` which is fixed by configuring it

![image](https://user-images.githubusercontent.com/92912932/209928470-1f2db267-43c4-4f69-8aef-c9474816fbda.png)

![image](https://user-images.githubusercontent.com/92912932/209928497-47cf9c4b-33e3-4681-9afb-b15a33b59e1e.png)

https://user-images.githubusercontent.com/92912932/209928549-c57377bb-2e84-443b-bb9b-d633f0ea41c4.mp4

So, i'll close this issue.

Thank You!

**Comment by vnt** [comment]
Hello,
I have this error: 

> It's not possible to create a PHP session.

And it is different from

> PHP memory_limit is inferior to 256 MB

Hana, your solution, does not solve my problem

**Comment by stact** [comment]
For Plesk User I found a safe fix :) 

Append to open_basedir
`{:}/var/lib/php/session`

The value `{WEBSPACEROOT}{/}{:}{TMP}{/}{:}/var/lib/php/session`

Hope it helps! And thank you @reiner56 ^^

**Comment by RichardM2019** [comment]
the cause of the error is due to the upgrade of One Click Upgrade from v4.14.2 to v4.15.0.
Everything worked perfectly on the website where I deliberately did not include One Click in the upgrade. after upgrading from Onle Click from 4.14.2 to 4.15.0, the problems appeared at that site as well.
My question: how can I downgrade One Click Upgrade again to 4.14.2?
(And yes. when you set open-basedir to "None" it works too, but I am afraid for security issues)

**Comment by RichardM2019** [comment]
> For Plesk User I found a safe fix :)
> Append to open_basedir `{:}/var/lib/php/session`
> The value `{WEBSPACEROOT}{/}{:}{TMP}{/}{:}/var/lib/php/session`
> Hope it helps! And thank you @reiner56 ^^
*****
thanks for sharing, but this didn't work for me

**Comment by kpodemski** [comment]
@RichardM2019 you can change the name of the module directory, autoupgrade to autoupgrade-off or something, just to see if the site is working properly without a module

**Comment by reiner56** [comment]
hello, i contacted Plesk support and they told me that they need the path to correct the error.

see comment from plesk

<img width="815" alt="Captura de pantalla 2023-01-01 a las 12 00 37" src="https://user-images.githubusercontent.com/34655358/210177164-540566e2-5ee1-47fa-8433-a970b4f26433.png">

**Comment by RichardM2019** [comment]
> hello, i contacted Plesk support and they told me that they need the path to correct the error.
> 
> see comment from plesk
> 
> <img alt="Captura de pantalla 2023-01-01 a las 12 00 37" width="815" src="https://user-images.githubusercontent.com/34655358/210177164-540566e2-5ee1-47fa-8433-a970b4f26433.png">

****
Also many thanks for this! Great follow up, and I will check it.
These answers help a lot of people. 
(And no clue why someone already closed this topic a few days ago "as no issue" and probably thought that was the best help. But that in itself is another topic and probably irrelevant for now)

**Comment by Maofree** [comment]
Hi
I confirm this problem is present after the upgrade to the version v4.15.0
and on all website with plesk
the fix can be done from the php settings on plesk changing from,
{WEBSPACEROOT}{/}{:}{TMP}{/}
to
none
to upgrade prestashop and then return to {WEBSPACEROOT}{/}{:}{TMP}{/}

@HanaRebaiQA can you reopen this post? if not I need to create a new one to fix this problem on the module

bye

**Comment by Kerami82** [comment]
The same problem after upgrade to the version v4.15.0  :(. I want to upgrade to 1.7.8.8, and I can't :(

**Comment by Tomi1444** [comment]
Same here.

**Comment by venditdevs** [comment]
> Hello @venditdevs
> 
> Thanks for your report. I was unable to reproduce your issue when upgrading from 1788 using php7.3 and 7.4.
> 
> Here is the information about my system :
> 
> * **Server information**: Linux # 62~20.04.1 - Ubuntu SMP
> * **Server software version**: Apache/2.4.51 (Debian)
> * **PHP version**: 7.3.33 / 7.4.27
> * **Memory limit**: 1024M
> * **Max execution time**: 30
> * **Upload Max File size**: 10000M
> 
> **Upgrade from PS1788 with php 7.3** : Only the maintenance error
> 
> **Upgrade from PS1788 with php 7.4** : An error related to `memory_limit ` which is fixed by configuring it
> 
> ![image](https://user-images.githubusercontent.com/92912932/209928470-1f2db267-43c4-4f69-8aef-c9474816fbda.png)
> 
> ![image](https://user-images.githubusercontent.com/92912932/209928497-47cf9c4b-33e3-4681-9afb-b15a33b59e1e.png)
> 
>  upgrade.4.15.mp4 
> So, i'll close this issue.
> 
> Thank You!

Hello [HanaRebaiQA](https://github.com/HanaRebaiQA)

Please do not close this issue if it's not resolved. We are not the only one with this problem. There are no errors or other usefull errors present to help solve this problem. As you can see, more people have problems with this issue so it's a larger problem than "i can no reproduce it". 
We have 170 shops here and all the shops have the same issue. IF it's server related (Apache) than it has to be a configuration issue, we have 30 servers and none of our users are limited for resources. The chance that it's a configuration issue is small, we work with Apache and i see the same issue occurs on other platforms.

open_basedir solution doesn't work here either.

**Comment by bocianl** [comment]
The same here. The issue is related to open base dir. On our hosting for security reasons, we got this off. 

Version v4.14.2 works.

**Comment by RichardM2019** [comment]
@HanaRebaiQA 
Hello HanaRebai QA https://github.com/HanaRebaiQA
Are you reading all the  comments/ problems?

Can you reopen this issue, which in principle should not be closed at all?
We are losing money and/or have a security issue when our (business) websites are not up to date

**Comment by HanaRebaiQA** [comment]
Hello @RichardM2019 

Sorry for the late answer. I was off from the office the last period.
I'll open it again to see the problem again!

ping @PrestaShop/qa-functional Could someone try to reproduce it?

Thanks!

**Comment by Snippy30** [comment]
I have the same problem. Would like to change to version 8, because my provider switches off PHP 7.4 from 1.2.2022.
Provider is Stratos.

Errorcode: It's not possible to create a PHP session.

Aftzer Install 1-Click Update-Modul.

**Comment by KungMatsW** [comment]
I also have the same problem in 3 shops. My 4:th shop does not show the session problem but it still runs 1-click upgrade 4.14.
The first 3 runs 4.15 and has the problem.
I also need to upgrade to 8.0 for all 4 shops and I need it now.

... and ...
All my 4 shops runs on the same server so this is not a server problem. It's related to the 1 click upgrade 4.15.

I have also tryed the tips above from @HanaRebaiQA or @venditdevs to expand the memory but that does not help,

**Comment by jelkose** [comment]
Hello,

I'm experiencing the same issue, using a Strato hosting package like @Snippy30.

Trying to update my PrestaShop version 1.7.8.6 (One Click Upgrade Version XXXX)

It seems like the function `test_sessions()` from class `ConfigurationTest` is called. This checks if the `session.save_path` from the php.ini, which is "2;/var/tmp" in my case, is a writable path. And here's the problem "2;/var/tmp" is not a path. 

So this seems to be a configuration problem (as I can't see PresaShop setting this value anywhere). As it is neither possible for me to change the value in the php.ini, nor to change it via the .htaccess file, I have added the line `ini_set("session.save_path", null);` to the top of the index.php file in my admin directory. This seems to be a workaround for anyone who cannot change the value in any other way.

Best regards,
Jelko

**Comment by KungMatsW** [comment]
Hello @jelkose 
I tryed you idéa adding that row to the top of admin index.php but I get ERROR 500.
Are you sure you wrote the correct row?

**Comment by jelkose** [comment]
I did not include the ; (semicolon) at the end, maybe that's Your problem.

**Comment by KungMatsW** [comment]
No, I have tryed with semicolon, but still ERROR 500

**Comment by KungMatsW** [comment]
> ini_set("session.save_path", null);

And just to be sure.
You're telling me to put the row at the very top of my admin/index.php file like this.
```
<?php
ini_set("session.save_path", null);
```

**Comment by BarbUk** [comment]
The issue is caused by 

https://github.com/PrestaShop/autoupgrade/blob/353707f00af1c02878fd193a2c2a526ea1dfeb91/classes/UpgradeSelfCheck.php#L597-L598 

that call https://github.com/PrestaShop/PrestaShop/blob/7aabf1874574aa565e6a3e8dd619701178cbb8c5/classes/ConfigurationTest.php#L401-L408.

With an open_basedir configured without the `session.save_path`, the `session.save_path` dir will not be writable.

The code should not check if the dir is writable, but if a session can be created or if a session already exists (using the autoupgrade module from the backoffice, a session should already exists).

**Comment by KungMatsW** [comment]
@BarbUk
But what can we do to fix it? ... I don't understand this.
It is beyond my knowledge

**Comment by Snippy30** [comment]
@jelkose After entering these lines in index.php in the admin directory, the error message was gone. I could now install the V8. After the installation, I can no longer access the "BackOffice". I changed the PhP version to 8.0. Nevertheless it doesn't work. If I go to the admin directory of my HP, the login for the back office comes with a user name and password. If I enter this, only the penguin appears and I can only go back.
Sorry if I post this here. Doesn't really belong on this topic.

**Comment by BarbUk** [comment]
@KungMatsW 

> @BarbUk
> But what can we do to fix it? ... I don't understand this.

If you have an open_basedir set, you can temporarily configure it to allow php to access your session.save_path.

For the code, prestashop should fix the test, not you.

**Comment by matks** [comment]
Thank you @BarbUk for the nice tip ;)

**Comment by KungMatsW** [comment]
I dont understand what open_basedir is.
Where and how can I change it?
I have the shops on shared servers and I can't change anything on the web host. Only my own Prestashop files

**Comment by matks** [comment]
@KungMatsW it is a setting of the PHP engine running on your server

https://www.php.net/manual/en/ini.core.php#ini.open-basedir

If you can modify nothing on the web host, you will probably not be able to use the above workaround

**Comment by Hlavtox** [comment]
@PrestaShop/committers This should be fixed on our side, I get the same error on our server and sessions work completely fine otherwise.
I have read somewhere that the way how Plesk is configured is the correct way.

**Comment by venditdevs** [comment]
@HanaRebaiQA 

One Click Upgrade want's to open "session.save_path" as a path, but it's not a writable path for modules.. (something like that), maybe that helps.

![image](https://user-images.githubusercontent.com/14218917/212613828-705f2518-bfe9-46fd-bb09-8de758afec05.png)

**Comment by Hlavtox** [comment]
It is a path, but only a system can write there. The app cannot write into that directory because of openbasedir restrictions, it cannot go UP out of prestashop directory.

**Comment by JanMiddelkoop** [comment]
Double-posting here to make sure this gets attention:

Despite it's name, session.save_path should not be treated as a path.

When you use Redis as a session backend (which is a good idea for performance), your PHP session.save_path is likely set to something like "tcp://127.0.0.1:6379/?prefix=prestashop". The check fails and produces incorrect results.

Presumably the same would happen when using Memcached as session backend, or any backend other than the default (file-based) sessions.

**Comment by RichardM2019** [comment]
As this is taken too long and the cause is clear, I have contacted Prestashop Support.
( I just wanted to be sure that the developer is aware of the problems and that he/she will fix it)
They will escalate it to the concerned department / developers to take proper action.
I think that is good news :-)

**Comment by ghost** [comment]
Ich habe den Fehler auch. Zuerst habe ich mit einer älteren Version versucht auf 1.8 upzudaten. Leider blockiert der 1-Click-Updater dies mit der Meldung, dass er zwar eine aktuelle Version ist aber es noch eine Aktuellere geben soll. Hab dann jetzt die ganz aktuelle Version runtergeladen und bekomme den vielfach gezeigten Fehler. Auch ich bin Strato-Kunde und gebe hier mal ein Bild von den Serverdaten und von der Fehlermeldung. 
![fehler](https://user-images.githubusercontent.com/119105495/214837603-f1ce78c4-86a8-43ee-bada-7aa7afa17f52.png)
![mysql](https://user-images.githubusercontent.com/119105495/214837618-3900c39b-5edd-4d88-a3eb-c463226fd28e.png)
![server](https://user-images.githubusercontent.com/119105495/214837628-669d064e-7f3f-4a35-9184-2bb920253916.png)

**Comment by ghost** [comment]
And again in English, sorry:

I have the error too. First I tried to update to 1.8 with an older version. Unfortunately, the 1-Click-Updater blocks this with the message that although it is a current version, there should be a more current version. Have then now downloaded the very latest version and get the multiple error. I'm also a Strato customer and I'll give you a picture of the server data and the error message here.

**Comment by ghost** [comment]
I have now installed the 1-click updater on a laragon test server in the current prestashop 8 version. The php session error no longer exists there. something must have changed in the session behavior in the latest prestashop version that was not there in the old version.

**Comment by Hlavtox** [comment]
I checked it and the test scenario is the same since at least 1.6.

I think that LAMP stacks began to be configured in a safer way. 👍

**Comment by KungMatsW** [comment]
Have anybody heard any news abuit this?

**Comment by ghost** [comment]
Unfortunately, no. I reinstalled the whole shop manually and still have problems with the one click updater. the second check can't really take that long... embarrassing for a shop system like prestashop

**Comment by venditdevs** [comment]
@KungMatsW 

no news so far. It's 2 weeks since they submitted a fix but they're still waiting on a second confirmation.

[https://github.com/PrestaShop/PrestaShop/pull/31053]

@Dexter-Brings 
Embarrassing indeed, just like all the "I can't reproduce" reactions followed by closing the issue/bug while more people are responding with the same problem.

**Comment by RichardM2019** [comment]
totally agree. And I can tell you that prestashop 8.0 has the same problem.

**Comment by Hlavtox** [comment]
Even the 1.6 has the same problem. Upgrade process will be fixed by an improved session check in https://github.com/PrestaShop/autoupgrade/pull/561.

If you don't want to wait, just change this piece of code in `classes/ConfigurationTest.php` and you can upgrade. 😎

**Comment by KungMatsW** [comment]
> Even the 1.6 has the same problem. Upgrade process will be fixed by an improved session check in [PrestaShop/autoupgrade#561](https://github.com/PrestaShop/autoupgrade/pull/561).
> 
> If you don't want to wait, just change this piece of code in `classes/ConfigurationTest.php` and you can upgrade. 😎

But does this presuppose that you can change it yourself on your own server or on the web host?
Most of us who have this can't do it, so I don't understand how I could solve it.

**Comment by Hlavtox** [comment]
The check in autoupgrade module calls to the Prestashop core to check the session. So, even if we fix it now in the core for next Prestashop version 8.0.2, you still would not be able to upgrade.

So, we also need to implement this improved check into the autoupgrade module itself, so everyone with older versions can upgrade. This will be included in the next version of autoupgrade module - probably 4.15.1.

So, if you **don't want to wait,** you can change this now. If you can't, you will have to wait.

**Comment by KungMatsW** [comment]
So when can we expect the 4.15.1 to be released?

**Comment by kpodemski** [comment]
@KungMatsW 

There's no date yet. You can use the fix right now, you don't need to wait:
https://github.com/PrestaShop/autoupgrade/pull/561/files

**Comment by KungMatsW** [comment]
Is this what you tell me to do? Row 582 in my script image
![image](https://user-images.githubusercontent.com/118338163/217211620-ba96e527-c97c-4b9f-85f7-87602b259f1e.png)

**Comment by Hlavtox** [comment]
@KungMatsW Remove the previous lines.

```
if (!class_exists(ConfigurationTest::class)) {
            return true;
        }

        return ConfigurationTest::test_sessions();
```
and keep only
`return in_array(session_status(), [PHP_SESSION_ACTIVE, PHP_SESSION_NONE], true);`

**Comment by KungMatsW** [comment]
So like this? .... It seems to work :)
![image](https://user-images.githubusercontent.com/118338163/217212933-1adbfba2-d409-4ca9-bc61-9f5984abbdae.png)

**Comment by tenenick** [comment]
hi guys, Same issue here trying to upgrade form 1.7.8.7 to 1.7.8.8 with 1-Click Upgrade v4.15.0
Solution from Hlavtox did the job.
Thanks a lot mate. You saved my day 👌👍🎉

**Comment by matteolavaggi** [comment]
Why this issue is closed when redis session save handler is not yet supported? O_o

**Comment by Hlavtox** [comment]
@matteolavaggi Did you test a develop branch of autoupgrade module?

**Comment by matteolavaggi** [comment]
No, I only test the last release version. With 1.14 session check is ok but
you can't upgrade because the version is not ok, with 1.15 session check is
bug so you can't upgrade.
Result , you can't upgrade ps in anyway. I can't force to ask myself what
kind of dev environment are used from the maintenance team to test the
release? A redis php session handler is a common setup, now we are in 2023,
not in 1993 ^^ why only test it with file session path storage?!

I think critical module like this must be released more carefully, actually
there is no way to update prestashop with the module.


Il Lun 6 Mar 2023, 12:12 Daniel Hlavacek ***@***.***> ha
scritto:

**Comment by Hlavtox** [comment]
@matteolavaggi I don't understand. Why do you complain that the issue is closed when you didn't even test the version that will be released? The issue should be fixed and a new release of autoupgrade is in process.

> With 1.14 session check is ok but you can't upgrade because the version is not ok, with 1.15 session check is
> bug so you can't upgrade.
> I think critical module like this must be released more carefully, actually
> there is no way to update prestashop with the module.

The upgrade module is using the same check for many years since 1.6 and it worked fine until now, it's not a problem that would come with a new version. Every PR and every release is always tested by people from QA team, it is released carefully.

**Comment by matteolavaggi** [comment]
Issue must be closed WHEN fix is released, not before O_o

Il giorno lun 6 mar 2023 alle ore 12:41 Daniel Hlavacek <
***@***.***> ha scritto:

**Comment by kpodemski** [comment]
@matteolavaggi, that's actually true ;-) it has been closed automatically after merging PR

**Comment by RainManCZE** [comment]
SOLVED without any changes in code 
I've just added `php_value session.save_path none` at the begining of .htaccess

**Comment by hibatallahAouadni** [comment]
@kpodemski & @Hlavtox should we close the issue? as it seems related to php configuration :thinking:

**Comment by RichardM2019** [comment]
> @kpodemski & @Hlavtox should we close the issue? as it seems related to php configuration 🤔

If you read the massages you will see the cause of the error is due to the upgrade of One Click Upgrade from v4.14.2 to v4.15.0.

**Comment by Hlavtox** [comment]
@hibatallahAouadni It's fixed, but autoupgrade 4.16 has not been released yet. Not sure why @kpodemski decided to reopen the issue. 😛

**Comment by hibatallahAouadni** [comment]
Reminder: please close this issue when the upgrade module v4.16 is released :wink:

**Comment by MatissJekabsons** [comment]
Ok. I have the same issue and disabling open_basedir does not help too.

**Comment by Frits1969** [comment]
> 

thanks... this works for me for the update form1.7.8.8 to 1.7.8.9

**Comment by Maofree** [comment]
Hi
right now I've seen that with LITESPEED there is the same problem
and the fix using with Apache doesn't work in the plesk

open_basedir =>> none

to solve this problem it is necessary to apply this fix
https://github.com/PrestaShop/autoupgrade/pull/561/files
return in_array(session_status(), [PHP_SESSION_ACTIVE, PHP_SESSION_NONE], true);

it is necessary to release the 4.1.16 with this fix

**Comment by Hlavtox** [comment]
Version released with a fix

**Comment by matteolavaggi** [comment]
Hi, i'm experiencing the same problem also with the autoupgrade module with the session fix on php 7.4 and litespeed with redis configured as a session handler:


`public function isPhpSessionsValid()
    {
        return in_array(session_status(), [PHP_SESSION_ACTIVE, PHP_SESSION_NONE], true);
    }
`

`session.save_handler = redis
session.save_path = "tcp://redb01.europe-west1-b.c.webserver-307508.internal:6379?auth=MYAUTHCODE`


If i try to login on back office i'll get this error:
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/046115db-4e68-4c85-a242-633d246b5ad9)

To find a more meaningful log i need to force debug mode false and get a standard 500 error:

ps1788.matteolavaggi.it] [STDERR] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Core Error: SessionHandler::open(): Cannot call default session handler in Unknown:0\nStack trace:\n#0 {main}\n\nNext Symfony\Component\Filesystem\Exception\IOException: Failed to create "yaml": mkdir(): Permission denied in /var/www/html/ps1788.matteolavaggi.it/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:104\nStack trace:\n#0 /var/www/html/ps1788.matteolavaggi.it/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(676): Symfony\Component\Filesystem\Filesystem->mkdir()\n#1 /var/www/html/ps1788.matteolavaggi.it/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php(124): Symfony\Component\Filesystem\Filesystem->dumpFile()\n#2 /var/www/html/ps1788.matteolavaggi.it/src/Core/Util/File/YamlParser.php(92): Symfony\Component\Config\ResourceCheckerConfigCache->write()\n#3 /var/www/html/ps1788.matteolavaggi.it/src/Core/Addon/Theme/Theme.php(43): PrestaShop\PrestaShop\Core\Util\File\YamlParse in /var/www/html/ps1788.matteolavaggi.it/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 104\n


LSPHP 7.2 and 7.4 share the same session config, but with php7.2 i'm not getting the error, this happen only with php7.4
