### ISSUE TITLE
Translation string for "new" in BO not working

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#30916]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are two separate strings for the string ‘New’:

1. Front office: ‘New’ (=Nouveau) in `Shop.Theme.Global`
2. Back office: ‘New’ (=Neuf) in `Admin.Global`

![image](https://user-images.githubusercontent.com/113511191/212926519-b3b7d98a-1d9d-4f22-bb1c-b0b62c27d743.png)

![image](https://user-images.githubusercontent.com/113511191/212926535-97cac5ee-a768-43b0-a748-41f633d367b4.png)

 
Both strings are translated differently in 8+, but they both appear as “nouveau”, no matter the context. The translations are correct on Crowdin, but the translated strings on the software are not working correctly.

This is not the case in 1.7. I have not tested the bug in other languages.

I'm editing the string to place it under the right translation domain `Admin.Global`, instead of `Shop.Theme.Global`

### Expected behavior

Strings are supposed to be translated like this:

1. Front office: "Nouveau"
2. Back office: "Neuf" 

### Steps to reproduce

1. Create a new product, and make it visible on your store
2. Check if the label "new"is translated properly ("nouveau" in FO, "neuf" in BO)

### PrestaShop version(s) where the bug happened

8.0.0, 8.0.1

**Comment by l-delin** [comment]
Linked PR --> https://github.com/PrestaShop/PrestaShop/pull/30917

**Comment by sallemiines** [comment]
Hello @l-delin 

Thanx for reporting the issue.
I reproduce you issue with : 
**PS 1.7.8.7** OK 

![image](https://user-images.githubusercontent.com/31663369/212952857-9083756c-db90-4ff0-971f-2c4b1920016f.png)

![image](https://user-images.githubusercontent.com/31663369/212953012-9fa1909c-86e8-41f6-a0ea-13b6b5086217.png)

**PS 8.00** NOK 

![image](https://user-images.githubusercontent.com/31663369/212953181-965324a4-16c7-4c2a-962f-8abb538fc18f.png)

![image](https://user-images.githubusercontent.com/31663369/212953241-71c4c2ac-9943-4267-9dca-4c61fe52b93d.png)


Could you please check if this [issue 17455 ](https://github.com/PrestaShop/PrestaShop/issues/17455) is same to yours ? 

@l-delin Please check and feeback ! 

Thank you

**Comment by l-delin** [comment]
Hello @sallemiines Yes, it's the same problem, but contrary to issue https://github.com/PrestaShop/PrestaShop/issues/17455, there's already two existing strings, but the wrong one is being used because of an error in the code. 

Ping @Julievrz

**Comment by Julievrz** [comment]
Hi,

There are 2 strings:

One is in **Admin.Global** and it refers to the product's condition (in French, it should be "Neuf").

The other one is in **Shop.Theme.Catalog**. It's the label that indicates that a product was just added ("Nouveau" in French). 

There's an error in the code -> The domain **Shop.Theme.Catalog** was used instead of **Admin.Global** in the back office. So, when we change the translation for the Shop.Theme.Catalog string, the back office's translation changes as well. 

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php#L200

So the problem really comes from the translation domain that is used in the back office. 

There's nothing more we can do on Crowdin.

(@MatShir FYI)

**Comment by Julievrz** [comment]
Also, the issue is also reproduced in V8 based on your screenshot. You should have "Neuf" on the BO and "Nouveau" on the FO but you have "Nouveau" on both. 

I also reproduced it 
<img width="282" alt="Capture d’écran 2023-01-18 à 14 45 39" src="https://user-images.githubusercontent.com/70583503/213187521-b0dc15ba-17c4-4459-b904-589d4376dbca.png">

<img width="402" alt="Capture d’écran 2023-01-18 à 14 45 55" src="https://user-images.githubusercontent.com/70583503/213187586-26071a4f-9e17-45c3-8c6e-4f7f16f62e3f.png">

This is because the same translation domain is used for both strings. 

So the translation domain should be modified in the BO.

**Comment by SharakPL** [comment]
> You should have "Neuf" on the BO and "Nouveau" on the FO but you have "Nouveau" on both.

IMO it should be the same on both. All 3 BO options for product condition are supposed to show how this product will be described in FO so they should use strings from `Shop.Theme.Global`. Although it would probably be better to allow user custom configuration of these conditions, like order states instead of restricting to just 3 predefined options.

**Comment by Julievrz** [comment]
> > You should have "Neuf" on the BO and "Nouveau" on the FO but you have "Nouveau" on both.
> 
> IMO it should be the same on both. All 3 BO options for product condition are supposed to show how this product will be described in FO so they should use strings from `Shop.Theme.Global`. Although it would probably be better to allow user custom configuration of these conditions, like order states instead of restricting to just 3 predefined options.

Hello, 
The string in the back office indicates the product's condition. Here, "New" means that the product is brand new, in its original packaging. 
It has nothing to do with the label in the front office, that appears when you add a new product to your store. 
You could have a "Used" product with the "New" label on the front office. On the front office, the "New" label is only here to tell your customers that the product was recently added.
Even though it's the same word in English, it doesn't have the same meaning. 

Also, the back office strings should be in the 'Admin' domain and the ones from the front office should be in the 'Shop' domain. See https://devdocs.prestashop-project.org/8/development/internationalization/translation/translation-domains/

**Comment by mflasquin** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31148

**Comment by dominiqueblanc** [comment]
Hello Everyone,

I'm new here, so apologize if I'm doing wrong but... I didn't saw any comment about the Packs (grouped products).

However, the mistake 'New' (meaning 'New on site' = 'Nouveau' and not 'New' as a condition vs. 'Used' or 'Refurbished') is apparently not fixed.

Thanks and Best regards

**Comment by MatShir** [comment]
Hi @DomShop,
The issue is fixed on the 8.0.2. On which version are you ?

**Comment by dominiqueblanc** [comment]
Hi @MatShir,

Thank you for your reply.

I'm on 8.0.2 and I have translated to make it obvious.
It seems that it still goes wrong with the grouped products (packs).

Here are the pics...

![Prestashop 8 0 2 - Pack - fr](https://user-images.githubusercontent.com/129511652/229480695-320331f2-8b7b-4c98-8edc-285b6749eff8.png)

![Prestashop 8 0 2 - Pack - en](https://user-images.githubusercontent.com/129511652/229480718-138eb835-8e17-489d-bffa-767bf74ce780.png)

![image](https://user-images.githubusercontent.com/129511652/229480816-c13e35d1-e77b-4036-a9e0-eada3316df07.png)

Thank you in advance.
BR

**Comment by MatShir** [comment]
Thanks, we will have a look

**Comment by l-delin** [comment]
Hello @DomShop,

I tried reproducing your issue on multiple versions of PrestaShop (8.0.3 and 8.1) but to no avail. Translations appear correctly for me:

![image](https://user-images.githubusercontent.com/113511191/231782392-2c566d70-b334-4f99-9328-c7ddbcae6ce8.png)

![image](https://user-images.githubusercontent.com/113511191/231782442-cd951034-e52d-4e03-af5b-8a92c5808cd8.png)

![image](https://user-images.githubusercontent.com/113511191/231782505-edb0c355-df13-4770-b814-770b50a48ff4.png)

Could you try updating your translations and let me know if that works? 

Thank you!

**Comment by dominiqueblanc** [comment]
Hi @l-delin ,

Thank you for your feedback.

To reproduce that issue, I have re-installed Prestashop on a new domain (to do so leads me to an original version, with no custom).
The installed version is 8.0.3, theme classic, PHP version 8.0.27

What I get is, on the product demo_20...
![image](https://user-images.githubusercontent.com/129511652/232203879-a6d706b1-60fd-4fdd-b63d-b261216ad71c.png)

and on the pack (product demo_21) :
![image](https://user-images.githubusercontent.com/129511652/232204374-e9aaafac-da39-4af7-b6cc-49ea8f904af6.png)

With no custom, as you can see, this issue is not fixed : the expected (on the product flag meaning 'new on sale' or 'just added') should be ' Nouveau '. That's ok.
BUT, as a condition, it should be ' Neuf ', which is apparently not ok.

Your pics showed FO (Nouveau) and BO (Neuf).

My BO does the same and that's fine (e.g. product demo_21)
![image](https://user-images.githubusercontent.com/129511652/232207172-e9fcd275-7933-4a8f-b207-c99b9184b709.png)

But, to compare, could you please show the entire FO product page (as customers does and as I shown above) to check the display of both flag and condition ?

By my side, it seems that there is a mismatch between BO and FO.
As a condition, FO uses the `Shop.Theme.Catalog` and not the `Admin.Global`.

However, you shown (and it gave me the clue) that the product condition is managed and translated in `Admin.Global` to appears correctly in BO.

Then, 'New' (=Neuf) as a condition, correctly translated in BO, has to go all the way !

Which means that the FO needs to be feed from the `Shop.Theme.Catalog`, but also linked/related to the `Admin.Global` , in order to speak the same, from BO to FO.

Obviously, still focus on the condition, what is called 'New' (=Neuf) in BO, is called 'New' (=Nouveau) in FO and that's wrong.

If I select 'Used' (=Utilisé) in BO, it appears correctly 'Used' (=Utilisé) in FO.
![image](https://user-images.githubusercontent.com/129511652/232207688-975ca197-f17b-414c-be43-7a1b17fea62c.png)
But it's an easy going because 'Used' (as well as 'Refurbished') ONLY relates to the condition and still stands in `Shop.Theme.Catalog` while 'New' (=Neuf) has been removed in #31148.

If I go translate 'New' in 'Nouveau', in `Shop.Theme.Catalog`, that will be applied on both `product flag` and `condition` because the specific use of this word 'new' is missing in the BO International ->Translations, in the `Shop.Theme.Catalog` section, while it appears twice on the product page and means two different things.

Therefore, to fix this issue, a specific 'New' (=Neuf) has to be added in translations in the `Shop.Theme.Catalog` to be able to finally split the meanings and the display of 'new' on the flag vs. condition.

Best regards

**Comment by dominiqueblanc** [comment]
Hi again,

In order to check the conditions (and where it stands exactly, just in case), I looked for it in the `Admin.Global`.

![image](https://user-images.githubusercontent.com/129511652/232273071-63fa7e93-6a6e-4c3f-ba97-0cfebc35aa39.png)
![image](https://user-images.githubusercontent.com/129511652/232272954-2dee9cf1-0d34-43ff-ab29-86bb232a334d.png)

I found 'New' (=Neuf)... 
![image](https://user-images.githubusercontent.com/129511652/232274531-044da2c6-2d44-4042-9e40-41ae35ba19b8.png)


...but not 'Used' nor 'Refurbished'.

Used : the Global section is empty
![image](https://user-images.githubusercontent.com/129511652/232273402-137d8a67-b507-456e-a606-1051a1950558.png)

Refurbished : no result 
![image](https://user-images.githubusercontent.com/129511652/232273561-034bd178-838f-42b0-b0da-789160584938.png)

However, the product conditions stands in a dropdown in BO and it suggests that the dropdown is powered by the same source... (`Admin.Global`)

I hope it helps.

Best regards
