### ISSUE TITLE
Hook trigger not implemented

### ISSUE THREAD

**Issue by harman-jack** [PrestaShop/PrestaShop#30943]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

the actionUpdateQuantity Hook does not trigger when updating stock through the stock_availables web service API.
I saw many PrestaShop users are using the ERP system and they are using web service APIs for stock syncing from ERP to Prestashop. On another side, they are also using the marketplace integration module as well which depends on Hooks for stock syncing.

### Expected behavior

I don't know why it is not implemented yet.

but it is better if the actionUpdateQuantity hook triggers every time when updating stock through web service API or any other medium. it will improve the developer experience as well as the user's experience.

### Steps to reproduce

Try to update stock through the stock_availables web service API.

and check that the actionUpdateQuantity hook is not triggered.

### PrestaShop version(s) where the bug happened

1.7

**Comment by HanaRebaiQA** [comment]
Hello @harman-jack 

Thanks for your report.

Could you please provide us more information about the steps to reproduce with a screen-shot or a screen-record end the clear version on which you have reproduced your issue?

**Comment by Hlavtox** [comment]
@harman-jack Can you check on develop? I have added these triggers to the new code.

**Comment by harman-jack** [comment]
@HanaRebaiQA 

PS version: 1.7.8.6

Stock update through product edit from Prestashop catalog, video attached:

https://user-images.githubusercontent.com/55911839/213634531-a2ddb052-94cc-400d-8363-d7d6b6bec059.mp4

Stock update through stock_availables web service API, video attached:

https://user-images.githubusercontent.com/55911839/213634726-b66bcd17-0493-4676-8a8f-94cdfb429123.mp4

please let me know if you need anything else.

**Comment by florine2623** [comment]
Hello @harman-jack ,

I don't have access to a module similar to yours.
Is there a way to check directly from the database ? or with this [module](https://github.com/PrestaShop/ps_qualityassurance) ?

Waiting for your feedback ^^

**Comment by harman-jack** [comment]
Hello @florine2623 ,
let me share the module:

[arise_prestashop_cedconnector_2.0.17.zip](https://github.com/PrestaShop/PrestaShop/files/10517520/arise_prestashop_cedconnector_2.0.17.zip)

**Comment by hibatallahAouadni** [comment]
Hello @harman-jack 

Could you please check on develop as @Hlavtox asked you 🙏 
It seems your issue is fixed on develop.
Waiting for your feedback.

Thanks!

**Comment by harman-jack** [comment]
Okay @hibatallahAouadni 

hello @Hlavtox,
Could you please let me know where you have added those triggers?

Thanks!

**Comment by harman-jack** [comment]
Hello @Hlavtox, Gentle reminder!

**Comment by harman-jack** [comment]
Hello @Hlavtox 

I have checked it with the latest realized version 1.7.8.8, but it still not working

Updating quantity from Prestashop product edit page:

https://user-images.githubusercontent.com/55911839/222665050-04a9f5ff-8612-47ee-bde5-86251d9fefec.mp4

Updating quantity from web service API:

https://user-images.githubusercontent.com/55911839/222665887-7b34475a-37f9-4c25-b084-42837ba9c390.mp4

I hope you understand the problem.

Thanks!

**Comment by Hlavtox** [comment]
@harman-jack Try with 8.1 beta

**Comment by hibatallahAouadni** [comment]
Hello @harman-jack 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
