### ISSUE TITLE
module psgdpr v1.4.3 crash with lot of customers ( like 78980 records)

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30963]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With a very big number of record of customers ( in my case 78.980) when you enter in the module to operate the module crash badly:

in console:
![image](https://user-images.githubusercontent.com/16102074/213552693-5aa283a5-edda-4868-aeed-70975e0fabbe.png)

in the interface to manage customers that ask to remove their data appear:

![image](https://user-images.githubusercontent.com/16102074/213552830-1580f760-d1b0-4325-af0c-b3543cf4338d.png)

if you visit cutomer activities tab, seems is not developed for managing tons of records (no pagination on query) and quite crash my installation interface:

[i don't publish a screen for privacy]

### Expected behavior

Because GDPR will collect tons of information, expecially on big and long time installation all the interface and query must be developed to load only paginated data.

### Steps to reproduce

1. fill your customer table of 79.000 or more record.
2. simulating they accept privacy and policy and so on
3. now go to gdpr module and you will see in console JS error, database crashing and interface to search customers crashed too.

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by HanaRebaiQA** [comment]
Hello @HartLarsson 

Thanks for your report.
Could you please send us a screen-shot of your issue ?

**Comment by dpatou** [comment]
Hey @HanaRebaiQA it seems to me screenshots were added to the issue.

@HartLarsson (or anyone else looking for a way to "uncrash" psgpdr) if you're still looking for it, the crash is caused by the GDPRLog::getLogs() call at module config load, it loads too much data into datatables and one part (template rendering) or the other (client side datatable rendering) ends up crashing, depending on your server/client hardware and your history volume.

All pathes below refer to within the psgdpr module.

The call is here : https://github.com/PrestaShop/psgdpr/blob/dev/psgdpr.php#L468
I "fixed" it by editing this call to an empty array.

A better (but still not ideal) fix would be to limit the query by (using LIMIT maybe) in classes/GDPRLog.php (getLogs method)

Durable fix would be to have a datatables data requested by page in ajax and not trying to load the whole history each time and introduce pagination. It would require an ajax log querying admin controller aswell as adapting the DataTable instanciation in views/js/back.js

https://datatables.net/reference/option/serverSide and https://datatables.net/reference/option/ajax for future reference.

**Comment by HartLarsson** [comment]
> Hey @HanaRebaiQA it seems to me screenshots were added to the issue.
> 
> @HartLarsson (or anyone else looking for a way to "uncrash" psgpdr) if you're still looking for it, the crash is caused by the GDPRLog::getLogs() call at module config load, it loads too much data into datatables and one part (template rendering) or the other (client side datatable rendering) ends up crashing, depending on your server/client hardware and your history volume.
> 
> All pathes below refer to within the psgdpr module.
> 
> The call is here : https://github.com/PrestaShop/psgdpr/blob/dev/psgdpr.php#L468 I "fixed" it by editing this call to an empty array.
> 
> A better (but still not ideal) fix would be to limit the query by (using LIMIT maybe) in classes/GDPRLog.php (getLogs method)
> 
> Durable fix would be to have a datatables data requested by page in ajax and not trying to load the whole history each time and introduce pagination. It would require an ajax log querying admin controller aswell as adapting the DataTable instanciation in views/js/back.js
> 
> https://datatables.net/reference/option/serverSide and https://datatables.net/reference/option/ajax for future reference.

i agree that the problem was there... better asi i told too to show data paginated and datatable (i use in many projects) works great for that

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

Do you have the same issues on your other shops with other versions (newer version like 1788 or 800)?
Your issue is related to Performance and I think we should improve the store's performance 😉 
Please check and feedback.

Thanks!

**Comment by dpatou** [comment]
Hi @hibatallahAouadni 
Regardless of PS version, the module will still have the issue in any shop with enough customers having (at least) given their consent (which is required for purchasing), considering the code of this module (independant of prestashop's version) is :

https://github.com/PrestaShop/psgdpr/blob/dev/classes/GDPRLog.php#L158-L161
(all user actions including consents are loaded at once without pagination, date filter, or record limit)

And all loaded at once in datatable : 
https://github.com/PrestaShop/psgdpr/blob/dev/views/js/back.js#L70-L79
because all loaded in html :
https://github.com/PrestaShop/psgdpr/blob/dev/views/templates/admin/tabs/customerActivity.tpl#L28-L56

**Comment by seederp2p** [comment]
This happens to me on chrome but works fine on firefox.

I've 150K customers.

What do you need to troubleshoot this further?

**Comment by HartLarsson** [comment]
> This happens to me on chrome but works fine on firefox.
> 
> I've 150K customers.
> 
> What do you need to troubleshoot this further?

westill speaking about have more then 70.000  customers recorded in GDPR table (not simple customers of the store), because there is no pagination as explained by @dpatou 

and the problem is not related to browser brand but how is managed the list in html (Frontend)

**Comment by seederp2p** [comment]
This is still present making the module unusable .

@hibatallahAouadni

**Comment by seederp2p** [comment]
> GDPRLog::

Basically one of the suggestion would be to change

'logs' => GDPRLog::getLogs(),
to
'logs' => [],

If I need to remove customer data, will it remove everything?

@dpatou

**Comment by dpatou** [comment]
> > GDPRLog::
> 
> Basically one of the suggestion would be to change
> 
> 'logs' => GDPRLog::getLogs(), to 'logs' => [],
> 
> If I need to remove customer data, will it remove everything?
> 
> @dpatou

This is exactly what I did and information removal still works great. You just don't see history any more in the module conf screen (that table where you saw customers adding/removal of information history).

If you really need to pull it out due to customer request, a couple of database queries can do the trick

**Comment by dpatou** [comment]
Alternatively, you could also replace the SQL query in classes/GDPRLog.php method "getLogs" by

```
SELECT *
    FROM `' . _DB_PREFIX_ . 'psgdpr_log` where request_type <> 1
```

(added "where" clause), it would only show you "non additions". In my DB the data spread is like this
```
count(*)	request_type	
286569	1	
322	2	
47	3	
82	4	
```

Which should display non-1s fine

**Comment by seederp2p** [comment]
Wouldn't it be better to definitively correct the module and release a fix? Since this is the official GDPR module, it is basically useless for the common user who has a store with a lot of logs... :)

**Comment by dpatou** [comment]
I'm pretty sure anyone is free to open PRs, there are for sure numerous issues that need more attention than this one.

My thought is that most users with a store with lots of logs (like mine) are likely to generate enough revenue to have one of their IT staff (or an hired contractor) apply one of the fixes listed here or even open a PR here for a better fix if it hinders their activity.

[This comment](https://github.com/PrestaShop/PrestaShop/issues/9757#issuecomment-1542064200) says it better than I do (although I would like to see issues fixed by other people like anyone else ;) )

**Comment by HCS83** [comment]
Hello,
For information, on PS 1.7.5.1 with RGPD module 1.4.3 and only 257 customers in the DB, i have the same issue, so i guess it is not a matter of number of customer in DB as it is mention in this thread.
Regards,

**Comment by seederp2p** [comment]
Today I got an update to 2.0.2 and this issue still exists...

**Comment by matks** [comment]
@seederp2p Apologies, we disabled the distribution of 2.0.2 but looks like a config mistake made it re-distributed. Fixed again.

**Comment by seederp2p** [comment]
> @seederp2p Apologies, we disabled the distribution of 2.0.2 but looks like a config mistake made it re-distributed. Fixed again.

Herm...

Should I use 2.0.2 or downgrade?

Also in a different environment, it still shows the 2.0.2 upgrade available in the backoffice.

**Comment by seederp2p** [comment]
> @seederp2p Apologies, we disabled the distribution of 2.0.2 but looks like a config mistake made it re-distributed. Fixed again.

Still showing up:

![image](https://github.com/PrestaShop/PrestaShop/assets/3126847/35e1a6f3-41b9-4ea1-9687-65b36105bc06)

**Comment by matks** [comment]
> Still showing up:


It's coming back 😫  https://api-addons.prestashop.com/?format=json&iso_lang=en&iso_code=FR&version=8.1.6.0&method=listing&action=native

**Comment by seederp2p** [comment]
> > Still showing up:
> 
> It's coming back 😫 https://api-addons.prestashop.com/?format=json&iso_lang=en&iso_code=FR&version=8.1.6.0&method=listing&action=native

This is back.

It's showing 2.0.2 available for upgrade....

**Comment by boo-code** [comment]
The crash described here is structurally gone in psgdpr 2.x, and the reason is worth stating because it also answers @HCS83's report of the same symptom on only 257 customers.

In 1.4.3 the back office page built a list of every customer. In 2.0.3 there is no such path at all: `src/Controller/Admin/CustomerController::searchCustomers()` is the only way customers reach that screen, it returns HTTP 400 when the search phrase is empty, and it delegates to core's `SearchCustomers` query. `SearchCustomersHandler` caps that query at 50 results, so nothing on the page grows with the size of the customer table.

That cap also bounds the one part that would otherwise scale badly: the controller calls `Order::getCustomerNbOrders()` once per row, which is a query per customer, but at most 50 of them per search rather than one per customer in the shop.

`src/Repository/CustomerRepository` only exposes `findCustomerNameByCustomerId()` and `findCustomerIdByEmail()`, so there is no "fetch them all" left anywhere in the module either.

The later part of this thread is a different problem - 2.0.2 reappearing in the back office update list after being pulled. That is the addons listing rather than the module code, and the current version on `dev` is 2.0.3.
