### ISSUE TITLE
Order and Customer summary broken when Invoices are off

### ISSUE THREAD

**Issue by lim3ra** [PrestaShop/PrestaShop#31157]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, I noticed a problem on Presta version 1.7.8.8. 

When you turn off invoices - stats for orders and customers are showing "0" per each order
![image](https://user-images.githubusercontent.com/26142543/216174094-8bb4578d-a4a0-43ea-b588-a8326aab917d.png)

### Expected behavior

When you turn Invoices back on - it works fine
![image](https://user-images.githubusercontent.com/26142543/216173883-3e2e5d33-e72c-42d0-8945-20b1d7973cf3.png)
![image](https://user-images.githubusercontent.com/26142543/216173964-895f721b-ed59-4c82-8ff8-6b119ea5380f.png)

### Steps to reproduce

1. In the Orders/Invoices menu, turn off invoices
2. Make an order, pay with whatever method you want (I tested custom modules: P24, BlueMedia, PayOnDelivery made by Presta and built-in bankwire module)
3. Make sure the order has proper status (paid, marked as finished, etc)
4. Go to order details, basket summary shows 0 
![image](https://user-images.githubusercontent.com/26142543/216174478-a0a03f84-906d-4151-9001-264126870287.png)
5. Go to customer list/summary, shows 0
![image](https://user-images.githubusercontent.com/26142543/216174543-6cd23f1f-53f8-4f99-906f-03b091b982d3.png)

### PrestaShop version(s) where the bug happened

1.7.8.X

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment]
Hi @lim3ra, just today I merged a PR that will improve this for next Prestashop 9 - https://github.com/PrestaShop/PrestaShop/pull/31104.

It will show different value that will never be 0. ;-)

**Comment by lim3ra** [comment]
> Hi @lim3ra, just today I merged a PR that will improve this for next Prestashop 9 - #31104.
> 
> It will show different value that will never be 0. ;-)

Cool thanks for the info, do you know how this might be connected with the invoices switch?

**Comment by Hlavtox** [comment]
I think it's not filling up the order_payment table and not updating total_paid_real in orders table. 👍 Try to check it out

**Comment by lim3ra** [comment]
This is not solved, table Customer view still shows wrong values.

**Comment by Hlavtox** [comment]
@lim3ra Let's reopen so we keep track, so the numbers are zero on the customer list? Everywhere else it's fine?

**Comment by lim3ra** [comment]
> @lim3ra Let's reopen so we keep track, so the numbers are zero on the customer list? Everywhere else it's fine?


The customer view list is broken and statsbestcustomers module seems to be affected as well.

![image](https://user-images.githubusercontent.com/26142543/219609666-930e2d07-3174-4447-aba2-48a081f2264d.png)

Dashboard>Stats>Best customers>Summary spent (last column)

**Comment by Hlavtox** [comment]
@lim3ra Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/31440 ;-)

**Comment by lim3ra** [comment]
Hey @Hlavtox 

I have tested #31440 , it works perfect, thanks!

Btw I noticed statsbestcustomers module uses its custom query to get these stats:

IFNULL((
				SELECT ROUND(SUM(IFNULL(op.`amount`, 0) / cu.conversion_rate), 2)
				FROM `' . _DB_PREFIX_ . 'orders` o
				LEFT JOIN `' . _DB_PREFIX_ . 'order_payment` op ON o.reference = op.order_reference
				LEFT JOIN `' . _DB_PREFIX_ . 'currency` cu ON o.id_currency = cu.id_currency
				WHERE o.id_customer = c.id_customer
				AND o.invoice_date BETWEEN ' . $this->getDate() . '
				AND o.valid
			), 0) as totalMoneySpent,

**Comment by Hlavtox** [comment]
@lim3ra Cooool!

This should work, and we will even solve a potential issue with conversion rates, because it was using a conversion rate from currency and not from order.

Can you make a PR for the module if it works?
```
IFNULL((
				SELECT ROUND(SUM(IFNULL(o.`total_paid_tax_incl`, 0) / o.conversion_rate), 2)
				FROM `' . _DB_PREFIX_ . 'orders` o
				WHERE o.id_customer = c.id_customer
				AND o.invoice_date BETWEEN ' . $this->getDate() . '
				AND o.valid
			), 0) as totalMoneySpent,
```

**Comment by lim3ra** [comment]
> @lim3ra Cooool!
> 
> This should work, and we will even solve a potential issue with conversion rates, because it was using a conversion rate from currency and not from order.
> 
> Can you make a PR for the module if it works?
> 
> ```
> IFNULL((
> 				SELECT ROUND(SUM(IFNULL(o.`total_paid_tax_incl`, 0) / o.conversion_rate), 2)
> 				FROM `' . _DB_PREFIX_ . 'orders` o
> 				WHERE o.id_customer = c.id_customer
> 				AND o.invoice_date BETWEEN ' . $this->getDate() . '
> 				AND o.valid
> 			), 0) as totalMoneySpent,
> ```

yup, it did the trick

I will push changes to module later today

cheers!

**Comment by HanaRebaiQA** [comment]
Hello @lim3ra 

Thanks for your report.
I was able to reproduce your issue on PS1788 and PS8.1.0_beta using the same steps to reproduce and when the Invoices is disabled. But, I was unable to reproduce it on PS1778.

**PS1788 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/220887204-bffa2a05-8f98-4383-b1a6-058ec852f0cb.png)

![image](https://user-images.githubusercontent.com/92912932/220887228-e3b32060-1651-4586-877d-20d6375a298a.png)

https://user-images.githubusercontent.com/92912932/220887833-1ef09d6a-5943-49b5-891a-2b08e8e18c1d.mp4

**PS8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/220887284-237fbe59-a69d-4fc9-ba0d-3385287841d9.png)

**PS1778 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220887245-cdc9cb2a-5a8d-4915-81fb-514edd01e9bf.png)

https://user-images.githubusercontent.com/92912932/220887580-8e64eeb3-f2df-4e78-89bb-45fcfe1f7145.mp4


Indeed, it's a regression! 

I'll add this to the debug backlog so that it's fixed.

Thanks for your PR!

**Comment by yavorr** [comment]
i have the same issue on presta 8.1.4 - there is a solution?
Its not working even when i enabled invoices ;/

**Comment by lim3ra** [comment]
I can confirm problem is back in 8.1.7

**Comment by Progi1984** [comment]
The module has not been release in 2.0.5
