### ISSUE TITLE
Native popover incompatibility/conflict

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#32851]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Chrome now have/use `popover` attr: https://developer.chrome.com/blog/introducing-popover-api/

The issue here is that product page and maybe others use `popover` attr to display an info tooltip. Then user agent styles for popover hides or adds a black border around the elements with `popover` attr
Macos
<img width="349" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/194784/815029b2-4f98-47ec-936f-755bc4b38e2b">
On windows I see black border
![image](https://github.com/PrestaShop/PrestaShop/assets/194784/f0165939-0198-4877-b01f-99ef73610066)
Source code:
![image](https://github.com/PrestaShop/PrestaShop/assets/194784/4bf4bb57-0206-4a78-ab94-5565f81da07d)
Implemented in:
https://github.com/PrestaShop/PrestaShop/blob/6ed7395027ce33310c40a4917c457a79cfe64702/src/PrestaShopBundle/Form/Admin/Product/ProductSeo.php#L108

Browser styles:
<img width="199" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/194784/b133fd18-6219-4e4b-93e6-e42f7c6ab43e">

### Expected behavior

- The black border should not be displayed OR the label should not be hidden
- An attribute used by the browser should not be used should not be used by Prestashop to avoid conflicts

### Steps to reproduce

1. Have chrome 114
2. Edit product and go to seo tab
  - Meta-title and meta-description  are hidden
  - OR Meta-title and meta-description have black border

### PrestaShop version(s) where the bug happened

1.7+

**Comment by florine2623** [comment]
Hello @davidglezz ,

Thanks for the report.
I have reproduced the issue on 1.7.8.9 and 8.0.4 with Old product page.
It has been fixed with New Product Page on those versions.

And it cannot be reproduced on 8.1.0 and develop.

https://github.com/PrestaShop/PrestaShop/assets/16019289/fbe37e59-7963-46b4-b44b-df0286d03a98


So I will close the issue.

**Comment by dnkhack** [comment]
@florine2623 Fresh install PS 8.1.0, Chrome 114 in the Ukrainian language.

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/123455a2-d014-424d-91a7-6d19990bce19)

**Comment by davidglezz** [comment]
Thanks!

**Comment by dnkhack** [comment]
@davidglezz Hello, you can try my temporary solution while PS dev doesn't fix it. 

https://github.com/dnkhack/fixgooglepopover

First Enable the module in the module configuration.

**Comment by carcam** [comment]
I don't think we have to fix this. That border seems like an accessibility improvement similar to the "focus". Removing it makes really hard to people browsing the page with a keyboard to know where they are.
