### ISSUE TITLE
Module Status Button Not Reflecting Correct Status

### ISSUE THREAD

**Issue by agroundworld** [PrestaShop/PrestaShop#33063]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Recently upgraded to PS 8.1.  I noticed that when changing or configuring the status buttons on modules, the status button is not reflecting the correct status. 

### Expected behavior

The correct status on the module configuration button should be reflected.

### Steps to reproduce

1. Navigate to Module Manager
2. Select a module where Enable Mobile and Disable Mobile are available.
3. Select Enable Mobile (Status button will reflect Disable but should reflect Enable Mobile)
4. Select Disable Mobile (Status button will reflect Disable but should reflect Disable Mobile)
![Module button 1](https://github.com/PrestaShop/PrestaShop/assets/75636570/75cb5fd7-02a9-499c-b47f-9380e9d7db4d)
Enable Mobile selected in above screen shot.

![Module button 2](https://github.com/PrestaShop/PrestaShop/assets/75636570/06e281a1-0726-4745-90d2-e132c06e9ab3)
Disable Mobile selected in above screen shot.

![Module button 3](https://github.com/PrestaShop/PrestaShop/assets/75636570/f641a07b-de5d-4d70-883b-2cb6b95ff533)
Correct status not reflected.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Lester WIlliams

**Comment by AureRita** [comment]
Hi @agroundworld  ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.0 and not with the version 8.0.4 as you can see : 

[Untitled_ Jul 3, 2023 4_43 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/2660e32d-f441-42c5-a18e-eee0e77d3032)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jolelievre** [comment]
Not sure but may be related to this PR https://github.com/PrestaShop/PrestaShop/pull/29512

**Comment by Hlavtox** [comment]
@agroundworld @AureRita This is a correct behavior that has been fixed on 8.1.

Enable on mobile/Disable on mobile should be in the dropdown.

**Comment by agroundworld** [comment]
If this is working as designed might I suggest that it is confusing. The status of Disable is not the same as Disable Mobile. If you have selected Disable Mobile and what is showing is Disable then you have no way of knowing what the status of the module truly is.  Perhaps you should reconsider the previous implementation.  Thanks. Lester Sent from Mail for Windows From: Daniel HlavacekSent: Wednesday, July 19, 2023 4:32 AMTo: PrestaShop/PrestaShopCc: agroundworld; MentionSubject: Re: [PrestaShop/PrestaShop] Module Status Button Not Reflecting Correct Status (Issue ***@***.*** @AureRita This is a correct behavior that has been fixed on 8.1.Enable on mobile/Disable on mobile should be in the dropdown.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> Virus-free.www.avast.com

**Comment by Hlavtox** [comment]
@agroundworld Hi, yes, they are separate properties. The only thing different is that this function is in the dropdown, like it was in Prestashop 1.7.8 and lower. It was a mistake that it was the primary button in PS 8.

This feature was removed for Prestashop 9, so it's really not worth to spend time on it now. 🙏

**Comment by agroundworld** [comment]
So to clarify, the Disable/Enable Mobile functionality is being removed in PS 9? If so, then I agree that time is better spent on other issues.

**Comment by Hlavtox** [comment]
@agroundworld Yes, it was removed from v9. It was kinda obsolete feature... 

- Everyone should have the same experience.
- You cannot specify the breakpoint that would decide what is mobile and desktop.
- You resize/rotate the screen and still get what was loaded.
- It simplifies the code and loading of the module.
