### ISSUE TITLE
PS 9 Symfony mailer not working with port 587 (only 465)

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#36663]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PS 9 implementing Symfony Mailer, PS 8 Swift Mailer.

PS1.7-PS8 with port 587 with TLS working well.
PS9 port 587 isn't working, I investigated, port 465 is working..
**If eshop owner update PrestaShop from version 8 to 9, SMTP will stop working.** (because other port definition)
Huge BC... After update will eshop owner totally lost with this.

I tested more mail providers, same problem. Not related to mail service.

There is changed connection string:
```
PS 8 connection string:
tcp://smtp.seznam.cz:587
PS 9 connection string
ssl://smtp.seznam.cz:587
```

### Expected behavior

Working same like in PS8

### Steps to reproduce

1) BO - tools - emails
2) fill SMTP credentials (TLS + port 587)
3) compare PS8 vs PS9 (PS8 will works, PS9 doesn't work)

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1+8.2+8.3

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by Hlavtox** [comment]
@ShaiMagal The connection transport should look like this - `smtp://user:pass@smtp.example.com:25` - or maybe it's a different thing than the connection string?

**Comment by ShaiMagal** [comment]
@Hlavtox Like i already wrote in task description:
Connection strings are different for PS8 and PS9
_PS 8 connection string (using tcp://):
tcp://smtp.seznam.cz:587
PS 9 connection string (using ssl://)
ssl://smtp.seznam.cz:587_

If you change in PS9 to 465:
ssl://smtp.seznam.cz:465

it's working.

But, if some customer is using port 587 + TLS from PS8 and update PS to PS9, his emails will not working... and customer will be confused way. I think he has no change to detect ,there is "problem" with port.
Imagine this situation :-D And a lot of complains

I am not sure, how this work exactly, so someone should investigate this, if there is not any problem with implementation...

**Comment by Hlavtox** [comment]
Ping @jolelievre @kpodemski for investigation

**Comment by kpodemski** [comment]
My understanding is that since:

> Mail SSL encryption was dropped
> When we migrated from Swift Mailer to Symfony Mailer, we noticed that SSL support was not an option in ESMTP transport. SSL is an old and outdated encryption type, and for security reasons, it will no longer be allowed.
> The remaining choices are “TLS encryption” or “No encryption”.

If one uses an outdated choice, we should update it to TLS + 487 port inside the upgrade script for PrestaShop 9. Would that make sense?

**Comment by Hlavtox** [comment]
@kpodemski It's not TLS vs SSL, 587 is a normal supported port for TLS.

See https://www.mailgun.com/blog/email/which-smtp-port-understanding-ports-25-465-587/#subchapter-3

> When an email client or outgoing server is submitting an email to be routed by a proper mail server, it should always use SMTP port 587 as the default port.
> This port, coupled with TLS encryption, will ensure that email is submitted securely and following the guidelines set out by the IETF.
> All Mailgun Send customers should consider using port 587 as their default SMTP port unless you're explicitly blocked by your upstream network or hosting provider.

https://www.cloudflare.com/learning/email-security/smtp-port-25-587/

>  Today, SMTP should instead use port 587 — this is the port for encrypted email transmissions using SMTP Secure (SMTPS).

**Comment by ShaiMagal** [comment]
We must investigate it before release of PS9, it's blocker issue.

**Comment by kpodemski** [comment]
Ping @ibahloul-ps @jolelievre 

@ShaiMagal is available if you need more details

**Comment by ShaiMagal** [comment]
Yes, if you will need some more information, let me know. But I think, I wrote everything important in first post.

**Comment by kpodemski** [comment]
Ping again @ibahloul-ps @jolelievre

**Comment by ShaiMagal** [comment]
Any news here?

**Comment by Hlavtox** [comment]
Friendly ping again @ibahloul-ps @jolelievre, this is an important issue, since most ordinary hosting servers now can't send mail using sendmail.

**Comment by Hlavtox** [comment]
Investigated and found this comment - https://github.com/symfony/symfony/issues/34846#issuecomment-580190302

> To be clear, you should use 465, true to use SSL to connect or 587, false to connect withou SSL and upgrade via STARTTLS. Any other combination won't work. The code was buggy, fixing it here

I removed the $isTls forced parameter from the construct in `classes/Mail.php` and the error disappeared. And it seems to work with port 465 also. I think that the encryption can be removed from settings completely. It will automatically use the correct one depending on the port it seems.

```
$transport = (new EsmtpTransport(
                    $smtpServer,
                    $smtpPort
                ))
                    ->setUsername($smtpLogin)
                    ->setPassword($smtpPassword)
                ;
```

**Comment by Maofree** [comment]
Hi
I got this problem right today with a new prestashop 9.0.2
setting TLS with 465 works

**Comment by maximo88** [comment]
Same problem on Prestashop 9.1.3.

To get a clean native SSL route (⁠ssl://...:465⁠) in PrestaShop 9, you had to "deceive" the panel by selecting the TLS option. Therefore 587 port can’t be used.

**Comment by internauten** [comment]
The project [https://github.com/internauten/InternautenMix](https://github.com/internauten/InternautenMix) includes a PrestaShop module called internautengraph. This module hooks onto the actionEmailSendBefore hook and supports the Microsoft Graph API and SMTP with STARTTLS. Both are supported by Office 365 and other providers.

Perhaps someone could integrate this directly into Prestashop.

**Comment by boo-code** [comment]
Opened #42197 against `9.1.x`, implementing what @Hlavtox found in April.

Confirming the diagnosis against the Symfony we ship (mailer 6.4.40): the third argument of `EsmtpTransport` selects implicit TLS, not STARTTLS, and `Mail` forced it to `true` for any setting other than `off`. Since the back office offers only `None` and `TLS`, there was no combination that produced STARTTLS at all - which is why the only way to a working setup was to pick TLS and move to 465, as @maximo88 describes.

Symfony already resolves this when the argument is left unset:

```php
if (null === $tls) {
    if (465 === $port) { $tls = true; } else { $tls = ...; }
}
```

and a non-TLS stream is upgraded in `doHeloCommand()` whenever the server advertises `STARTTLS`. So passing `null` gives 465 implicit TLS and 587 plain-plus-STARTTLS - exactly the pairing the Symfony issue you linked calls the only one that works. Both places that build a transport now share one resolver so they cannot drift apart.

`off` is unchanged - it resolved to `false` before and still does, so shops sending unencrypted are bit-identical. Only the `tls` setting changes.

Being explicit about the limits of what I verified: I have no live 587 server here, so I did not run the end-to-end handshake. The test builds the real transport and asserts the resulting stream - 587 is not implicit TLS, 465 still is - and reverting the resolver makes it fail. @ShaiMagal or @Maofree, if either of you can point it at your provider on 587 with Encryption set to TLS, that would close the last gap.

One thing worth deciding separately: Symfony 6.4 gives no way to refuse an offered STARTTLS upgrade, so `off` has always meant "do not start in TLS" rather than "never encrypt". That is pre-existing and unchanged here, but the label is misleading if anyone cares to rename it.

**Comment by bardsynth** [comment]
@boo-code I've updated code of the `classes/Mail.php` in my PS 9.1.4 build and I am able to send emails with encryption set to TLS and port set to 587 (OVH Email Pro plan which uses 587 / STARTTLS exclusively).

**Comment by devmysoft** [comment]
@bardsynth what did you changed in classes/Mail.php to be able to send mail with TLS ? I am in the same situation with ovh.. Also can you do a merge request ? it's very painfull this bug and version after version the bug is still there..

**Comment by bardsynth** [comment]
@devmysoft I've updated `classes/Mail.php` according to fix [#42197 ](https://github.com/PrestaShop/PrestaShop/pull/42197/changes) by @boo-code 
Make sure you have the same email address as in your SMTP configuration in Preferences/Contact/Store tab.
Pull request for this fix has been already approved as I can see.

**Comment by jolelievre** [comment]
Resolved by https://github.com/PrestaShop/PrestaShop/pull/42197
