### ISSUE TITLE
File manager is not loaded for one administrator

### ISSUE THREAD

**Issue by GBteamFr** [PrestaShop/PrestaShop#37626]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I am facing a strange issue. This concerns the Prestashop image manager, in the text editor. 
When I am logged in as SuperAdmin (the account with which I installed Prestashop), I have no problem, the image manager is displayed well and it works normally.
The problem appears when I log in with my client's account (who is also a SuperAdmin), from his account, impossible to display the image manager, the window appears but remains white. I did the test from the same computer and the same browser, but also on another computer or on another browser. Same observation, The problem is therefore linked to this second SuperAdmin account, but why?

Below you can find the screenshot of with the bug visible and the console displaying the errors. I would like to point out that these errors are not present if I am connected with the account which does not pose a problem.

![Image](https://github.com/user-attachments/assets/8efe7795-0919-4a03-8882-31bc333f662b)

Thanks for your help

### Steps to reproduce

1 Create a new SuperAdmin account
2 Log in with this new account
3 Go to "Appearance > Page" and edit a page
4 try to add an image with the file manager

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.31

**Comment by paulnoelcholot** [comment]
Hello @GBteamFr,

I try to reproduce your issue but as you can see, I can't : https://www.loom.com/share/fe2aceabc16343098a807138d3070bbf?sid=ec2d164b-b47b-41a4-a4d5-3f2e5ffdc2a0

Did I miss something?

Thanks for your feedback!

**Comment by GBteamFr** [comment]
Thanks @paulnoelcholot for your reply. I don't really know what to tell you. I just did a new test, by creating a new additional SuperAdmin account. On my side I reproduce the problem. Same errors on browser console.

**Comment by paulnoelcholot** [comment]
Hello @florine2623 

I think it's related to its environment but can you test it yourself if in doubt?

Thanks

**Comment by Hlavtox** [comment]
@GBteamFr Try to disable the bundled modules you don't need, like ps_edition_basic. The JS issue comes from it probably.

**Comment by GBteamFr** [comment]
@Hlavtox Thanks for your reply, i tried to disable the module "PrestaShop Edition Basic" but it didn't work. 
I remind you that I have no problem if I connect with the initial SuperAdmin account, so I doubt it's related to a module, but I could be wrong.

**Comment by Hlavtox** [comment]
@GBteamFr I have one idea! Do the admins have the same language in BO?

Try to enable debug mod and open the filemanager, maybe it will show some error in the modal

**Comment by GBteamFr** [comment]
@Hlavtox the language is the same (FR) for all admins.

The debug mod revealed this error : 
Fatal error: Uncaught Error: Call to a member function get() on null in /htdocs/modules/ps_mbo/ps_mbo.php:288 Stack trace: #0 //htdocs/modules/ps_mbo/ps_mbo.php(360): ps_mbo->get() #1 /htdocs/modules/ps_mbo/src/Traits/Hooks/UseActionObjectEmployeeUpdateBefore.php(38): ps_mbo->getAdminAuthenticationProvider() #2 /htdocs/classes/Hook.php(1077): ps_mbo->hookActionObjectEmployeeUpdateBefore() #3 /htdocs/classes/Hook.php(418): HookCore::coreCallHook() #4 /htdocs/classes/Hook.php(983): HookCore::callHookOn() #5 /htdocs/classes/ObjectModel.php(773): HookCore::exec() #6 /htdocs/classes/Employee.php(249): ObjectModelCore->update() #7 /htdocs/adminxxxxxxxx/init.php(93): EmployeeCore->update() #8 /htdocs/adminxxxxxxx/filemanager/config/config.php(10): require_once('/homepages/4/d4...') #9 /htdocs/adminxxxxxxxx/filemanager/dialog.php(2): include('/homepages/4/d4...') #10 {main} thrown in /htdocs/modules/ps_mbo/ps_mbo.php on line 288

**Comment by Hlavtox** [comment]
Doesn't even surprise me anymore, just uninstall `ps_mbo`, if you don't need it.

**Comment by GBteamFr** [comment]
Thanks a lot for your help. The file manager is fixed !
Your last answer makes me think that ps_mbo is a regular problem?

Thank you all

**Comment by Hlavtox** [comment]
@GBteamFr One one of my best friends @ShaiMagal is running the biggest prestashop hosting in our country. And lately, when shop is not working, fifty-fifty chance that some of the modules bundled in the commercial distribution are the cause.

**Comment by xsalaberria** [comment]
Hello, I have the same problem.
I tried to uninstal ps_mbo , it doesnt work

can you help me ?

Prestashop 8.2, PHP : 8.1.31

Thanks

**Comment by web-burn** [comment]
The problem with file manager is still exist in PrestaShop 8.2.1. Please fix it. I see the empty window in file manager in many shops!
