### ISSUE TITLE
Automated install with Traefik `PS_ENABLE_SSL=0` causes `ERR_TOO_MANY_REDIRECTS` in the user interface

### ISSUE THREAD

**Issue by Rufmord** [PrestaShop/PrestaShop#39657]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I am installing PrestaShop in a containerized environment. Specifically Kubernetes. The twist here is the reverse proxy which handles my tls certificates. I use Traefik here. I am also using MariaDB.

## Configuration
I configure the following environment variables for the container:
```yaml
env:
  - name: PS_INSTALL_AUTO
    value: "1"
  - name: PS_DOMAIN
    value: "prestashop.k8s.domain.tld"
  - name: DB_SERVER
    value: prestashop-mariadb-cluster-primary
  - name: DB_NAME
    value: prestashop
  - name: DB_USER
    value: root
  - name: DB_PASSWD
    valueFrom:
      secretKeyRef:
        name: mariadb
        key: root-password
  - name: PS_ENABLE_SSL
    value: "0"
  - name: ADMIN_MAIL
    valueFrom:
      secretKeyRef:
        name: prestashop
        key: admin-mail
  - name: ADMIN_PASSWD
    valueFrom:
      secretKeyRef:
        name: prestashop
        key: admin-password
  - name: PS_DEV_MODE
    value: "1"
  - name: PS_COUNTRY
    value: "DE"
  - name: PS_LANGUAGE
    value: "de"
  - name: PS_CURRENCY
    value: "EUR"
  - name: PS_TIMEZONE
    value: "Europe/Berlin"
```
The variables are propely mapped in the container, I checked them with `env`.

## Installation
```
* Checking if prestashop-mariadb-cluster-primary is available...

* DB server prestashop-mariadb-cluster-primary is available, let's continue !

* Setting up install lock file...

* Reapplying PrestaShop files for enabled volumes ...

* Copying files from tmp directory ...

* No pre-install script found, let's continue...

* Installing PrestaShop, this may take a while ...

* Launching the installer script...
Testing database settings
Installing database
Dropping database tables
Installing default data
Truncating database
Populating database
Configuring shop
Installing theme classic
Installing modules on disk
Installing fixtures
The admin folder was renamed into admin116utjmpmtfme65sr6x/
You can now access your backoffice at http://prestashop.k8s.domain.tld/admin123randomstring/.
-- Installation successful! --

* Removing install folder...

* No post-install script found, let's continue...

* Setup completed, removing lock file...

* Almost ! Starting web server now


* No init script found, let's continue...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.255.0.164. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.255.0.164. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 29 16:14:43.488104 2025[] [mpm_prefork:notice[] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) configured -- resuming normal operations
[Mon Sep 29 16:14:43.488176 2025[] [core:notice[] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
After this installation I can access the admin interface on `http://prestashop.k8s.domain.tld/admin123randomstring/` where my reverse proxy is redirecting to https. But if I want to access the user interface on `http://prestashop.k8s.domain.tld/` I get the error `ERR_TOO_MANY_REDIRECTS` in any browser. This is most likely to the cause I configured PrestaShop with SSL disabled because of my reverse proxy.
```
10.255.0.21 - - [29/Sep/2025:16:15:49 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:50 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:50 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:50 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:50 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:50 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:51 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:51 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:51 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:51 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
10.255.0.21 - - [29/Sep/2025:16:15:51 +0000] "GET / HTTP/1.1" 302 240 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
```

### Expected behavior

The expected behavior is a working site, not `ERR_TOO_MANY_REDIRECTS`.

### Steps to reproduce

I provide here the Kubernetes Manifests, but a simple Docker install with the same environment variables should also be enough.
# Kubernetes Manifests
## Deployment
```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-prestashop
  labels:
    app.kubernetes.io/name: prestashop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: "prestashop/prestashop:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PS_INSTALL_AUTO
              value: "1"
            - name: PS_DOMAIN
              value: "prestashop.k8s.domain.tld"
            - name: DB_SERVER
              value: prestashop-mariadb-cluster-primary
            - name: DB_NAME
              value: prestashop
            - name: DB_USER
              value: root
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: root-password
            - name: PS_ENABLE_SSL
              value: "0"
            - name: ADMIN_MAIL
              valueFrom:
                secretKeyRef:
                  name: prestashop
                  key: admin-mail
            - name: ADMIN_PASSWD
              valueFrom:
                secretKeyRef:
                  name: prestashop
                  key: admin-password
            - name: PS_DEV_MODE
              value: "1"
            - name: PS_COUNTRY
              value: "DE"
            - name: PS_LANGUAGE
              value: "de"
            - name: PS_CURRENCY
              value: "EUR"
            - name: PS_TIMEZONE
              value: "Europe/Berlin"
          volumeMounts:
            - name: prestashop-data
              mountPath: /var/www/html
      volumes:
        - name: prestashop-data
          persistentVolumeClaim:
            claimName: release-name-prestashop
```
## PersistentVolumeClaim
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-prestashop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
## Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-prestashop
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: prestashop
```
## Secret Example
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prestashop
type: Opaque
stringData:
  admin-mail: "user@domain.tld"
  admin-password: "somePassword"
```

### PrestaShop version(s) where the bug happened

Container Image version 8

### How you installed PrestaShop

Containerized in Kubernetes

**Comment by Rufmord** [comment]
I investigated a little bit more.
If I activate the SSL and set a trusted proxy as stated in this issue https://github.com/PrestaShop/PrestaShop/issues/39282#issuecomment-3300257330 from this merge request https://github.com/PrestaShop/PrestaShop/pull/35761
```yaml
- name: PS_ENABLE_SSL
  value: "1"
- name: PS_TRUSTED_PROXIES
  value: "127.0.0.1,10.0.0.0/8" # 10.0.0.0/8 is the cluster IP range
```
then I get the exact same message in the admin interface that SSL is activated and I should click on that link.
<img width="1206" height="976" alt="Image" src="https://github.com/user-attachments/assets/4c15d5e6-90a9-456c-9dd1-a7de05012923" />
If I do this, then I get this error:
```
RuntimeException:
Infinite redirection detected, please fill in the 'PS_TRUSTED_PROXIES' environment variable or disable the PS_SSL_ENABLED configuration

  at /var/www/html/src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php:72
  at PrestaShopBundle\EventListener\Admin\SSLMiddlewareListener->onKernelRequest(object(RequestEvent), 'kernel.request', object(EventDispatcher))
     (/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure)), 'kernel.request', object(RequestEvent))
     (/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)
     (/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2, false)
     (/var/www/html/vendor/symfony/http-kernel/EventListener/ErrorListener.php:117)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException(object(ExceptionEvent), 'kernel.exception', object(EventDispatcher))
     (/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure)), 'kernel.exception', object(ExceptionEvent))
     (/var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:239)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(RuntimeException), object(Request), 1)
     (/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:132)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(RuntimeException), object(Request))
     (/var/www/html/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:84)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::{closure:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure():78}(object(RuntimeException))
     (/var/www/html/vendor/symfony/error-handler/ErrorHandler.php:538)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(RuntimeException))      
```

**Comment by florine2623** [comment]
Hello @Rufmord ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by PululuK** [comment]
Hi @Rufmord , i have exactly the same issue ... did you found a solution ?

**Comment by Rufmord** [comment]
Hello @PululuK unfortunately not. I tried many different things, but could not figure out any solution that the user and admin interfaces work simultaneously.

**Comment by ChillCode** [comment]
Aplied https://github.com/PrestaShop/PrestaShop/issues/39190#issuecomment-3179194274 and solved a similar issue, not sure is the same related to PS_TRUSTED_PROXIES

I was not using traefik, but i guess is the same issue in all cases, that logic is wrong so the patch is valid.

**Comment by prusayn** [comment]
@ChillCode Yes, back office is not using PS_TRUSTED_PROXIES value at all, that's why frontend is working, just admin login page and dashboard is unusable. It will fail with any proxy where `X-forwarded` headers are used.

I've created PRs:
9.0.x: https://github.com/PrestaShop/PrestaShop/pull/39800
8.2.x: https://github.com/PrestaShop/PrestaShop/pull/39801

**Comment by ChillCode** [comment]
Thanks for the PR @prusayn 

May @PululuK can post the results in the PR so it's already tested by a maintainer.

**Comment by adi-itgg** [comment]
any updates? had same issue here...

**Comment by prusayn** [comment]
Resolved conflicts, waiting for approval

**Comment by ZetaMap** [comment]
I tried applying the fix myself on the latest docker version, but it didn't change anything. Even with the environment variable and the field in the '.env' file set.
I've tried other things and debugging it, but I'm still getting the error "Infinite redirection detected, please fill in the 'PS_TRUSTED_PROXIES' environment variable or disable the PS_SSL_ENABLED configuration."
So i patched the related file myself to disable this check and it worked for me, the pages are correctly redirected.
So here is a temporary fix (work around) of this problem:
```patch
diff --git a/src/PrestaShopBundle/Controller/Admin/LoginController.php b/src/PrestaShopBundle/Controller/Admin/LoginController.php
--- a/src/PrestaShopBundle/Controller/Admin/LoginController.php
+++ b/src/PrestaShopBundle/Controller/Admin/LoginController.php
@@ -223,7 +223,7 @@ class LoginController extends PrestaShopAdminController
         }

         $sslEnabled = (bool) $this->getConfiguration()->get('PS_SSL_ENABLED');
-        if ($sslEnabled && !$request->isSecure()) {
+        if (false && $sslEnabled && !$request->isSecure()) {
             $maintenanceIpConfiguration = $this->getConfiguration()->get('PS_MAINTENANCE_IP');
             if (empty($maintenanceIpConfiguration)) {
                 $maintenanceIps = [];
diff --git a/src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php b/src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php
--- a/src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php
+++ b/src/PrestaShopBundle/EventListener/Admin/SSLMiddlewareListener.php
@@ -36,7 +36,7 @@ class SSLMiddlewareListener 
     public function onKernelRequest(RequestEvent $event): void
     {
         // already SSL, do nothing more
-        if ($event->getRequest()->isSecure()) {
+        if (true || $event->getRequest()->isSecure()) {
             return;
         }

```
