### ISSUE TITLE
doctrine throws error from the beginning: There is no column with name "theme_name" on table "ps_image_type".

### ISSUE THREAD

**Issue by smoebody** [PrestaShop/PrestaShop#40258]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After a brand new  installation with docker the module-page lists ca. 40 modules which needs upgrade. At least the upgrade of 

> PrestaShop Marketplace in your Back Office
> v5.1.0 -> v5.2.1 

breaks the entire installation.

After investigating with cli-console i found that `doctrine:schema:validate` throws an error - also on a brand new installation:

```
root@7e555091bfb4:/var/www/html# php bin/console doctrine:schema:validate

Mapping
-------


 [OK] The mapping files are correct.


Database
--------

13:33:34 CRITICAL  [console] Error thrown while running command "doctrine:schema:validate". Message: "There is no column with name "theme_name" on table "ps_image_type"." ["exception" => Doctrine\DBAL\Schema\Exception\ColumnDoesNotExist^ { …},"command" => "doctrine:schema:validate","message" => "There is no column with name "theme_name" on table "ps_image_type"."]

In ColumnDoesNotExist.php line 16:

  There is no column with name "theme_name" on table "ps_image_type".


doctrine:schema:validate [--em EM] [--skip-mapping] [--skip-sync] [--skip-property-types]
```

My speculation is that the `schema-update` fails while upgrading the module and therefore leaves the entire installation in an unusable state.

### Expected behavior

To upgrade modules without any errors occuring.

### Steps to reproduce

1. install prestashop according to the [guidelines](https://devdocs.prestashop-project.org/9/basics/installation/environments/docker/)
2. login to admin backend
3. navigate to module management
4. click 'upgrade' next to module 'PrestaShop Marketplace in your Back Office'

an error occurs and on page-reload the installation answers with 500 internal server error.

### PrestaShop version(s) where the bug happened

9.0.1

### How you installed PrestaShop

docker

### PHP version(s) where the bug happened

8.4.12 (docker)

**Comment by kpodemski** [comment]
Hello @smoebody 

I'm afraid that your assumption is wrong, because I don't think we run the doctrine schema sync during module updates. What error do you really have after updating MBO? 🤔

**Comment by merguezzz** [comment]
Same bug with a fresh install php8.4 / ps 9.0.1 when trying to generate SQL queries to create MySQL tables from Symfony style module entities with command `sf doctrine:schema:update --dump-sql` .

It comes from Doctrine entity ImageType constraints based on missing property 'theme_name' , no need to declare it here as name property is already unique.

Fixed with:
```
diff --git a/src/PrestaShopBundle/Entity/ImageType.php b/src/PrestaShopBundle/Entity/ImageType.php
index e88874e..03ad300 100644
--- a/src/PrestaShopBundle/Entity/ImageType.php
+++ b/src/PrestaShopBundle/Entity/ImageType.php
@@ -34,9 +34,7 @@ use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
 /**
  * @ORM\Entity(repositoryClass="PrestaShopBundle\Entity\Repository\ImageTypeRepository")
  *
- * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"name","theme_name"})})
- *
- * @UniqueEntity({"name", "theme_name"})
+ * @ORM\Table()
  */
 class ImageType
 {
```

**Comment by smoebody** [comment]
> Hello [@smoebody](https://github.com/smoebody)
> 
> I'm afraid that your assumption is wrong, because I don't think we run the doctrine schema sync during module updates. What error do you really have after updating MBO? 🤔

Sorry for the delay. I pulled the new image, but the problem persists with upgrading MBO. But at least the shop stays usable now. Only a few pages are not available anymore:
* Overview
* Carecenter
* Marketplace

When i go to "Module Manager" page i get the following notifiaction:
```
Too few arguments to function PrestaShop\Module\Mbo\Distribution\ConnectedClient::__construct(), 5 passed in /var/www/html/var/cache/prod/admin/ContainerI2r7j2m/getConnectedClientService.php on line 21 and exactly 7 expected
```
